### ISSUE TITLE
Duplicate notification of updates

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#100]
**Package Name or Section of Feren OS where this bug resides**
discover, mint-update

**Describe the bug**
There appears 2 (two) notification indicators when software updates are available - clicking one opens KDE Discover, and the other Mint Update Manager.

**Expected behavior**
It might be a better idea to have only one (e.g. the Mint's faster update manager) startup automatically.

**Comment by feren** [comment]
The Discover one only appears if you've installed discover.

**Comment by Sadi58** [comment]
OK. I think I'll uninstall Discover then because as a Linux Mint user just testing if Feren OS is a step forward Update Manager is more attractive to me.
But AFAIK I didn't install Discover; both came pre-installed. So maybe you should check the default setup?

**Comment by feren** [comment]
plasma-discover isn't pre-installed.

**Comment by Sadi58** [comment]
Maybe it got installed when I was installing something else. ;-)
So it seems you recommend Store (instead of Discover), Synaptic Package Manager (instead of Muon), (Mint) Update Manager and QApt Package Installer for all software management needs.
I'll uninstall Discover then to avoid duplication.
