### ISSUE TITLE
Feren theme - Synaptic Package Manager

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#104]
**Package Name or Section of Feren OS where this bug resides**
feren-theme

**Describe the bug**
Toolbar background color does not cover the empty part on the right, leaving a lighter area there.
![Screenshot_20200114_184858](https://user-images.githubusercontent.com/6375934/72359382-3b705780-36ff-11ea-8e91-497cfba91047.png)
_This is actually Synaptic Package Manager's fault, but some themes include a special fix to create a uniform background there - although this is a very minor issue._

**Comment by feren** [comment]
This is fixed in the new WIP GTK theme, pending its first release.

**Comment by feren** [comment]
Fixed.
