### ISSUE TITLE
User Manager KCM has non-working Log In Automatically checkbox

### ISSUE THREAD

**Issue by dancaer69** [feren-OS/Bug-Reporting-Center#105]
Hello,
I installed feren os 2-3 days ago(switched from linux mint cinnamon), and I cannot use autologin option from plasma settings. I check the checkbox to enable autologin(input root password) and apply the change. I don't get any error, but after I reboot, I need to login again(autologin doesn't work), and when I open settings for autologin the checkbox is cleared again. Seems that reverts to default value(unchecked).
EDIT:
I get these errors:

> QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
QDBusArgument: read from a write-only object
kf5.kauth: Tried to start an invalid action
log_user_manager: fail "Attempted to execute a non valid action"

**Comment by feren** [comment]
What dialog did you use? To enable autologin, you should go into **Login Window** and then enable it from there:

![image](https://user-images.githubusercontent.com/11057934/72566266-67c8d700-38ab-11ea-9323-acf32f71a00a.png)

**Comment by dancaer69** [comment]
I don't have engish language, so I will translate:
Customize -> User Details -> User Manager(label of that window)
There my username is pre-selected list at left side, and in right side there are textboxes about:
Username:
Real Name:
Email address:
Change password:
And 2 checkboxes after those:
- enable administrator privelages for this user
- login automatically
I was trying to do it from there. I cannot find find this window you posted in settings.
I downloaded the latest version Feren OS x64.iso. I'm using the Feren Os theme, and the dark one before that(changed it because of unreadable white font color in a qt application I'm using a lot). But in both I had the same Settings layout and the same issue.
I managed to enable autologin from lightdm config file by manually edited it, but this checkbox is still unchecked.

**Comment by dancaer69** [comment]
I just found the window. It's not part of the system settings which I use. It's a standalone application. 
Seems that this option is for kde' s desktop manager(kdm), which feren doesn't use.

**Comment by feren** [comment]
Gonna mark this as upstream and investigate why it's there to begin with in User Manager, as I don't really see why it is even there when the Plasma supported DM isn't installed, and even then the SDDM settings page has an autologin option in there.

**Comment by feren** [comment]
So, uh, from what I can get:
No one really seems to know why there's still a checkbox there, probably. That and the User Manager KCM (KDE Control Module - pages in System Settings) is pending a rewrite anyway so it's probably not going to be fixed until that KCM is rewritten.

**Comment by feren** [comment]
For now, to do autologin make use of **Login Window**.

**Comment by dancaer69** [comment]
Ok, thanks!

**Comment by dominichayesferen** [comment]
This was fixed in the Users KCM rewrite many Plasma versions ago by just lacking the checkbox entirely. As such, now I've noticed it's still open...
