### ISSUE TITLE
Charging Android phone doesn't automatically starts on connection

### ISSUE THREAD

**Issue by dancaer69** [feren-OS/Bug-Reporting-Center#106]
**Describe the bug**
When connecting an android phone device in a usb port the charge doesn't start, as happens to every linux distro I've use until now, but I need to change(from the device) to mtp transfer mode to enable charging. The phone has 'Only charge" option as default.

**Steps to Reproduce**
-Connect Android device to usb port
-The device start charging if feren hasn't load the graphical environment(after a reboot)
-The device stop charging when plasma loads or in lightdm login screen
-Device starts charging when change to mtp file transfer mode
-Device stops charging again if I change mode back to default "Charge only" option. 

**Expected behavior**
When connect an Android device to a usb port, device start to charge automatically.

**Comment by dancaer69** [comment]
Seems, that this happens because of TLP. I found that TLP is a powersaving tool for laptops. It has an autosuspend usb future which is enabled. Also has a blacklist option to exclude devices from autosuspend. I input the device's id there and now it starts charging normally. I run Feren os in a desktpo pc though, so I don't know if is needed at all.

**Comment by feren** [comment]
Is this still happening?

**Comment by dancaer69** [comment]
I removed TLP, so I don't know.
