### ISSUE TITLE
Wastebin Plasmoid and ~/.local/share/Trash/files desync

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#107]
**Package Name or Section of Feren OS where this bug resides**
nemo-plasma-integration

**Describe the bug**
Nemo file manager shows no indication of the full/empty status of the "Rubbish Bin" whereas the Wastebin widget (on either Latte dock or Plasma panel) sometimes shows a red dot, and sometimes doesn't. For instance, if an item is created and deleted on the Desktop (apparently managed directly by Plasma, and not Nemo file manager) the Wastebin widget immediately and always shows a red dot, which doesn't go away if it is opened by Nemo file manager and Empty Rubbish Bin button is pressed; the red dot goes away when it's emptied directly via right-click on Wastebin widget.

**Additional context**
I think all this might be due to nemo-plasma-integration needing improvement, and lack of indication in nemo file manager itself might be due to a missing trashcan-full symbolic icon.
(I wouldn't prefer replacing Nemo with Dolphin for better integration because I very much like Nemo's actions and scripts which are much easier to manage.)

**Comment by feren** [comment]
nemo-plasma-integration is just there to re-route a few things that differ between Plasma and Nemo to make things work seamlessly despite this, and therefore is not related to the trash icon updating.

Chances are the bug you're mentioning is either an icon set issue with Inspire or just an upstream Nemo issue. The best way to check for an upstream Nemo bug (regarding the in-Nemo trash icon) is to install the 'mint-y-icons' icon theme from Store, set the icon set to Mint-Y and see if Nemo then has a full trash icon.

**Comment by Sadi58** [comment]
1. It seems this has nothing to do with Latte dock (edited accordingly).
2. We can forget about the Rubbish Bin icon in Nemo file manager's sidebar. It's the same with Mint-Y icon theme, and even if it's not an icon theme issue, it has to be an upstream issue I guess.
3. But there is obviously some inconsistency between Nemo file manager Rubbish Bin and Plasma Wastebin widget behaviors. For instance, when I create and delete 2 files on the Plasma Desktop, and then 2 more in Nemo File Manager Home window, the Wastebin widget I've placed on my Plasma top panel continues to ignore the other 2, telling me there are only 2 items deleted. However, when I click on it, Nemo file manager windows opens and shows 4 items! And what's more strange, once it showed 2 items only whereas Nemo file manager window for ~/.local/share/Trash/files showed 4! And when I emptied the Plasma Wastebin, only those 2 files were gone, but not the other 2 created and deleted in Nemo file manager. All this shows I think that Plasma Wastebin widget is not monitoring the Nemo file manager (~/.local/share/Trash/files) as it should. I don't know which package is responsible for this.

**Comment by Sadi58** [comment]
Here's also a screenshot of how weird things can become - Wastebin indicates there's 1 item deleted, however when I click on it, I see a Trash window of Nemo showing many more files, and when I go to "$USER/.local/share/Trash/files" I see 1 file, because the other files were deleted from my Data partition  for Documents, Downloads, etc. and they are actually in "/media/$USER/Data/.Trash-1000/files". Sometimes only after login, they are also detected by the Wastebin Plasmoid.
![Screenshot_20200118_144150](https://user-images.githubusercontent.com/6375934/72663728-d2daf080-3a06-11ea-89ca-6937fea1aa94.png)
Considering that this is an **upstream** issue (Wastebin Plasmoid and/or Nemo), then it might be worth considering to switch to Dolphin instead of Nemo for better integration. I will personally do so as soon as I can somehow manage to transfer my Nemo Actions and Scripts to Dolphin. ;-)
(Similarly, I cannot get PDF thumbnails in Nemo either)
