### ISSUE TITLE
Drag-and-drop between Nemo file manager and Ark

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#108]
**Package Name or Section of Feren OS where this bug resides**
nemo-ark

**Describe the bug**
It's not possible to drag and drop files between nemo file manager and ark (e.g. to extract files from and/or add files to a zip file) as with file-roller.

**My temporary workaround:** I had to replace ark with file-roller until this is fixed. Maybe this combination should be the default?

**Comment by feren** [comment]
I'm going to assume for now that this is an upstream issue. I'll check in the future though just to be sure.

**Comment by Sadi58** [comment]
I saw this info for nemo-ark package: _Maintainer: Feren OS Team_
But I don't know if this package is only for adding context menu items and nothing to do with drag'n'drop interaction between the two.

**Comment by feren** [comment]
nemo-ark is just a fork of nemo-fileroller that I made for adding context menu items.

**Comment by Sadi58** [comment]
I also think now this issue is probably due to lack of compatibility between Nemo and Ark.
For instance, there's no such incompatibility between Nemo and Krusader.
In this case maybe it's better to replace Ark with File Roller, or Nemo with Dolphin?
