### ISSUE TITLE
Update Manager appears to be broken

### ISSUE THREAD

**Issue by jsmithabq** [feren-OS/Bug-Reporting-Center#109]
I installed from this image:  
-rw-r--r-- 1 jsmith sambashare 1903263744 Jan 18 12:32 'Feren OS x64 Classic Dec 2019.iso'

After the install, from the start-up wizard it suggests upgrading packages.  The first upgrade is for the Update Manager itself.  Upon installation, the Update Manager window crashes, does not reappear,and cannot be started from the menu.

With Linux Mint 19.3, if you follow the same procedure, the Update Manager installs the new Update Manager, the original window disappears, and the (freshly updated) Update Manager main window appears again.  Subsequently, you can also use the Update Manager normally.

So, I have two Feren OS Classic installations, for which I cannot get updated packages via the graphical app, so I used apt-get, but for new users they will not understand why Update Manager fails, and thus how to update a new installation.

P.S.: I've been using Linux since the first kernel release and I've installed dozens of distros gazillions of times. This is my first type testing Feren OS. Except for this one issue, it is a great distro.  Here's hoping you keep the classic distro...  Thanks for all your hard work!

**Comment by feren** [comment]
Make sure Update Manager is on its latest version and that you are on the LM 19.3 base by updating packages once more.

In Terminal:
1. `sudo apt update`
2. `sudo apt dist-upgrade -y`
3. Try relaunching Update Manager once it's all done
