### ISSUE TITLE
Default file manager: Nemo vs Dolphin

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#110]
This **issue** is **not a bug** but a matter of decision by Feren OS developers, considering feedback from users here perhaps. ;-)

When I began to use Feren OS recently I've encountered several problems of integration between KDE Plasma DE and Nemo File Manager. The most important one was Wastebin plasmoid not syncing properly with Nemo file manager.
As a long time Linux Mint user I like Nemo very much (particularly for user-friendly management of Nemo Actions and Scripts unlike other file managers, including Nautilus and Dolphin) but I thought at the end that I should install and use Dolphin as the default file manager in Feren OS and maybe keep Nemo in reserve for some file operations in which I make use of a number of Nemo Actions and Scripts - at least I can somehow transfer them to Dolphin. In addition, I will also use use Nemo and/or Krusader for file operations with admin privileges which Dolphin doesn't support unfortunately.

So maybe other users can also express their opinion here about the choice of default file manager in Feren OS.
![Screenshot_20200120_120540](https://user-images.githubusercontent.com/6375934/72714835-77347280-3b80-11ea-911e-238adfb81c9d.png)

**Comment by feren** [comment]
Moving this to #111.
