### ISSUE TITLE
Can not try FerenOS

### ISSUE THREAD

**Issue by DasJott** [feren-OS/Bug-Reporting-Center#112]
**Package Name or Section of Feren OS where this bug resides**
FerenOS - Recent Version x64

**Describe the bug**
After boot I can choose a language. No matter what language I choose, next is an error message stating: "You need to boot the kernel first", which I think is your task.

In VirtualBox it doesn't seem to get over the part where it detects the virtual machine.
CPU is pretty busy and fan is running like a vacuum cleaner, but it seems to just freeze. It looks like it installed the guest additions but then nothing happens at all.

**Steps to Reproduce**
Download FerenOS, dd on USB, reboot or put it into Virtualbox

**Expected behavior**
FerenOS is booting, one can play with it

**Comment by feren** [comment]
I'll check the ISO later to see if I can reproduce this issue.

**Comment by DasJott** [comment]
That seems to have been an issue with screen resolution and too less ram on the vm.
Doubled the team to 2G and it worked. Started the ISO and the live part ran fine. Installed it and that installation end up with a black screen on startup. 
Will try it again later.

**Comment by DasJott** [comment]
It seems EFI is not supported. After disabling, I could boot it. I found out, that the installation didn't work. When I wanted to install again, I got this:
![image](https://user-images.githubusercontent.com/6298761/73208652-1a6c2580-4147-11ea-9230-27ae0e5a8d61.png)

I think I am not supposed to use FerenOS ...

**Comment by feren** [comment]
Can't reproduce this on the latest standard version ISO after freshly downloading it off of SourceForge and flashing it and booting into it.

**Comment by feren** [comment]
As for the install fail image, https://github.com/calamares/calamares/issues/1163.

**Comment by feren** [comment]
As for the black screen: Check the Graphics Controller used in the VM in VirtualBox. In 6.0 onwards, VirtualBox introduced, for some reason, a default graphics controller that doesn't work with Ubuntu-based Operating Systems that well. You can change it to something that works, such as VBoxVGA, via VM Settings -> Display -> Graphics controller.

**Comment by feren** [comment]
Do these issues still occur on 2020.01?

**Comment by DasJott** [comment]
I may have to check with live boot again. I might get it this weekend. 

For install I decided to take manjaro cinnamon for now..
