### ISSUE TITLE
update manager

### ISSUE THREAD

**Issue by coolvan** [feren-OS/Bug-Reporting-Center#114]
(dpkg-preconfigure:11634): Gdk-WARNING **: 10:06:26.440: Cannot transform xsetting gtk-menu-images of type gchararray to type gboolean

(dpkg-preconfigure:11632): Gdk-WARNING **: 10:06:26.540: Cannot transform xsetting gtk-button-images of type gchararray to type gboolean

(dpkg-preconfigure:11632): Gdk-WARNING **: 10:06:26.540: Cannot transform xsetting gtk-menu-images of type gchararray to type gboolean

(Reading database ... 353367 files and directories currently installed.)
Preparing to unpack .../base-files_10.1ubuntu2.8_amd64.deb ...
Warning: Stopping motd-news.service, but it can still be activated by:
  motd-news.timer
Unpacking base-files (10.1ubuntu2.8) over (10.1ubuntu2.7) ...
Replaced by files in installed package feren-info-kde (2020.01.0.0.0) ...
dpkg: error: dpkg frontend is locked by another process
E: Sub-process /usr/bin/dpkg returned an error code (2)
A package failed to install.  Trying to recover:
dpkg: error: dpkg frontend is locked by another process

**Comment by feren** [comment]
It seems your DPKG glitched or something. I can't see anything in the mentioned packages in this that I maintain that'd cause this. Marking this as Non Producible for the time being.
