### ISSUE TITLE
Reboot or shutdown fails after installation - SQUASHFS error

### ISSUE THREAD

**Issue by holzboa** [feren-OS/Bug-Reporting-Center#115]
I installed the Feren Os x64.iso on a Notebook and a Mini-PC. The USB stick used for installation works fine with other distros.
The same message loops when the system request to remove the install medium and press Enter.

`SQUASHFS error: Unable to read page, block ebad62, size 221f4`

**Comment by feren** [comment]
Hard Reset your machine to get around that. At that point the system was ready to safely reboot/power off anyway.

**Comment by feren** [comment]
Is this issue still happening on the latest revision of the standard January 2020 Snapshot ISO?

**Comment by feren** [comment]
Seems fixed now on my end, so...
