### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by ApertureDevelopment** [feren-OS/Bug-Reporting-Center#116]
Hello feren, it's me again and again with installation issues.

When Feren OS installs at about 80% I get a installation fail with the following message:

![IMG_20200130_150731](https://user-images.githubusercontent.com/16450982/73681415-9376fa00-46be-11ea-8d06-ca239d1c0f5b.jpg)

![IMG_20200130_150655](https://user-images.githubusercontent.com/16450982/73681520-cb7e3d00-46be-11ea-8331-d2fc6adcb450.jpg)

**Comment by holzboa** [comment]
I guess you have "Secure Boot" turned on in the UEFI. The same happened when i tried to install the first time. In newer Ubuntu releases the installer got a option for secure boot included. I think we'll see it in Feren OS soon.
Just turn off secure boot and it should work.

**Comment by ApertureDevelopment** [comment]
Secure boot **is** disabled. This error is unrelated to secure boot

**Comment by feren** [comment]
That error is saying your /boot/efi mount doesn't look like an EFI Partition. Make sure a /boot/efi is set during manual partitioning. If you're not using manual partitioning, let me know.

PS: You might want to try formatting the /boot/efi partition if all else fails.

**Comment by ApertureDevelopment** [comment]
I did set the "bootable" flag to a partition I created for /boot/efi, if thats not the right one, I honestly don't know which to set of the +10 flags

**Comment by feren** [comment]
Try turning on format for that partition and then installing.

**Comment by ApertureDevelopment** [comment]
Everytime I try I delete and re-create the partitions, that should format them shouldn't it? But I can try again I guess

**Comment by radicaldurian** [comment]
I have exactly same problem. I tried many distros on my system before, this is first time i have got some installation issue.

**Comment by feren** [comment]
Is this issue still occuring in Feren OS April 2020 Snapshot?
