### ISSUE TITLE
Latte settings textures become visible when opening subwindow in Konsole that turns off Compositor

### ISSUE THREAD

**Issue by holzboa** [feren-OS/Bug-Reporting-Center#117]
I use a script running in a terminal. The first terminal shows the radiostations and plays (ffplay) the chosen station in a 2nd terminal window.
As soon as the second terminal pops up pieces of the Dock-Settings background appear and  disappear again when i close the terminal.
The same fragments i see sometimes when i switch fast with "alt+tab".

I use the same script in Endeavour OS/ XFCE, no fragment there.
Maybe not a bug but i was surprised to see that here. Is this behaviour related to Plasma?

![radio sh](https://user-images.githubusercontent.com/59257180/73700556-2166db00-46e7-11ea-847f-9e2bef6d0b90.png)

**Comment by feren** [comment]
That's triggered by the Compositor turning off for that application. The pieces of Latte Dock settings getting visible when Compositing is off should be reported to the Latte Dev at bugs.kde.org if it's not already reported.

**Comment by feren** [comment]
FYI, it'll be way less apparent if you use Feren OS or Cupertino Layout, and it'll not be there at all with all other layouts.

**Comment by holzboa** [comment]
You are right, only happens using the Unity Layout - thanks for that - i missed it.
Is there place here to beg for a "shortcuts-overlay"? As you really do a good job in combining things, pleeeaaase.. would be a gread addition. 
Not really like Unity had or ElementaryOS has, more the way KeyCue/MACOSX to show keyboard-shortcuts of the actually used program.
I posted the issue to [https://bugs.kde.org/show_bug.cgi?id=417619](url)

**Comment by holzboa** [comment]
I got a answer from KDE.ord. As it turns out it's easy to fix in Compositor (WM_CLASS(STRING) = "kcmshell5", "kcmshell5):

![compo](https://user-images.githubusercontent.com/59257180/74522826-41cf3a80-4f1c-11ea-8bfe-e05bb8ec051c.png)

Unchecked and works!
