### ISSUE TITLE
FerenOS Next KDE - installation failure on multiple PC's & Laptops

### ISSUE THREAD

**Issue by slickmrick** [feren-OS/Bug-Reporting-Center#118]
**Package Name or Section of Feren OS where this bug resides**
FerenOS-Next - unable to install on multiple-PC's.
During installation of FerenOS-Next

**Describe the bug**
1. Am getting the SAME ERROR on multiple PC's & Laptops that ALL work fine with Windows 10-64bit, as well as various other Linux Distros (mainly Ubuntu 18.04.x LTS or Debian 9/10, but also tried ClearOS & Solus on some of them). No matter which method I use to install FerenOS-Next, I always get to the SAME point right at the very end of the install process where calamares gets to about 90% and then displays message: "Installation Failed. blah blah blah... External command failed to finish." Then a small Error pop-up box appears saying: "Installation Failed External command failed to finish. Command feren-installer-tools refresh-apt failed to finish in 120 seconds. There was no output from the command."
If I ignore the error messages & try to reboot, it fails with a "No operating system found" error from BIOS. I have also tried installing boot-repair (in the Live OS) & running the auto-repair option. boot-repair APPEARS to have repaired the boot drive (no errors to indicate repair failed). But then I get multiple Terminal boxes appearing CONTINOUSLY, faster than I can close them! I have used boot-repair on many, many systems over the last 10+ years & have NEVER seen boot-repair do this before! (BTW, even if I manage to kill all the terminal boxes & reboot the system, it still fails with BIOS saying no bootable OS found on drive)

**Steps to Reproduce**
1. Tried the following:
Re-downloading installation ISO images (SAME problem on ALL release candidates 1,2 & 3 (latest as of 4th Feb 2020). Can't see anywhere on Feren download site any way of verifying the ISO file with checksum. Tried downloading ISO's from multiple PC's running either Win10 or Linux.
2. Tried downloading on my Work PC as well as various other friends of mine just to eliminate my home connection (but I've never had ANY issues downloading other Distros at home!)
3. Tried Burning ISO's using multiple DVD-Writers (internal) and even purchased TWO different USB Burners (as I thought may be the 1st one could be faulty!) - All images burned at x4 speed or less & verified against the downloaded ISO with TDK branded DVD-R or DVD+R media.
4. Tried creating bootable USB flash-drives (must have tried at least 5 drives that I've used to install various other Distros) & again purchased a few NEW ones which have same issue (created using latest version of etcher 64bit appimage on Linux & also Rufus under Win10).
5. Yes, I am connected to internet during ALL installs (I think it won't allow you to start installation without a connection?)
6. Yes, UEFI/EFI set to LegacyBoot in BIOS. (But also tried with UEFI/EFI enabled, just in case!). In fact, some of the PC's/Laptops don't even support UEFI/EFI in BIOS.
7. Tried various spinner SATA HDD's, 2.5" & 3.5". Tried SSD's (various brands/sizes, min 120GB. mainly Samsung Evo Pro's/Kingston/Intel). Tried various M2.NVMe drives as well.
8. All attempts to install are on BARE-METAL real PC/Laptop hardware (not VM's) with NO OTHER drives connected (internal or USB, other than Feren Boot DVD/Flash Drive). No Dual-Boot setups either. Single OS on single drive.
9. Tried using GPARTED before starting installation & DELETING ALL existing partitions.
10. Tried installing Boot-Loader to MBR & also to "/"
11. Tried manually partitioning drive using same partition layout that the calamares installer creates (if you let it auto-partition & use the whole drive (erase OR replace options both fail with same error)

**Expected behavior**
Installation to complete! (FYI, FerenOS Classic installs without any issues on ALL the PC's/Laptops that have this issue with FerenOS-Next-KDE, but I really don't like the default desktop & prefer KDE-Plasma)

**Screenshots**
See my description of error messages above. Nothing else to show!

**Additional context**
I noted that the ISO I downloaded on the 26th Dec 2019 appears to imply that it is the FINAL (non-beta) release of FerenOS-Next but I found an ISO released AFTER this date, which says it's the Release Candidate 3 ISO (yes, I've tried RC1 & RC2). Does this mean that FerenOS-Next is NOT at the FINAL RELEASE stage yet? It's also confusing, as all the ISO's have the same name ("Feren OS x64.iso") regardless of which version they are. Why don't you actually give the ISO's names that reflect the version or at least the date of release?
On your website it shows the latest release is the January 2020 Snapshot - isn't that the same as the RC3 ISO that you get from SourceForge.net??? Again, hard to tell, as all the ISO's have the same name!
I am going to try installing FerenOS-Next into a VM (Virtual Box & VMWare Workstation) & if that works, will try to clone the VM to a bare-metal PC (Clonezilla, Rescuezilla & maybe even try a Timeshift restore!) as FerenOS has been one of my favourite Distros of all time, but I have not ended up using it as my daily/production OS as the older FerenOS (now classic) did not use KDE, which is my favourite DE ATM!

**Comment by feren** [comment]
January 2020 Snapshot was released in January 2020.

**Comment by slickmrick** [comment]
Hi all! Just wanted to give you an update on my FerenOS-Next installation issues!
In my description of the error message, I stated that the error pop-up box says that the failure 
was due to "feren-installer-tools refresh-apt failed to finish in 120 seconds". I did actually try to manually run this command by opening a terminal box & it completed in about 30 seconds without
any errors, so not sure why it failed to run during the installation process. Despite manually running
the command it still failed to boot into FerenOS-Next. So I then switched to plan B!

I managed to get FerenOS-Next to work using the following method:
1. I installed FerenOS-Next into a VirtualBox-VM (using the exact same method that I was using to
install on a real physical PC or Laptop that ended up failing near the end of the installation process)
2. After booting into FerenOS-Next on the VM, I ignored the requests to install the VirualBox guest
additions & did a full OS update. I rebooted the VM again to make sure everything was okay.
3. I then set the VM to boot from a Clonzilla Boot CD & booted into Clonezilla.
4. I had a pre-prepared USB flash drive formatted to EXT4 & plugged it into the Host PC & then
allowed the VM to use the drive.
5. I used the basic Clonezilla settings to create a full boot drive backup image to the flash drive.
6. I then booted the real PC using the Clonezilla Boot CD & connected the flash drive with the
FerenOS-Next image & restored the image to the real PC's internal HDD.
7. When I rebooted the real PC it still did not boot into FerenOS-Next (grub errors), so I rebooted
the real PC using the FerenOS-Next live install DVD (actually I used my bootable FerenOS-Next
flash drive) & ran the pre-installed boot-repair package & allowed it to repair the drive using the
default boot-repair options.
8. This time the real PC managed to boot into FerenOS-Next but froze up after a few seconds 
after logging in. I forced the PC to power off & rebooted again. This time the OS was stable after
logging into the desktop. I have been using FerenOS-Next on the real PC for a few days now &
it has been absolutely 100% stable. I am also 100% happy as FerenOS was always my favourite
Ubuntu/KDE distro (second to KDE-Neon).

I have only found 1 small issue with FerenOS-Next so far, and that is that once I have logged into
the Desktop the Discover-updater notification will appear in the bottom panel along with the
system-updates notification but attempting to run either of them results in an error saying that
another update process is currently running! I end up having to close them both, then wait a few
minutes before running sudo update && dist-upgrade in terminal. Also, Discover-updater will find
more updates to install compared to the system-updates, is this normal? I suspect Discover
updates flatpak apps where system-updates doesn't? Anyway, I might need to disable either
Discover-updater or the standard system-updater from autorun/auto-start as there is obviously a
clash going on here!
I will keep you posted of any other issues with FerenOS-Next as & when they occur.
Regards to the developers & FerenOS community in all their hard work in making FerenOS one
of the best/polished distros available.

**Comment by MadCabbit** [comment]
This bug also pops up every time when installing Feren OS (January 2020) in vmware set to UEFI, whether it be manual partitioning or guided, it still results in this error.

**Comment by feren** [comment]
Try 'sudo apt update && sudo apt install feren-calamares-global-settings -y' in Terminal before launching the installer.

**Comment by kaouki** [comment]
I have exactly the same problem. Running the installer and at the end the same message:  "feren-installer-tools refresh-apt failed to finish in 120 seconds"

I tried to run: 'sudo apt update && sudo apt install feren-calamares-global-settings -y' 
befor running the installer but the same problem pops up.

**Comment by feren** [comment]
@kaouki You have an outdated ISO, try using 2020.04's ISO file instead.

**Comment by feren** [comment]
After trying the latest ISO(s), do you still have these issues?

**Comment by kaouki** [comment]
Sorry for the late reply, but downloading the iso from Ecuador took me some time and disputes with my isp. I just installed the latest version and after some UEFI tweaks, everything went fine.

**Comment by feren** [comment]
Fixed in Feren OS 2020 April Snapshot
