### ISSUE TITLE
Dolphin: sorting Places

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#119]
**Package Name or Section of Feren OS where this bug resides**
Dolphin
**Describe the bug**
The sidebar of Dolphin installed from Feren OS repos is a bit different from that in KDE Neon: most importantly, Places are displayed in no meaningful order and cannot be sorted either. It is often impossible to move an item and sometimes ends in some unexpected behavior.

**Expected behavior**
In KDE Neon, Dolphin sidebar shows Places in a logical order: Home at the top, Trash at the bottom, and others in between and in alphabetical order. User can easily add items and manually sort them as well.  

**Additional context**
I tried manually installing dolphin and libdolphinvcs5 packages from KDE Neon repositories, but it made no difference.
![Screenshot_Dolphin-Neon](https://user-images.githubusercontent.com/6375934/73979424-28882600-493f-11ea-8597-1f8bebee4ff7.png)

**Comment by Sadi58** [comment]
I thought it might be useful to note that other KDE apps don't have this issue - i.e. items in Places are sorted as expected (although it might be a good idea to remove the bottom two items under Recent there as well).
![image](https://user-images.githubusercontent.com/6375934/74090824-133b0500-4ac1-11ea-8ca9-16bf5a4beca9.png)

**Comment by dominichayesferen** [comment]
Feren OS has moved over to using KDE Plasma's vanilla Places sidebar listings now that it supplies the ones Feren OS previously added, pretty much. Therefore, this issue is now fixed.

To fix it, delete ~/.local/share/user-places.xbel, ~/.local/share/user-places.xbel.bak and ~/.local/share/user-places.xbel.tb-cache.
