### ISSUE TITLE
a very minor bug with feren-plasma-desktop and feren-plasma-desktop-full packages

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#120]
**Package Name or Section of Feren OS where this bug resides**
nemo-plasma-integration

**Describe the bug**
If the user wishes to replace Nemo with Dolphin file manager, this package complains that feren-plasma-desktop depends on it, so it cannot be removed. 

**Expected behavior**
This package depends on plasma, nemo, etc. and possibly nemo may depend on this to work properly in Feren OS, but feren-plasma-desktop can sure live without it. So it should probably removed from dependencies of feren-plasma-desktop and feren-plasma-desktop-full packages.

**Comment by feren** [comment]
feren-plasma-desktop is a **metapackage**, it should be safely removable.

**Comment by Sadi58** [comment]
Thanks. I was so afraid that I didn't check to see both feren-plasma-desktop and feren-plasma-desktop-full were actually meta-packages. ;-)
