### ISSUE TITLE
Annoying Picture-in-Picture Block?

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#123]
How do i get rid of this stupid block Picture-in-Picture Block

<a href="http://www.imagebam.com/image/37240d1333954587" target="_blank"><img src="https://thumbs2.imagebam.com/f4/3a/ca/37240d1333954587.jpg" alt="imagebam.com"></a>

<a href="http://www.imagebam.com/image/7ba1e01333954410" target="_blank"><img src="https://thumbs2.imagebam.com/6e/53/4e/7ba1e01333954410.jpg" alt="imagebam.com"></a>

It plays in all my videos i play on the Web. This never did that before yesterday on Tuesday. When i got home and turned on my PC i noticed it.

I'm using Vivaldi Browser 2.11.1811.33.

OK so i tried it in Chromium and That Block wasn't there. This is just a Vivaldi issue. If you know how to fix

**Comment by feren** [comment]
Ask on vivaldi.net about that.

**Comment by tjw0lf** [comment]
WTF Dude? You should know how to fix things regardless Feren. What you incorporate in your distro OS You should know and be aware of.

**Comment by tjw0lf** [comment]
There seems to be other people that do not like this as well it sure is annoying it comes up on every video you watch. Vivaldi didn't incorporate a disable switch or turn off button anywhere. I might have to switch browsers because of this. I will wait a little bit but I'm not patient person i like my things the way i set them.

I posted on there forum

https://forum.vivaldi.net/topic/44154/pop-out-video-ubuntu-18-04

https://forum.vivaldi.net/topic/43951/switch-to-disable-picture-in-picture-video-popout-icon?_=1581627689304

Really they go by VOTING 

This isn't Feren OS's fault this is fault of stupid DEV's not thinking outside the box long road ahead
