### ISSUE TITLE
Remove e.g. "brave browser" from taskbar, added as mini program not possible

### ISSUE THREAD

**Issue by Rubenzahl** [feren-OS/Bug-Reporting-Center#124]
**Package Name or Section of Feren OS where this bug resides**
Feren OS with default theme (KDE) / Fresh install
18.04
5.3.0-28-generic

**Describe the bug**
Want to remove an added program from taskbar (removing vivaldi works fine)

**Steps to Reproduce**
I added "brave browser" after installation from Menu with right click -> add to taskbar -> as mini program.
Then I wanted to remove it. But there is no "remove" like there is for vivaldi.

Steps to reproduce the behaviour:
1. Install brave browser (I installed it from repository)
2. Right click in the menu and choose "add to taskbar as mini program"
3. Now try to remove it from the taskbar again.
4. Right clicking brings up menu but "remove ..." is missing

**Expected behaviour**
I want to somehow remove added programs from taskbar

**Screenshots**

**Additional context**
Added Firefox too. Same problem. But Thunderbird works as expected.

**Comment by feren** [comment]
You're meant to **Pin to Task Manager** for that, not Add To Panel (Widget). Right-click the panel, Edit Panel and remove them while in Panel Edit Mode and then try pinning them using the correct menu option afterwards. Alternatively drag it from the menu onto the 'Icons-only Task Manager' (windows list) and release to pin the application to your Task Manager.

**Comment by feren** [comment]
Don't ask me why KDE Plasma (the standard Feren OS Desktop Environment) still provides an option to add it to the panel as an icon Plasmoid - not that sure myself to be honest.

**Comment by feren** [comment]
Tip: For Cupertino and Ubuntu Unity Layouts you'll have to open them first and pin them while opened and/or drag them from File System/usr/share/applications in a Files window to the dock of both layouts.

**Comment by Rubenzahl** [comment]
Thanks a lot. That did the trick!
