### ISSUE TITLE
Delete does not always function

### ISSUE THREAD

**Issue by ghost** [feren-OS/Bug-Reporting-Center#125]
In the files app:
When trying to delete a dir containing dirs + pictures - Im told it is not possible to delete a dir, while it is not empty ??  When trying to delete files in that dir, it seems to go OK - but when going one dir up, and then trying to delete that dir, the same error comes - and upon browsing that dir, the files are STILL there...
![image](https://user-images.githubusercontent.com/61122679/74611415-ed82b100-50fb-11ea-907d-8358a7a3bfae.png)
The dir resides on network at a NAS.

**Comment by feren** [comment]
That sounds like a Nemo Bug, so I'd probably try reporting it at https://github.com/linuxmint/nemo/issues to see if they have any idea why it's happening, since it's their own code.

**Comment by Clausdittrich** [comment]
Hi - im quite new to Linux - but I did get the hint of the Nemo bug - so I tried Dolphin - and huraaa it works. And this file manager is IMO quite beautiful and easy to use - BUT I cant get it to remember the password for my NAS. The password dialogue doesnt present the option of remembering, like Nemo did ?? How can Dolphin remember passwords from SMB shares ??
![image](https://user-images.githubusercontent.com/61122679/75189059-b04a9e80-574d-11ea-8452-b5594287a6db.png)

**Comment by feren** [comment]
For Samba Shares, there is a setting in System Settings -> System -> Advanced Options -> Windows Shares to supply default credentials to log into shares with (if it's not the one in System it's the one in Personalisation). Apart from that, I'm not sure.

**Comment by Clausdittrich** [comment]
Thanx !!! You are fantastic - it works.
I am super delighted - have checked all functions I used to use in Windows - and Feren can do it too, it seems. I am really happy to be quit of Windows.
I have been looking for a replacement to Windows, have tried LM, Zorin and now Feren - the other 2 were slow and had several problems (IMO as I am used to Windows) - but not Feren, apart from this issue with File manager - Must admit I like Dolphin a lot better that Nemo - as dolphin can delete/move files and folders on NAS. That Nemo can not. And the GUI of Dolphin is much nicer looking.
So I a am happy now - will ofcoarse test more, but so far so very good..
As a lot of windows users are tired of the OS, have u thought about promoting Feren OS ?
Im quite sure that it is almost as freindly to Windows users as it can be (apart from more clear documentation + some small issues)
I also think that u actually could earn some money on every installation - with a freemium model, with a paid upgrade of some sort.
Regards Claus, Denmark

**Comment by feren** [comment]
To be honest, I kind of want to get more of a backing behind the OS first before I explore seriously advertising it to Windows users.

**Comment by Clausdittrich** [comment]
OK thanx for you answer - maybe the advertising will come later - in a
Windows world, moving to the Linux world is not easy, but Feren has solved
the most part of those adapting problems a Windows user has...
So kudos to your work.
Nice weekend

*Venlig hilsen / Kind regards / Mit freundlichen Grüßen*

*| 2982-2799 | Claus Dittrich | Tresman |*





Den tor. 27. feb. 2020 kl. 15.01 skrev The feren OS Dev <
notifications@github.com>:

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?

**Comment by dominichayesferen** [comment]
Oh. It's a ghost, so they can't respond... welp.
