### ISSUE TITLE
Default for keyboard is Numlock on still!!

### ISSUE THREAD

**Issue by nikbex-sno** [feren-OS/Bug-Reporting-Center#130]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nikbex-sno** [comment]
Missed the text entry bit, sorry.
Install iso has numlock turned on still even tho it detects the machine as a laptop numlock is not turned off!!
Having dug out my old usb keyboard and turned numlock off,
 fine during install but on rebooting the installed OS, the numlock is back on!!!!
All input from laptop keyboard is numeric only.....
PLEASE FIX THIS AS IT WAS ALSO IN THE JANUARY ISO!

**Comment by feren** [comment]
You can turn off Numlock, for the Login Screen at least, through Login Window.

**Comment by nikbex-sno** [comment]
Thanks, I’ll try that. 
Have remote installs to do!!
Nick

**Comment by nikbex-sno** [comment]
Hi there, tried your suggestion….no effect, still had to use usb keyboard on laptop!!
Used to work ok in the previous version tho’
Regards
Nick

**Comment by nikbex-sno** [comment]
The required setup now!

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?

**Comment by nikbex-sno** [comment]
Downloading now for test, been busy on Big Sur!!

**Comment by nikbex-sno** [comment]
Hi Dominic,

Just loaded and tried on same laptop, NO PROBLEMS AT ALL!!

Thanks for your patience and reply.

Nick
