### ISSUE TITLE
Broken install in updator after first install of FerenOS

### ISSUE THREAD

**Issue by wulfalpha** [feren-OS/Bug-Reporting-Center#132]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
Update Manager
**Describe the bug**
After install from latest ISO the first time the system updates it fails and advises to try sudo apt --fix-broken install this removes
**Steps to Reproduce**
1. Install from Iso
2. Update via Update manager (second time I flashed the OS the update manager actually froze and I had to run sudo apt update && sudo apt upgrade before it showed me the error)
3. Performe the fix: sudo apt --fix-broken install and system will update as normal.

**Expected behavior**
Updater should remove and add packages as needeed without errors/should be a button to run fix-broken install in the updator.
**Screenshots**

**Additional context**
To be fair this happend inside A VM which is why im not surprized. Just passing along the issue and the fix.
Have a good day!

**Comment by feren** [comment]
This has already been fixed in April 2020 Snapshot, which is hopefully going to release tomorrow.

**Comment by wulfalpha** [comment]
Awesome! Thanks for the quick response!

**Comment by feren** [comment]
Fixed in Feren OS April 2020 Snapshot.
