### ISSUE TITLE
Cannot Complete Feren OS Update 28 Broken Packages

### ISSUE THREAD

**Issue by joshontech** [feren-OS/Bug-Reporting-Center#133]
**Package Name or Section of Feren OS where this bug resides**
Feren OS updater
 
**Describe the bug**
After trying to update Feren OS after install it downloads all the updates and than tries to install them. The update installer gets about 15% done and than crashes and tells me I have 28 packages that need to be repaired. To fix the broken packages I did a sudo apt install -f to fix dependencies and than the update continues as usual. But this has happened on me with 2 different computers.

**Steps to Reproduce**
1. Install Feren OS
2. Update feren from the update manager
3. Get the 28 packages broken error

**Expected behavior**
Update Feren and reboot with no issues

**Screenshots**

**Additional context**

**Comment by feren** [comment]
#132

**Comment by joshontech** [comment]
@feren was this issue resolved in the newest snapshot?

**Comment by feren** [comment]
Yes
