### ISSUE TITLE
CANNOT read from hd1

### ISSUE THREAD

**Issue by RomanianBeret** [feren-OS/Bug-Reporting-Center#134]
**Package Name or Section of Feren OS where this bug resides**
i think grub2 i dont know. Feren OS 2020 April Snapshot

**Describe the bug**
it gives me error on boot cant read from hd1

**Steps to Reproduce**
enter in the live cd grub English (UK)
I know it dosent make any sence

**Expected behavior**
i expected for feren os to load and then for me to lauch the installer and install my favourite os

**Screenshots**
i cant tke screenshots

**Additional context**
please anyone help me

**Comment by RomanianBeret** [comment]
please i really really love the desktop please help me feren is important please i whould appreciate to anyone.

**Comment by feren** [comment]
That sounds like an issue with how you flashed Feren OS onto your USB.

Check the Feren OS User Guide for instructions on flashing Feren OS to a USB Drive or a DVD.

**Comment by RomanianBeret** [comment]
Ok So @feren What Are The differences From CdBurnerXP And Windows'es cd burner? and if you can reproduce it i whould then get a dvd cause i dont wanna lose one again... rewriteable dvds? no only cd's so please tell me how i should actually make it and lemme know if you are able to reproduce this bug or i dont know so please please if u can tell me differences and if its reproduceable. Thanks.

**Comment by RomanianBeret** [comment]
oh and id like having it so so much.

**Comment by feren** [comment]
> What Are The differences From CdBurnerXP And Windows'es cd burner?

I don't know since I don't make them.

I can't really reproduce it, currently, because my computer lacks a disc slot. If you can, use a USB instead - USBs have unlimited rewrites.

**Comment by RomanianBeret** [comment]
Well after making loads and loads of bios and configurations for USB to install. I think that ther is something that's not working. Usbs give me like can't get uefi dB list - fixed but then error - 110 which is an power thing. And an very old windows USB with the first major update. And my question is:do you know how to help me make the USB and configure bios? Or anything just please please please I don't wanna waste any more DVDs and if you ask for rewritable I can't find any.i opened account to report it. I wanna really really really try feren os. So please help get up my dream of having FEREN OS on my laptop... I really really want Feren Os

**Comment by RomanianBeret** [comment]
No it's impossible for me to install from USB.

**Comment by RomanianBeret** [comment]
Not to BOOT JUST INSTALL

**Comment by feren** [comment]
https://feren-os-user-guide.readthedocs.io/en/latest/writetousb.html

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
