### ISSUE TITLE
'Send Feedback' desktop icon disappears on changing theme

### ISSUE THREAD

**Issue by ferenbreath** [feren-OS/Bug-Reporting-Center#135]
When Global Theme is changed to Breeze, the desktop shortcut icon for 'Send Feedback or Report an Issue' disappears. Text and action still remains.

**Comment by feren** [comment]
That is because Breeze appears to be lacking the `distributor-logo` icon. You should probably report that to https://bugs.kde.org/ as a Breeze Icon Set bug under KDE neon.
