### ISSUE TITLE
[Task] Feren OS on 20.04 (post-release)

### ISSUE THREAD

**Issue by dominichayesferen** [feren-OS/Bug-Reporting-Center#136]
This isn't a bug report, but rather a task to be done in Feren OS, which needs to consist of 1 or more issues anyway on GitHub to be addable to a 'Project' or 'Milestone', hence I'm making this 'issue' to track progress and to-do for Feren OS on 20.04.

- [x] Try and force an upgrade of base on Feren OS to Ubuntu 20.04 to see how broken it is Feren OS utilities-wise (on my own side, not for anyone else)
- [x] Fix utilities that are broken in Ubuntu 20.04 (*cough* MintSources *cough cough*)
- [x] Prepare the new GTK theme for GTK 3.24 (currently working on the GTK 3.22 version - shouldn't be too broken in GTK 3.24 so I might be able to initially get away with temporarily using the GTK 3.22 counterpart in 20.04 until the GTK 3.24 counterpart's ready in which case it'll immediately be updated to use the GTK 3.24 counterpart of the new theme)
- [x] Take ownership of all the stuff needed from the Linux Mint repositories
- [x] Get rid of the Linux Mint repository by default in 20.04-based Feren OS
- [x] Get rid of all the packages in the 20.04 Feren OS repositories that were for Feren OS Classic
- [x] Replace feren-maintenance with a fork of MintReport (both Feren OS on 18.04 and 20.04)
- [x] Re-do Major Update tool from scratch to make it simpler to maintain and more consistent code-wise
- [x] Add 32-Bit blocking support to Major Updater's rewrite
- [x] Add extra screen in Major Updater for Feren OS Classic users to let them either upgrade to Feren OS or to Linux Mint 20 (or instead just don't do the major update at all)
- [x] Make use of the SystemD Service work from oem-config-feren to allow for better resuming the Major Update process if the computer restarts during a Major Update, and to also make the Major Updater actually restart at the end
- [x] Adjust 16.04 -> 18.04 update path around all the changes made to Feren OS on 18.04 to restore the update path
- [ ] (unrelated) Actually remember to give the remaining Git-repository-less packages in Feren OS's repositories Git Repositories so Arch packagers, etc can finally do their magic to add Feren OS stuff to the AUR if they want, and overall just give others an easier way to see the packages.
- [x] Fix Feren Store in 20.04
- [x] Fix Nemo and Feren Store and so on package removals in 18.04 -> 20.04 major update
- [x] ~~Find out what filesystem changes were made in-between 18.04 -> 20.04 to initiate them on the update process~~

**Comment by LinuxReporter** [comment]
sounds good

**Comment by dominichayesferen** [comment]
This is essentially done, but the post-release stuff still needs to be done currently.
