### ISSUE TITLE
Manual Partitioning Does Not Set Boot Flag

### ISSUE THREAD

**Issue by joshontech** [feren-OS/Bug-Reporting-Center#137]
**Package Name or Section of Feren OS where this bug resides**
Calimares installer when manual partitioning.

**Describe the bug**
After making a fat32 partition for /boot/efi and setting the boot flag calimares complains the boot flag is not set. 

**Steps to Reproduce**
1. Start manual partitioning
2. Make a fat32 partition mount it at /boot/efi and set boot flag
3. Exit manual partitioning and try to install.
4. On exiting calemares complains about no boot flag for /boot/efi

**Expected behavior**
Creat /boot/efi and set boot flag without the error message.

**Screenshots**

**Additional context**
The install works just fine after skipping the dialog that the flag was not set. Any additional info please ask.

**Comment by RomanianBeret** [comment]
Maybe try to set the ESP flag with gparted as the manual partition its more for setting the mount systems

**Comment by feren** [comment]
Are you using the latest Feren OS ISO? It has a workaround nowadays in the post-install script ran during the installation process to add a boot flag.

**Comment by feren** [comment]
Also the upstream bug report is https://github.com/calamares/calamares/issues/1175 so this is fixed upstream, pending Calamares's latest version being added to the Feren OS repositories.

**Comment by dominichayesferen** [comment]
Pretty sure this is fixed upstream by now in November 2020 Snapshot.
