### ISSUE TITLE
Can't install Feren - Wireless mouse not working

### ISSUE THREAD

**Issue by Truman-Burbank** [feren-OS/Bug-Reporting-Center#140]
My mouse pad doesn't work, so am using a Logitech wireless mouse. I tried navigating by using tab/arrow keys, but that didn't work well either. Thought I could get my wireless internet going, so that I could install the driver, but was not successful. Too bad - it looks like such an awesome distro. I'm sure that I could get around this by using the`terminal', but don't have the expertise. My laptop is an old Toshiba Qosmio. Thanks.

**Comment by feren** [comment]
By wireless, does that mean USB-plug-in-receiver or Bluetooth?

Also what exact laptop model is it, if you happen to know the name of it?

**Comment by Truman-Burbank** [comment]
Thank you for the fast response.
Yes, a USB-plug-in. My mouse is a logitech M510.
My laptop is a Toshiba Qosmio X75-A7290. 32GB ram.
The mouse works fine with Linux Mint 19.3, and previous versions.
Current kernel is 5.3.0-51-generic, but have been using Mint with this
mouse a year with no problem. Also am using a wireless Logitech keyboard.

**Comment by feren** [comment]
Could you possibly try installing Feren OS, and then installing `Xserver-xorg-input-all-hwe-18.04` from the Store onto the Feren OS install, followed by rebooting to see if it starts working once more?

**Comment by Truman-Burbank** [comment]
I had trouble installing Feren since I don't have a mouse. I was able to
get my laptop to use the number pad to move the cursor around, but when
installing, Feren gave me a format error. My computer wouldn't boot after
that, so had to reinstall Mint. I tried to install
Xserver-xorg-input-all-hwe-18.04
from a flash drive before installing, but looks like that doesn't work
(virtual drive maybe?).

**Comment by feren** [comment]
Try following this guide when reinstalling Feren OS:
https://feren-os-user-guide.readthedocs.io/en/latest/installoverlinux.html

**Comment by dominichayesferen** [comment]
Does this issue still occur in Feren OS November 2020 Snapshot?

**Comment by Truman-Burbank** [comment]
Sorry, but I'm using a different operating system now.
Thanks
