### ISSUE TITLE
Feren not waking from standby

### ISSUE THREAD

**Issue by pete051** [feren-OS/Bug-Reporting-Center#142]
I find that feren refuses to wake from standby, pressing a key or clicking the mouse only results in the "No signal" warning flashing. The only ways out I have found are alt ctl F2 then reboot from the terminal or the reset button. this is a Ryzen 3200G on an Asrock B450 pro

**Comment by feren** [comment]
Weird... it definitely seems to work for me, but there again Linux suspending has always been touchy. I'll mark it as "Can't Reproduce" for now since I don't have Ryzen hardware.

**Comment by pete051** [comment]
Update rather than rebooting from the command line I tried startx but this gave me a cursor on an otherwise blank screen from which the only escape was the reset button

**Comment by feren** [comment]
What about CTRL+ALT+F2 and then CTRL+ALT+F7?

**Comment by pete051** [comment]
Yes that worked, I'm booting from an nvme drive wonder is that's causing the effect

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
