### ISSUE TITLE
feren-maintenance - ferensources missing

### ISSUE THREAD

**Issue by holzboa** [feren-OS/Bug-Reporting-Center#144]
**Package Name or Section of Feren OS where this bug resides**
feren-maintenance

**Describe the bug**
when running /usr/bin/feren-maintenance i end up with an error:
dpkg-query: no packages found matching ferensources

**Steps to Reproduce**
1. run /usr/bin/feren-maintenance in a terminal or start it from application menu

**Expected behavior**
Not sure as i never got another output but when i look at the script i guess output should be different.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59257180/82142047-e0c84300-9839-11ea-9011-c748acf99a8c.png)

**Additional context**
there is a existing folder /usr/share/ferensources/ with subfolders /bionic including ferensources.conf, official-dbgsym-repositories.list, official-package-repositories.list, official-source-repositories.list and sources.list.

**Comment by feren** [comment]
That's just one of the checks being verbose, as such it's not a bug or an issue of any sort either, so don't worry about it. It's planned to be completely replaced by a new MintReport fork, soon, anyway.
