### ISSUE TITLE
Software Sources - Linux Mint mirror back to default

### ISSUE THREAD

**Issue by holzboa** [feren-OS/Bug-Reporting-Center#145]
**Package Name or Section of Feren OS where this bug resides**
ferensources

**Describe the bug**
I can change the ubuntu mirror to a local mirror but switching the Linux Mint mirror doesn't work. When opening up ferensources again, Linux Mint mirror is back to the american mirror

**Steps to Reproduce**
1. 

**Expected behavior**
Linux Mint mirror change should be permanent 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59257180/82142513-25a1a900-983d-11ea-8729-19188a44a4bc.png)

**Additional context**

**Comment by feren** [comment]
Something appears to be wrong with your Software Sources as the tabs at the top are not in your screenshot.

**Comment by holzboa** [comment]
Honestly I can't remember if there were tabs after fresh install. Do you mean a ppa tab?
ppa's show up in synaptic
In synaptic I tried to reinstall ferensources-ubuntu but I only got: 
404  Not Found [IP: 172.65.251.78 443]

Then after 
# apt update && apt full-upgrade

i hopped from 
ferensources-ubuntu  (2020.01.0.0.0) to (2020.05.0.0.0)

but that didn't solve the problem.

**Comment by feren** [comment]
Yeah, there are tabs.
NOTE: Screenshot depicts Software Sources in 20.04-based Feren OS, which is not released, hence why there are missing buttons in this depiction compared to your Software Sources

![image](https://user-images.githubusercontent.com/11057934/82268848-df953400-9967-11ea-9e93-df9334339af0.png)

**Comment by holzboa** [comment]
Wow, a slight difference. 
I wonder how I managed to change that. Guess I'll wait for your new version as everything works here.
