### ISSUE TITLE
open-vm-tools fails to install from welcome screen in live session

### ISSUE THREAD

**Issue by dalto8** [feren-OS/Bug-Reporting-Center#147]
**Package Name or Section of Feren OS where this bug resides**
open-vm-tools fails to install from welcome screen in live session

**Describe the bug**
When launching the live iso from within vmware you are presented with a screen which offers to install open-vm-tools.  It claims it is installing but doesn't.

It works fine post-installation.

**Steps to Reproduce**
1. Boot the live ISO in a VM
1. Click the button on the welcome screen to install open-vm-tools

**Expected behavior**
It should install when the button is clicked

**Comment by feren** [comment]
I'll look into this in the future... been a bit busy right now.

**Comment by dominichayesferen** [comment]
Should be fixed in Feren OS November 2020 Snapshot.
