### ISSUE TITLE
GIMP 2.10.8 reinstalled after removing - it is unstable

### ISSUE THREAD

**Issue by swarfendor437** [feren-OS/Bug-Reporting-Center#148]
Currently using the latest version with no issues (2.10.20) but today it installed the flatpak version again of 2.10.8. This needs to be ditched as it crashes an awful lot.
It's a repo bug rather than a FerenOS 2020.04 bug.
![Old version of GIMP that needs removing](https://user-images.githubusercontent.com/43353665/84369735-3391e200-abcf-11ea-952e-38487d60d083.jpg)

**Comment by feren** [comment]
GIMP is at 2.10.20 on its Flatpak counterpart.
