### ISSUE TITLE
Laptop "Sleep" function not working with lid closure

### ISSUE THREAD

**Issue by bearknifefight** [feren-OS/Bug-Reporting-Center#151]
Operating System: Feren OS 2020.07
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.14.2
Kernel Version: 5.4.0-42-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6200U CPU @ 2.30GHz
Memory: 7.4 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 520
Dell XPS 13 9350

When I close the lid, the computer now shuts down instead of sleeping, even when "sleep" is selected in the power management menu. All other power management options ("do nothing", "lock screen") appear to work correctly. 

Laptop has been updated recently and has been behaving normally otherwise.

**Comment by feren** [comment]
Does normal Sleep work?

**Comment by bearknifefight** [comment]
Yep. 

Weirdly enough, it seems to be working again as normal now after a few power cycles. I'll keep an eye on it...but I suppose we can mark this as closed? If I can find a consistent trigger for the issue, I'll update the thread.

Thanks for the quick response.
