### ISSUE TITLE
Thinkpad X240 Laptop Onboard Camera not recognised/working

### ISSUE THREAD

**Issue by Prajac** [feren-OS/Bug-Reporting-Center#152]
I have just tried using Zoom and Cheese and the laptop camera is not there. I have tried pressing the function buttons and nothing happens.
I am using a thinkpad X240 laptop which has a 0.9-MP, 720p front-facing camera with face-tracking technology

I have plugged in another webcam through the usb and this works. Only the onboard/integrated camera is not working
 Can anyone help?

**Comment by dominichayesferen** [comment]
Does this still occur on Feren OS November 2020 Snapshot?

**Comment by Prajac** [comment]
I shall test it and let you know. I kind of gave up on Linux and went back
to Windows. I shall reinstall feren and get back to you.

KR
Chandra
