### ISSUE TITLE
"Software Sources" Mint Repository mirror label always says default mirror on startup despite currently being on a different mirror

### ISSUE THREAD

**Issue by kagirohi** [feren-OS/Bug-Reporting-Center#153]
I use FerenOS in Japan.
I set up a mirror server of Linux Mint(tricia) near Japan(e.g.:http://ftp.jaist.ac.jp).
### **Change Mirror server**
![Screenshot_20200802_153325](https://user-images.githubusercontent.com/57948679/89117384-54442d00-d4d8-11ea-840c-4db212d6d3f3.png)

But restarting this application,Linux mint (tricia) mirror server settings are back to default.
(http://packages.linuxmint.com)
![image](https://user-images.githubusercontent.com/57948679/89117589-ea2c8780-d4d9-11ea-84c6-a041d20da5e3.png)

When I checked the configuration file, the change of the mirror server was completed successfully.
(/etc/apt/sources.list.d/official-package-repositpries)
![Screenshot_20200802_154951](https://user-images.githubusercontent.com/57948679/89117360-1810cc80-d4d8-11ea-92f3-3460e004a409.png)

What is happening.

**Comment by dominichayesferen** [comment]
Technically fixed in Feren OS November 2020 Snapshot, given that the Mint repository is no longer there in it and onwards...?

**Comment by kagirohi** [comment]
Thank you.
