### ISSUE TITLE
No Desktop after installation

### ISSUE THREAD

**Issue by weasel84** [feren-OS/Bug-Reporting-Center#154]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
Feren OS July 2020 Snapshot 

**Describe the bug**
Hello. I'm pretty new in the Linux world and I'm currently looking which distro fits me best. After successfully testing the Live system I installed Feren OS but unfortunately, after the installation only the background image appears but no taskbars and menues. I'm able to open programs like the file browser, the terminal window, the update manager or the driver manager via the right cklick menu on the desktop. As shown in the screenshots below I received the following error message after I stopped and restart the plasma desktop over the terminal window. Also the system hangs during the shutdown process.

I hope this is just a samll issues wich can be fixed easely by entering some commands in the terminal :)

**Screenshots**
![Screenshot_20200802_225647](https://user-images.githubusercontent.com/69201883/89297527-4f13e900-d664-11ea-9772-718b19c439c8.png)
![20200802_232325](https://user-images.githubusercontent.com/69201883/89297545-589d5100-d664-11ea-9fce-f74b395e55d2.jpg)

If yo nedd any further screenshots and / or logfiles, please let me know.

**Comment by feren** [comment]
Did you choose a different layout in the Welcome Screen?

**Comment by weasel84** [comment]
I tried all layouts but unfortunately, the situation remains the same at every layout.

**Comment by feren** [comment]
So, wait, was it a fresh Feren OS installation?

**Comment by weasel84** [comment]
Yes, it is a fresh is installation

**Comment by feren** [comment]
Can't reproduce it here, so I'll just mark as non-producable for now.

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
