### ISSUE TITLE
Screen goes black 

### ISSUE THREAD

**Issue by ronin117-prog** [feren-OS/Bug-Reporting-Center#155]
After fresh Os installation, at first boot when I try to connect to my wifi, the screen goes black, just after when I click the connect button. Also the KDE plasma dialog window asks for the wifi password twice which is kind of annoying. Pls fix this bug.

**Comment by feren** [comment]
Picture?

**Comment by ronin117-prog** [comment]
It occurs just after I press connect as shown in the picture if the wifi password isn't saved. After connecting once no such black screen is observed till now. 
![BUG](https://user-images.githubusercontent.com/68694355/89651194-2cdacf00-d8e1-11ea-8b08-8f88c98519b7.png)

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?

**Comment by ronin117-prog** [comment]
No, it only occurred a few times after fresh installation later it never happened.
Current OS version:  Feren OS 2020.07
