### ISSUE TITLE
Feren Widget Calendar unable to link to online account or gnome calendar

### ISSUE THREAD

**Issue by AbnormalBehavior** [feren-OS/Bug-Reporting-Center#160]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) Feren Calandar widget

**Describe the bug**
Does not sync with online calendar nor gnome calandar.
**Steps to Reproduce**
1. 

**Expected behavior**
only shows USA hollidays
**Screenshots**
![Screenshot_20200816_171627](https://user-images.githubusercontent.com/68035234/90344099-6b107680-dfe4-11ea-8149-051aadb5b689.png)
**Additional context**
Love the calendar, wish it worked.

**Comment by feren** [comment]
Unfortunately it's very unlikely that GNOME Calendar will ever get integrated into a KDE Plasma widget, and I have no plans to do so. That being said, you can configure Holidays in the widget's settings.
