### ISSUE TITLE
Bugy Youtube

### ISSUE THREAD

**Issue by kachilda1** [feren-OS/Bug-Reporting-Center#161]
**Package Name or Section of Feren OS where this bug resides** Youtube,
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___ In both Vivaldi and Chrome browsers.

**Describe the bug**
A clear and concise description of what the bug is. When watching a how to video in Youtube I set Youtube video to full screen, watch some of it minamize the video and then the browser and come back 10 or 15 minutes later to enlarge the video and all I can do is either start or stop the video all other youtube functions seem to be disabled. The fix seems to be to either close and reopen the browser or grab the top of the browser at the top of the panel and shake it around a little then I can go back to watching the video. Not a major issue but for me to live in it it has to be as good are better then Windows 10. Your very close.

**Steps to Reproduce**
Steps to reproduce the behaviour: Watch a Youtube video in full screen then mnamize the video then minamize the browser. Wait for 10 or 20 minutes and try to reverse the process.
1. 

**Expected behavior**
A clear and concise description of what you expected to happen. I expected to go back into my browser enlarge my youtube video back to full screen and continue watching where I left off.

**Screenshots**

**Additional context**
Add any other context about the problem here. My computer has 16 gig of ram and amd's eqivalent of an i5 dual core so I'm I'm certain it's not my computer but who knows. Thanks.

**Comment by feren** [comment]
Is this still happening?
