### ISSUE TITLE
Desktop effects were restarted due to a graphics reset 

### ISSUE THREAD

**Issue by RomanchJR** [feren-OS/Bug-Reporting-Center#162]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by feren** [comment]
That is too obscure a bug report to be able to ever be a helpful bug report. You can pretty much trigger this by any means, such as maybe being in a TTY or other user while the Plasma Desktop is loading, and other things.

As such, this is gonna be marked as Invalid or Closed for the time being. Go into System Settings -> First 'Advanced Settings' option -> Compositor, check the tick for using the compositor, and choose another version of OpenGL for the Compositing Backend, followed by Apply to bring back the Compositor.
