### ISSUE TITLE
steam doesn't open

### ISSUE THREAD

**Issue by RomanchJR** [feren-OS/Bug-Reporting-Center#163]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**
- while opening steam, it shows updating, but when update complete, it doesn't open. tried alot but can't.

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**
![Screenshot_20200901_190818](https://user-images.githubusercontent.com/58005198/91856831-cbf7aa00-ec86-11ea-8eff-3774683f69f8.png)

**Additional context**

**Comment by dominichayesferen** [comment]
Does this occur in Feren OS November 2020 Snapshot?
