### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by pontifex22** [feren-OS/Bug-Reporting-Center#165]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
Feren Calendar

**Describe the bug**
It is not possible to link my google calendar with the feren os calender. The tub for connection to Google Nextcloud or MS Exchange are not active and the Button for preferences of online accounts doesn't work either (see attach)

**Steps to Reproduce**

**Expected behavior**
Expect to connect my feren os calendar to my google calendar

**Screenshots**

**Additional context**

Thanx in advance, Oliver
![Screenshot_20200907_115836](https://user-images.githubusercontent.com/70888155/92375659-b6103c00-f101-11ea-965c-5e77d6d6a407.png)

**Comment by feren** [comment]
#90
