### ISSUE TITLE
Google Chrome cannot be set as default browser

### ISSUE THREAD

**Issue by jallain9** [feren-OS/Bug-Reporting-Center#166]
I have configured Chrome to be the default in the application settings. When I launch Chrome it asks if I want it to be the default. I tell it yes but the next time I launch Chrome it asks the same thing. Verified in settings that it is still the default.

**Comment by feren** [comment]
You can make Google Chrome the default in System Settings -> Applications. Any bugs with Chrome asking you to set itself as the default browser but it not actually doing it should be reported to Google themselves.

**Comment by jallain9** [comment]
I did set Chrome as default in the settings but it did not work. I'm sorry
if I did not make that clear; however I can set Chrome as default just fine
on 20.04 Beta 1.
