### ISSUE TITLE
Remove the space from the name of the ISO

### ISSUE THREAD

**Issue by Silejonu** [feren-OS/Bug-Reporting-Center#168]
I realise this is extremely minor, but this is a little annoyance in some situations, and on the other hand, I can't see any pros to have a space in the name.
For instance, ISOs with spaces in their names are not recognised in Ventoy and Feren OS is the only outlier amongst the dozens of distros I store on my Ventoy flash drive. I can just rename it and it's fine, but as it's the exception, not the norm, I often forget to do it and I imagine I'm not the only one.

**Comment by feren** [comment]
Might consider it in the next snapshot, so I'll keep this open for now. The reason it has had a space is to make the file names easier to read when viewing it in SourceForge's browser.

**Comment by Silejonu** [comment]
Thanks for considering it!
Also, it would be nice to have the date of the snapshot in the file-name (or any other way to distinguish between versions). It would help people know whether they still have the newest version or need to download the new snapshot.
Maybe something like that: Feren_OS_20201009.iso

**Comment by feren** [comment]
not really possible because renaming ISOs resets the statistics for downloads... plus the general file dates on SourceForge kinda say it all.

**Comment by dominichayesferen** [comment]
Alright, renamed it in November Snapshot.
