### ISSUE TITLE
Unable to install (32 bit - installer will not start)

### ISSUE THREAD

**Issue by s-m-e-e-again** [feren-OS/Bug-Reporting-Center#177]
**Package Name or Section of Feren OS where this bug resides**
feren-os-installer (feren os classic 32bit 2020)

**Describe the bug**
Installer will not start, it just closes welcome screen and nothing happens.
Running feren-os-installer in terminal ends with the message "no installers found".

**Steps to Reproduce**
1. Live boot from USB (made with Disks - Image Writer)
2. Open Welcome app from desktop or menu
3. Click "Install" (the welcome screen is closing but no installer)

**Expected behavior**
Installer should start and prompt for installation options.

**Additional context**
Tried multiple sticks on two different systems (always the 32 bit iso)
ISO was downloaded twice and verified (sha256sum).

**Comment by dominichayesferen** [comment]
Is there an "Install Feren OS" shortcut on the Desktop? If so, try that.

**Comment by s-m-e-e-again** [comment]
No, there isn't one. I thought there wasn't supposed to?

**Comment by dominichayesferen** [comment]
...
very odd. Guess I'll have to investigate what is going on.

**Comment by jules5238** [comment]
Same issue today installer will not start, tried multiple iso downloads sums are good.

**Comment by dominichayesferen** [comment]
Haven't had time to investigate this issue, apologies.

**Comment by dominichayesferen** [comment]
Alright, managed to FINALLY investigate this - yep, I messed up.

Fixed this in the new Feren OS Classic ISO updates.
