### ISSUE TITLE
URL in Welcome Screen is leading to a 404

### ISSUE THREAD

**Issue by medvardsen** [feren-OS/Bug-Reporting-Center#179]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? Welcome Screen /Recommendations > Office

**Describe the bug**
URL on the button for downloading WPS Office leads to a 404 (linux.wps.com/downloads)
**Steps to Reproduce**
1. Open Welcome Screen
2. Recommendations
3.Scroll down to the Office section and try to download WPS office by clicking the button

**Expected behavior**
The URL should be: https://linux.wps.com/

**Screenshots**
**Screenshot of Section is attached:**
![wps_section](https://user-images.githubusercontent.com/875864/101092269-aba6f680-35b9-11eb-8aeb-895f25f214d8.png)

**Welcome Screen Version Screenshot is attached:**
![version](https://user-images.githubusercontent.com/875864/101092247-a2b62500-35b9-11eb-995d-2e6abd69de2e.png)

**Additional context**
-

**Comment by dominichayesferen** [comment]
Fixed in feren-welcome 2019.12.0.X.X
