### ISSUE TITLE
Issue downloading repository indexes after installing updates on November snapshot installation

### ISSUE THREAD

**Issue by jmanaya** [feren-OS/Bug-Reporting-Center#181]
**Package Name or Section of Feren OS where this bug resides**
Update Manager

**Describe the bug**
Could not download all repository indexes after installing updates for the first time on a new installation of the November snapshot.

**Steps to Reproduce**
1. Download the November snapshot and install it.
2. After installation reload for the first time, click Install Updates in Update Manager. 
3. An error occurs while installing a plasma-workspace package having to do with a look and feel patch (I forget the exact name). 
4. I answered yes to use the new configuration files each time I was prompted.
5. After everything else has installed a reboot is required, I reboot the system. 
6. There is still one update available (the plasma-workspace package that had failed).
7. Before installing the update I click refresh and receive an error about the repositories:

> Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'Failed to fetch https://gitlab.com/feren-os/feren-repositories-neon-focal/raw/master/dists/stable/InRelease  Temporary failure resolving 'gitlab.com'Failed to fetch https://gitlab.com/feren-os/feren-repositories-focal/raw/master/dists/stable/InRelease  Temporary failure resolving 'gitlab.com'Failed to fetch http://repo.vivaldi.com/stable/deb/dists/stable/InRelease  Temporary failure resolving 'repo.vivaldi.com'Some index files failed to download. They have been ignored, or old ones used instead.

**Expected behavior**

I expected that all repository information would be updated and no error message displayed.

**Screenshots**

![update_manager_screenshot](https://user-images.githubusercontent.com/52865490/101959044-6e45f880-3bb9-11eb-9288-982fba3e665d.png)

**Additional context**

I have had the same results on a desktop and laptop on which I installed the November snapshot.

**Comment by dominichayesferen** [comment]
Sounds like you're not connected to the internet. Try connecting to the internet again via the WiFi tray item.

**Comment by jmanaya** [comment]
I'm connected to the internet. I've had the same issue on two desktops and a laptop. I've been able to install packages and everything, but at some point after applying the first set of updates after the initial installation I start getting those error messages. As far as I can tell I only get that message on the sources listed above.

**Comment by dominichayesferen** [comment]
Oh, could those repositories have potentially been down for you by chance then? That or ISP blocking is the only reasons I can think of for ONLY those repositories being the ones it can't connect to, unless your internet sucks or you disabled some repositories manually.

**Comment by jmanaya** [comment]
Yeah, it's really weird because it all worked fine until I installed updates. I tried installing Kubuntu instead and I haven't had the same issues so I don't think it's my ISP. I think it has something to do with the resolvconf package and/or systemd but unfortunately I don't know much about either to say how. While searching for solutions I found that in Kubuntu there's an entry for 'options edns0' in /etc/resolv.conf that wasn't there in Feren OS and the resolvconf package wasn't installed on Kubuntu. I looked it up and there were some bugs related to DNS resolution in previous versions of Ubuntu but I don't know enough about networking to say whether that's what is causing it.

**Comment by clecky69** [comment]
i have the same problem, i cannot download anything from the store or via command line from Gitlab. this problem only arose when i re-installed Feren, previously i had no problems whatsoever. my internet connection is fine and i have no problems with 2 other installed OS's.
pleqase help?

**Comment by clecky69** [comment]
re-formatted, installed Feren classic 2018. all went tickety boo until i tried to update to the current Feren OS. thats when it all went a bit pants - failed to update 4 times so i gave up. i believe the problem is firmly with Gitlab.

**Comment by dominichayesferen** [comment]
https://medium.com/feren-os/the-repository-keyring-expired-heres-how-to-renew-it-bd50dd874aac for the newest one

Though, I'll mark this as "Close if No Response" unless the original issue this issue was made for still occurs.
