### ISSUE TITLE
Installer does nothing

### ISSUE THREAD

**Issue by asteriogonzalez** [feren-OS/Bug-Reporting-Center#183]
**Package Name or Section of Feren OS where this bug resides**
Feren OS Nov-2020 Snapshot

**Describe the bug**
Click on installer does nothing

**Steps to Reproduce**
1. VirtualBox fresh machine with installer iso attached.
2. Installer desktop appears, Tour guide is shown.
3. Go to Install section, press button, nothing happens.
4. Click on installer shows an icon running on dock bar.
5. A few seconds later the running icon stops and disappears. 

**Expected behavior**
The installer windows is shown to install on HD.

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
How many CPU cores does the VM have?

**Comment by cyberdarius** [comment]
Same sitution.

Virtualbox default set 1 CPU. With 1 cpu installer doesn't start.
I added 2 cpu and now the installer works :-)


Thanks for this awesome distro !!!

**Comment by asteriogonzalez** [comment]
> How many CPU cores does the VM have?

Just 1. Using 4 cores works fine for me.

Thanks for the great distro!.

PS: Please, give some hint in the tour when installation detects is running in a VM. I think this really help in the viralization of your great work.

**Comment by dominichayesferen** [comment]
Right... this might be a past Calamares bug where a certain release wouldn't load if there was only one CPU core. I'll be sure to update Calamares to a version that fixed this bug, though, in a near-future minor ISO update.

**Comment by dominichayesferen** [comment]
Does this still occur in the latest ISOs?
