### ISSUE TITLE
Connecting to wifi is buggy during install from USB

### ISSUE THREAD

**Issue by periwinkleFTW** [feren-OS/Bug-Reporting-Center#186]
**Package Name or Section of Feren OS where this bug resides**
Feren OS installation

**Describe the bug**
When I boot up from usb and try to connect to wifi it asks me to enter wifi password in the popup where all the networks are listed (in the bottom right corner), However, even after entering correct password I have to enter the password again in a dedicated popup at the center of the screen

**Steps to Reproduce**
Boot up from bootable USB, try to connect to a wifi

**Expected behavior**
You should connect to wifi the first time you enter correct password

**Comment by dominichayesferen** [comment]
#174
