### ISSUE TITLE
Installing packages froze twice

### ISSUE THREAD

**Issue by periwinkleFTW** [feren-OS/Bug-Reporting-Center#187]
**Package Name or Section of Feren OS where this bug resides**
Feren OS 2020.11, store

**Describe the bug**
Installation of a package froze

**Steps to Reproduce**
1. Open store
2. Select Docker.io or Steam
3. Installation frozen about halfway through
Issue is resolved after a restart

**Expected behavior**

**Screenshots**

**Additional context**
It's a dual boot system

**Comment by dominichayesferen** [comment]
#182
