### ISSUE TITLE
System does not boot after installing steam and python 3.9

### ISSUE THREAD

**Issue by periwinkleFTW** [feren-OS/Bug-Reporting-Center#189]
**Package Name or Section of Feren OS where this bug resides**
kde

**Describe the bug**
After installing steam latest python a lot of apps stopped working. I restarted and after entering my password there is a black screen that says 
"kactivitymanagerd - The KDE Crash Handler <2>" 
Details: kactivitymanagerr PID: 3698 Signal: Aborted(6)

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by periwinkleFTW** [comment]
There is no way to report this issue because the 'Report Bug' button is greyed out

**Comment by dominichayesferen** [comment]
This might be related to a bug that occured when updating to Plasma 5.20. Try following this guide: https://medium.com/feren-os/plasma-workspace-issue-fix-and-fix-methods-for-those-affected-36f3ddd81e96

**Comment by periwinkleFTW** [comment]
Started having another bug with dual screen setup. After boot when i press the Feren symbol (bottom left) the menu would open on the secondary screen. This issue is intermittent, and I could not find a reliable way to reproduce it.

**Comment by dominichayesferen** [comment]
Did you follow the guide I linked to you, though?

**Comment by periwinkleFTW** [comment]
No. I went back to Ubuntu. Feren's UI is amazing but store installation bugs and start menu appearing on another monitor was just too much.
