### ISSUE TITLE
Malformed input, repository not added.

### ISSUE THREAD

**Issue by garvizu** [feren-OS/Bug-Reporting-Center#190]
I am trying to install Docker on Feren OS.

When I get to the part of adding the repository I get the error "Malformed input, repository not added."

> sudo add-apt-repository \
> "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
> $(lsb_release -cs) \
> stable"

I assume that $ (lsb_release -cs) must be focal. I have tried replacing it with focal, with the same result.

> sudo add-apt-repository \
> "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
> focal \
> stable"

Malformed input, repository not added.

Any suggestions?

**Comment by dominichayesferen** [comment]
Just write it into the file manually via `sudo nano /etc/apt/sources.list.d/docker-linux.list`

CTRL+X to exit and then 'y' to save changes.

**Comment by garvizu** [comment]
It works 

> Just write it into the file manually via `sudo nano /etc/apt/sources.list.d/docker-linux.list`
> 
> CTRL+X to exit and then 'y' to save changes.
> `deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable`

It works ok, Thank you
