### ISSUE TITLE
Latte won't unhide

### ISSUE THREAD

**Issue by bongo-x** [feren-OS/Bug-Reporting-Center#192]
**Package Name or Section of Feren OS where this bug resides**

Latte dock

**Describe the bug**

Latte dock on the right side will not unhide.

**Additional context**

Just started after updates of last 24 hours
Starting to remove Feren-latte-config from the store makes it instantly appear, actually removing it makes it broken again. Installing and reinstalling Feren-latte-config and Latte doe not help.
I managed to pull up dock options when it appeared when starting to remove and switched it to the bottom of the screen. Works fine on bottom of screen.

**Comment by dominichayesferen** [comment]
#172
