### ISSUE TITLE
Lock screen broke

### ISSUE THREAD

**Issue by LavenderSolus** [feren-OS/Bug-Reporting-Center#194]
One the very 1st day of my first ever try with Feren OS, the lock screen broke.

DETAILS:
It only had one option written on the screen, something like "Press Ctrl+Alt+F2 and enter (xyz command) then press Ctrl+Alt+F10."

WHAT I DID:
I did the same logged in on a CLI window that it showed, and login was good as it said but after login when I pressed the 2nd set of keys it did nothing. Didn't find much on the internet to help me so I had to totally reinstall (as I am not an expert).
Now running the 2nd install (whole drive as before) but this time I switched off the screen lock feature.
Please fix it.

WHAT WAS GOING ON WHEN IT HAPPENED:
Not much. I was just tweaking the looks and some downloads (softwares) were running from thre software center that's all.

**Comment by dominichayesferen** [comment]
Can't reproduce this issue, personally.

**Comment by LokiLinux** [comment]
> Can't reproduce this issue, personally.

I'm new to Linux so I actually don't mean what you said there. Please be more newbie-friendly.

**Comment by dominichayesferen** [comment]
I can't reproduce the issue, that's all it means.
