### ISSUE TITLE
Double Ampersand on Authorization Notification Pop-up

### ISSUE THREAD

**Issue by DvorakUser** [feren-OS/Bug-Reporting-Center#195]
**Package Name or Section of Feren OS where this bug resides**
Authorization Notification Pop-up

**Describe the bug**
Two ampersands when only one is needed

**Steps to Reproduce**
1. Connect PlayStation 4 controller via USB

**Expected behavior**
First button should be "Trust & Authorize" instead of "Trust && Authorize"

**Screenshots**
![ Trust Authorize Error](https://user-images.githubusercontent.com/16712082/103947869-a7588680-50ed-11eb-9702-e3127beac96c.png)

**Additional context**

**Comment by dominichayesferen** [comment]
Please update to Plasma 5.20.5, using yesterday's updates, and check again.
