### ISSUE TITLE
Problem with Repositories (update manager) 

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#202]
I started getting this today not sure why.. what can i do to fix it

![probem with repo](https://user-images.githubusercontent.com/16531121/105405072-b7498d80-5bf8-11eb-946b-0971b3ea1bd3.png)

**Comment by dominichayesferen** [comment]
Odd... try doing `sudo apt update` in Konsole so that I can actually have some useful output since it appears Synaptic failed to provide any helpful output here.

**Comment by tjw0lf** [comment]
There's no really useful output in terminal? I updated few packeges. It said upgradebale. Also i changed out gdebi and gdebi-core for mints you should go with that when its nice cleaner look i think for feren-os. But that shouldn't be given me the output i'm getting because i did that! Right.

```
- [sudo] password for tj: 
- Hit:1 http://mirror.clarkson.edu/ubuntu focal InRelease
- Hit:2 http://archive.canonical.com/ubuntu focal InRelease                                                                                                                                           
- Hit:3 http://mirror.clarkson.edu/ubuntu focal-updates InRelease                                                                                                                                     
- Hit:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                        
- Hit:5 http://mirror.clarkson.edu/ubuntu focal-backports InRelease                                                                                                                                   
- Hit:6 http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu focal InRelease                                                                                                                              
- Get:7 https://gitlab.com/feren-os/feren-repositories-neon-focal/raw/master stable InRelease                                                                                                
- Hit:8 http://security.ubuntu.com/ubuntu focal-security InRelease                          
- Hit:9 https://dl.winehq.org/wine-builds/ubuntu focal InRelease      
- Get:10 https://gitlab.com/feren-os/feren-repositories-focal/raw/master stable InRelease
- Ign:11 http://repo.vivaldi.com/stable/deb stable InRelease
- Hit:12 http://repo.vivaldi.com/stable/deb stable Release
- Fetched 8,605 B in 2s (4,925 B/s)
- Reading package lists... Done
- Building dependency tree       
- Reading state information... Done
- 2 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by dominichayesferen** [comment]
That just sounds like it was somehow locked or something... as if package management was occuring.

**Comment by dominichayesferen** [comment]
I guess if there's no issues, now...

**Comment by tjw0lf** [comment]
No its still not fixed @dominichayesferen  WHY DO YOU KEEP ON TAGGING IT  TO BE CLOSED

**Comment by dominichayesferen** [comment]
Well, then just say it isn't fixed... not that hard to not act like a child on Discord over an action someone does.
![Uploading Screenshot_20210131-185347.jpg…]()

**Comment by dominichayesferen** [comment]
Well, then just say it isn't fixed... not that hard to not act like a child on Discord over an action someone does.
![Screenshot_20210131-185347](https://user-images.githubusercontent.com/11057934/106394697-c5b45800-63f5-11eb-8c3a-6a4aa299c5e4.jpg)

**Comment by tjw0lf** [comment]
You Damn well Know hasn't been fixed Stop acting like little stupid bitch girl! Go watch your anime cartoons suck your Mommys nippes mother fucker

@dominichayesferen  WhY the fuck do you keep on tagging my shit to be Close motherfucker! When you know damn well this issue hasn't been fixed yet? Your fucking bitch DUDE.....

**Comment by dominichayesferen** [comment]
> You Damn well Know hasn't been fixed Stop acting like little stupid bitch girl! Go watch your anime cartoons suck your Mommys nippes mother fucker
> 
> @dominichayesferen WhY the fuck do you keep on tagging my shit to be Close motherfucker! When you know damn well this issue hasn't been fixed yet? Your fucking bitch DUDE.....

Well then, I hope you like a block and being reported to GitHub for acting like a spoilt child. Oh, did I mention that being unnecessarily abusive towards people and projects is literally against the GitHub Terms of Service?

Either way, with the attitude of a child you have shown here and in my Discord server, good luck getting any help anywhere, TJ Wolf. _To think I considered you A FRIEND at one point._
Get banned.
