### ISSUE TITLE
Update manager issue

### ISSUE THREAD

**Issue by FerenFanboy** [feren-OS/Bug-Reporting-Center#208]
**Package Name or Section of Feren OS where this bug resides**
Update manager

**Describe the bug**
I get the message:
"Could not download all repository indexes"
"The repository may no longer be available or could not be contacted because of network problems. If available, an older version of the failed index will be used. Otherwise, the repository will be ignored. Check your network connection and ensure the repository address is correct in 'Repositories' under 'Settings'.".

**Steps to Reproduce**
Everytime I open update maanger I get the same error

**Expected behavior**
For me to be able to access the latest updates

**Screenshots**

**Additional context**
My internet connection is fine. This issue only started to happen on a  regular basis after the latest  major Feren update

**Comment by dominichayesferen** [comment]
#205
