### ISSUE TITLE
user's profile goes blank after login

### ISSUE THREAD

**Issue by bolaji23** [feren-OS/Bug-Reporting-Center#215]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? latest feren OS standard ___

**Describe the bug**
A clear and concise description of what the bug is after login, the windows goes blank 

**Steps to Reproduce**
Steps to reproduce the behavior: install latest feren, update and upgrade, reboot, login and its a blank welcome screen with just the cursor showing
1. 

**Expected behavior**
A clear and concise description of what you expected to happen.blank welcome screen with just the cursor showing

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
Assuming you're running into an odd bug, just strike CTRL+ALT+T, and run these commands to fix this:
```
sudo apt update
sudo apt dist-upgrade -y
reboot
```
