### ISSUE TITLE
Fresh install with updates breaks install

### ISSUE THREAD

**Issue by Faldiin** [feren-OS/Bug-Reporting-Center#216]
Cheers,
          I have completed 5 installs on 2 laptops. One is Lenovo Work laptop and the other is Eluktronics laptop. Both have Nvidia graphics cards. What I found is with fresh install from ISO, the system is fine. When you complete a patch of the whole system and reboot, you cant log in. You may use the login password and get the welcome screen. After a minute, you are back at the login screen. Performed this again and pressed ALT + F2. Went into Term and updated the system. There was 7 packages held back. If you force the install then reboot, you are unable to login at all. Get failed to start session. 

To resolve the issue.
            Completed the install. When Patching, I said No to all the maintained package changes. Then when I got the same welcome screen issue, forced install the 7 kde packages which included X11. Rebooted the laptop. Logged in and recieved a popup about Fenen Desktop INI change. Applied the change. No more issues. I have completed these steps on both laptops. 

Thank you for the OS. Good Luck.

**Comment by dominichayesferen** [comment]
Since, you, uh... fixed it... guess I'll close this like any fixed bug.

**Comment by Faldiin** [comment]
A month ago when I was first playing with your Distro, this issue did not happen. This is something with the new update. As I bypassed your changes, that is not fixed. You may do what you like with it though. Your distro.

**Comment by dominichayesferen** [comment]
The fix for it is literally updating your system fully, it seems. Therefore, you've done the fix, so this is fixed.

**Comment by Faldiin** [comment]
Cheers,
          If your idea of fixing is bypassing your patches and having to
force install additional patches that are being held back, this would be an
interesting ride with your OS. I have been using linux as my main os for 10
years. I have never had to do this unless something is broken. Your OS and
I will respect your decision. I am moving on though. Good Luck.

**Comment by dominichayesferen** [comment]
The fix is literally just updating your system. End of.
