### ISSUE TITLE
Black screen with cursor only after latest updates

### ISSUE THREAD

**Issue by cnarff** [feren-OS/Bug-Reporting-Center#217]
**Package Name or Section of Feren OS where this bug resides**
Latest FerenOS 2021.01

**Describe the bug**
At startup, I've got the welcome message and then, just a black screen with the cursor (I can move it).

**Steps to Reproduce**
1. I updated my 2nd external SSD and I've got the same issue.
2. My computer is 
Processors: 2 × Intel® Pentium® CPU G4400 @ 3.30GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 510

**Screenshots**
![image](https://user-images.githubusercontent.com/80960561/111780176-f0c40f80-88ae-11eb-9706-96ba33e98301.png)

**Additional context**
PLease help !

Thanks

**Comment by dominichayesferen** [comment]
Refer to #216

**Comment by dominichayesferen** [comment]
Refer to #215
