### ISSUE TITLE
when using vm display donsent work on virtual box plz fix

### ISSUE THREAD

**Issue by therealstrikeman** [feren-OS/Bug-Reporting-Center#221]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
That's not enough information for a bug report. Please fill in the fields.

**Comment by therealstrikeman** [comment]
oh its Because My vm did not work with the screen resolution when i used feren OS, it did Work with Deepin OS and other Linux OS
so its  broken on virtual box so you have to install it on your laptop whether you like it or not you have to because its dev did not see it coming

**Comment by dominichayesferen** [comment]
what?

**Comment by dominichayesferen** [comment]
There isn't enough information on this bug report, so I'm going to have to close it due to no response of adding information.
