### ISSUE TITLE
SUPER key does not open app menu

### ISSUE THREAD

**Issue by oopmarcos** [feren-OS/Bug-Reporting-Center#228]
Pressing the SUPER key does not open the app menu, I have tried changing layouts and the error persists.
I have tested if the key itself works and it does.

**Comment by dominichayesferen** [comment]
Try going into the applications menu's settings and setting it to "ALT+F1" manually.

![image](https://user-images.githubusercontent.com/11057934/118174330-96ff4200-b426-11eb-93f4-3a76c3c02b61.png)

![image](https://user-images.githubusercontent.com/11057934/118174464-c4e48680-b426-11eb-833a-31daeaee5e95.png)

**Comment by oopmarcos** [comment]
Maybe I should have added, I'm using the Redmond layout, which is using the Application Menu. I changed the shortcut but it still doesn't work.

**Comment by oopmarcos** [comment]
Ok I just changed to the Feren Application Launcher, then back to the Application Menu, changed the shorcut again, and now it works. Thanks a lot for your help.
