### ISSUE TITLE
system reports crash logs

### ISSUE THREAD

**Issue by terryglover** [feren-OS/Bug-Reporting-Center#23]
Vivaldi web browser crashed** and **_system report_**s show numerous issues with cups for printer driver, no longer workin

**Describe the bug**
[troubleshoot.txt](https://github.com/feren-OS/Bug-Reporting-Center/files/3192240/troubleshoot.txt)

/tmp/mintreport/crash
/tmp/mintreport/reports

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**
I/home/terry/Pictures/Screenshot from 2019-05-17 17-11-34.png
f applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by feren** [comment]
The screenshot didn't get uploaded.

As for the CUPS issue... try removing and re-adding the printer, possibly? Little stumped on that one...

**Comment by terryglover** [comment]
Latest Vivaldi stable crashes every time opened, screen diagonal lines and frozen,system then has to be re-booted , it caused such a problem that i had to re-install feren as it would not start past the feren icon
[troubleshoot (1).txt](https://github.com/feren-OS/Bug-Reporting-Center/files/3195627/troubleshoot.1.txt)

**Comment by feren** [comment]
So I'm guessing it all works fine now?

**Comment by terryglover** [comment]
Hi, sorry but system crashed twice since i emailed you today, its the new
updated Vivaldi browser it does not like, i am in process of swapping to
firefox
thanks for your prompt response

Terry Glover

**Comment by terryglover** [comment]
HI, i have just installed the firefox web browser and unfortunatly my 
problem remains in that after shutting down/restarting and launching 
the browser (vivaldi and Firefox)  they fail and colour screen frozen, 
i have to power off and restart to get into the system, which loads to 
my homescreen no problem, using any of the apps (other than browsers no 
problem) wondering if its the generic graphic driver causing issue

**Comment by feren** [comment]
@terryglover What's your hardware?
