### ISSUE TITLE
Feren OS Installer never loads - Continuous Spinner

### ISSUE THREAD

**Issue by blu-frog** [feren-OS/Bug-Reporting-Center#233]
Unable to get the first window of the OS Installer to successfully load. I was able to use this same Live USB stick to successfully install on a different system (Toshiba Laptop).

Repro Steps:
1. Double-click the "Install Feren OS" shortcut on the desktop
2. Wait for the application to fully load so as to change the Language Selection (from EN-UK to EN-US)

Repro Rate: 3/3 (Including booting with `nomodeset` for the nVidia Card)

![Screenshot_20210526_212320](https://user-images.githubusercontent.com/40070339/119766927-c1abba80-be6a-11eb-9125-ce7f6a35d8df.png)

**Note:** Cannot terminate calamares when this application window gets stuck either.

System Info:
**Dell Optiplex 755 (Desktop)** with NVIDIA GK208B [GeForce GT 710]

Operating System: Feren OS 2021.04
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.8.0-48-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 2 × Intel® Core™2 Duo CPU E8400 @ 3.00GHz
Memory: 7.6 GiB of RAM
Graphics Processor: llvmpipe

**Comment by dominichayesferen** [comment]
You might wanna consider reporting this to Calamares, too, so the people who made this installer are aware of this.
https://github.com/calamares/calamares
