### ISSUE TITLE
ksplashqml crash (non-default layout)

### ISSUE THREAD

**Issue by Zahrun** [feren-OS/Bug-Reporting-Center#235]
**Package Name or Section of Feren OS where this bug resides**
ksplashqml

**Describe the bug**
ksplashqml crashes

**Steps to Reproduce**
1. Install feren OS, choose 'familiar' layout (probably true for the other non-default layouts)
2. Install updates
3. Reboot
4. Login
5. ksplashqml crashes

**Expected behavior**
ksplashqml shows the splash screen

**Screenshots**
![image](https://user-images.githubusercontent.com/10415894/120894438-a6823d00-c618-11eb-8422-b17a92e533a4.png)

**Additional context**
Probably related to the change of name from 'familiar' to 'doors' (and other layout renamed)
Workaround: set the splash screen in the advanced settings or change desktop layout.

**Comment by dominichayesferen** [comment]
Can you please upload ~/.config/ksplashrc? (CTRL+H to show hidden files and folders)

**Comment by Zahrun** [comment]
There is no such file at the time this bug occurs

**Comment by dominichayesferen** [comment]
Outta the sake of merging, and since I accidentally focused activity on #239, I'll merge it with that one by closing this one for Duplicate.
