### ISSUE TITLE
snap won't work

### ISSUE THREAD

**Issue by BAB1222** [feren-OS/Bug-Reporting-Center#237]
When I use the Welcome center to get snap, it will not work. I click on snap and nothing happens at all. I went to the store and downloaded snap. It doesn't show up anywhere in the programs list, but I do a search and find it. I click on it and nothing happens. 
Brad

**Comment by dominichayesferen** [comment]
So "Snap Store" is present in your applications menu?

**Comment by BAB1222** [comment]
No it isn't. If I search for snap on the computer I get a "run snap" option but when I click on it nothing happens.

**Comment by dominichayesferen** [comment]
Could you go into Konsole, type `feren-welcome`, press ENTER, reproduce the issue, and then post the output here?

**Comment by BAB1222** [comment]
OK here's 2 screen shots, the first one is what happens after I click install software. then I click Snap apps and it just goes back to nothing. No matter how long it sits there nothing will happen. Also the way I see snap appear in the first one is now how it shows me in the directions. In the directions, if I recall correctly, it comes up in a window on the left side. [
![error 1](https://user-images.githubusercontent.com/85803834/121821109-cf33b380-cc64-11eb-8808-b1514a95971e.jpg)
![error 2](https://user-images.githubusercontent.com/85803834/121821113-d22ea400-cc64-11eb-9334-b0adaec4a615.jpg)

](url)

**Comment by dominichayesferen** [comment]
Could you go into Konsole, type `feren-welcome`, press ENTER, reproduce the issue, and then post the output (what the Konsole says) here?

**Comment by BAB1222** [comment]
Did you get my post from 4 hours ago? Those are the only 2 screen shots to give you. No error message, absolutely nothing else happens. The snap apps thing disappears and nothing at all happens.

**Comment by dominichayesferen** [comment]
What does Konsole say, though?

**Comment by BAB1222** [comment]
Sorry I didn't realize what you wanted. 
![feren error](https://user-images.githubusercontent.com/85803834/122406367-ca198180-cf4e-11eb-8cbd-d2d0b21833aa.jpg)

**Comment by dominichayesferen** [comment]
Hmm... weird.

Could you close Welcome Screen, and then type `snap install snap-store && snap-store` and press ENTER?

**Comment by BAB1222** [comment]
It worked!!! thanks so much for your time and willingness to help and knowledge. This is part of the reason I like Feren so much! I just recently ditched windows and have tried several Linux OS, and this one impressed me the most and hit the sweet spot!
Brad

**Comment by dominichayesferen** [comment]
This bug has been confirmed, and fixed
