### ISSUE TITLE
Can`t install FerenOS alongside Windows

### ISSUE THREAD

**Issue by alvarohnl** [feren-OS/Bug-Reporting-Center#24]
**Describe the bug**

**Steps to Reproduce**
1. I tried to install FerenOS alongside Windows like I did dozens of times before with others distros.

**Expected behavior**
Instalation completed.

**Screenshots**
![Screenshot from 2019-05-23 16-55-41](https://user-images.githubusercontent.com/8726785/58291806-2e2fe280-7d95-11e9-8108-9004bfb9a559.png)

**Additional context**

**Comment by feren** [comment]
Did you go through the **Manual Partitioning** option?
If so, make sure that the small FAT32 partition that's usually at the top of the hard drive (that stores a folder in it called 'EFI' when mounted via Disks) is modified as follows:
- Format? No
- Boot Flags = boot
- Mount Location = /boot/efi

Then it should install. If you didn't use Manual Partitioning to get to this error, do let me know.

**Comment by alvaro-nogueira** [comment]
Thanks, I will try later and update this issue

**Comment by feren** [comment]
@alvaro-nogueira Did it work?

**Comment by alvaro-nogueira** [comment]
@feren yes, I select the EFI partition and worked.
