### ISSUE TITLE
Some applications have strange border around windows after update of package feren-theme 2021.07.0.0.0+ubrel2

### ISSUE THREAD

**Issue by J-Putnam** [feren-OS/Bug-Reporting-Center#240]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

Somewhere within feren-theme 2021.07.0.0.0+ubrel2

**Describe the bug**

A border the same color of the selected theme accent is produced around the window of some applications, noted it Warpinator.

**Steps to Reproduce**
1. Update feren-theme
2. restart x-server, login
3. start Warpinator
4. strange border is shown

**Expected behavior**

No extra border artifact shown

**Screenshots**

![Buggy_Update](https://user-images.githubusercontent.com/87282393/125209721-786bca80-e260-11eb-840b-6425b27ff46c.png)
![buggy_update_located](https://user-images.githubusercontent.com/87282393/125209727-7f92d880-e260-11eb-9b25-0e7b5ef48dfb.png)

**Additional context**

I have isolated it to this update after reverting to a previous Timeshift backup and then updating everything but the feren-theme package.  Everything works as expected.  Once I update the individual file and preform the steps to reproduce it, the border appears.

Thank you,
J Putnam

**Comment by J-Putnam** [comment]
Also, I have noticed my system is unstable with this update.  I have had plasma crash and restart a few times and even had the whole system lock up unresponsive forcing a hard reset.

**Comment by dominichayesferen** [comment]
(I swear to gosh I fixed that borders issue a while ago)
Marked as confirmed as this graphical bug occurs in the GTK+ theme when the Compositor is off.

**Comment by dominichayesferen** [comment]
Fixed in feren-theme 2021.07.0.0.1
