### ISSUE TITLE
Blank, transparent frame is appearing instead of KRunner launcher bar

### ISSUE THREAD

**Issue by lennyqebian** [feren-OS/Bug-Reporting-Center#242]
**Package Name or Section of Feren OS where this bug resides**
It happens when I'm trying to open KRunner with the default keyboard shortcut (Alt + F2) or from a Konsole.

**Describe the bug**
Instead of KRunner launcher, a blank, transparent frame is appearing after pressing Alt + F2 or executing `krunner` command from a Konsole.

**Steps to Reproduce**

1. Press the Alt + F2 or Alt + Space keyboard shortcut.
2. Check whether KRunner launcher bar or a transparent frame is shown.

Alternative flow:

1. Open a Konsole terminal window.
2. Type the `krunner` command and press ENTER key.
3. Check whether KRunner launcher bar or a transparent frame is shown.

**Expected behavior**
KRunner launcher bar is expected to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/5828527/126721249-2d2b40aa-ccd9-414a-8c19-e6b98147f83d.png)

Expected:

![image](https://user-images.githubusercontent.com/5828527/126788386-dd8f0c4c-2733-4d70-92e2-35adcb2cde68.png)

**Additional context**

**Comment by dominichayesferen** [comment]
Try reinstalling Plasma Desktop Workspace:
Go into Konsole and type `sudo apt install --reinstall plasma-workspace`, press ENTER, provide your login password, and then confirm with Y, then log out and back in and try KRunner again.

**Comment by dominichayesferen** [comment]
Does this still happen after performing those steps?

**Comment by dominichayesferen** [comment]
This has been found and identified to be an upstream issue with KDE Plasma failing to handle non-existent Global Theme IDs.

It has been reported here: https://bugs.kde.org/show_bug.cgi?id=462217
