### ISSUE TITLE
Icons placement wrong in desktop activities

### ISSUE THREAD

**Issue by Sahil2004** [feren-OS/Bug-Reporting-Center#243]
**Package Name or Section of Feren OS where this bug resides**
This bug happens in various activities

**Describe the bug**
When I switch to any activity the icons don't seem to respect the pannel on top and go under it. When I press edit pannel for that particular activity, it corrects it for that but when I switch back to another one, it breaks it there.

**Steps to Reproduce**
1.  Create a new activity
2.  Have some icons on the desktop
3.  Edit the pannel on that activity and it will break it on others

**Expected behavior**
The icons should respect the pannel that is there.

**Screenshots**
![image](https://user-images.githubusercontent.com/40143545/127034663-6a71dec4-cd35-4170-87dd-86af1956a0c0.png)

**Comment by dominichayesferen** [comment]
What panel are you using, Latte Dock or Plasma?

**Comment by Sahil2004** [comment]
The above one is plasma (shown in the pic) and the below one is latte (dock).

**Comment by Sahil2004** [comment]
BTW it seems to have been fixed today. The bug is no longer there. Might have been fixed due to a restart.

**Comment by dominichayesferen** [comment]
Guess I'll close this, then, if that's the case.
