### ISSUE TITLE
Issue with Display Brightness Stability

### ISSUE THREAD

**Issue by sloefan** [feren-OS/Bug-Reporting-Center#244]
**Package Name or Section of Feren OS where this bug resides**

Display with any program running.

Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

Spontaneously.

**Describe the bug**

Display Brightness unstable with sudden increases or decreases without any user input.

**Steps to Reproduce**
1.

Laptop is MSI GE62 2QF. Possibly a hardware-compatability issue, not experienced with other OS.

**Expected behavior**

I expect display brightness to remain stable and only change when intentionally adjusted.

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
Does this happen while user input is being done to the computer? If not, it's likely the intentional darkening that every OS does to warn of the screen about to be turned off to save power during inactivity.

**Comment by sloefan** [comment]
In normal circumstances the screen would dim after 3min or so, that still happens. In this case the brightness bar appears on screen without any prompting and it'll go right down, potentially to 0 depending on what the brightness was, or it will rush up to a considerably higher number.

If a heavy application is running or not I don't think it makes much of a difference. I suppose it's just more blatant if I'm looking at the desktop or a browser session. I'd love to give a more precise answer than this but I've tried it with the graphics card only or off in any case. It still seems entirely random.

**Comment by dominichayesferen** [comment]
I'd potentially go and report that to https://bugs.kde.org .

**Comment by sloefan** [comment]
Thanks for the link

**Comment by sloefan** [comment]
This 'temporary' fix worked for me...

https://askubuntu.com/questions/777754/brightness-randomly-up-and-down-on-msi-laptop/808785#808785
