### ISSUE TITLE
Aug, 22 2021 update messed desktop, regardless of layouts

### ISSUE THREAD

**Issue by kosmos-kahnn** [feren-OS/Bug-Reporting-Center#248]
I updated quite a few packages that were included in a standard update using the update tool. After completing them they messed the desktop up. The issue I am having is a gap of about 12 px, according to the top panel. I tried switching the layout to a few options and it still does not change that gap, I can resize the panel up to cover the gap but it is too big for my taste. This issue persists not matter if I use a recovery option or the last updated one. 

I really love this distro and hope to keep using it but am always nervous because a few updates can sometimes ruin the system for me, and I would love to see this distro be awesome. If there is any other info I can provide please let me know and thanks for the awesome system.

kosmos kahnn

**Comment by dominichayesferen** [comment]
Could you post a screenshot?

**Comment by kosmos-kahnn** [comment]
![image](https://user-images.githubusercontent.com/89363265/131235158-4a9b7c87-c262-4fbb-a207-df62701ca6c5.png)

This for reference has the top bar height at 28 and to get it to connect to the max window, I would have to resize it to 38.
That is the max window allowed, no matter the layout

**Comment by qy117121** [comment]
I reverted the software version to resolve
https://gitlab.com/feren-os/feren-repositories-neon-focal/-/blob/c966c97e81e0afe31963b38f196020ccf6f668b9/pool/neon-focal/l/latte-dock/latte-dock_0.9.12-0xneon+20.04+focal+release+build5_amd64.deb

**Comment by kosmos-kahnn** [comment]
worked like a charm thanks so much and as always thanks for the distro, still my favorite. Keep up the good work

**Comment by dominichayesferen** [comment]
I've sent out an update that mostly alleviates these issues on the latest Latte Dock.
