### ISSUE TITLE
Install fails when installing locals.  Computer goes into shutdown.

### ISSUE THREAD

**Issue by J-Putnam** [feren-OS/Bug-Reporting-Center#251]
I have tried to install Feren on my neighbors All-in-one HP and everything works perfect until I get to the reboot and setup the user info.  After I setup the password and proceed with the install it stops at the "installing locals" part then goes through the shutdown process.  I tried to install Linux Mint and Manjaro which install just fine, but they are not Feren.  

How can I show off to my customers how cool Linux can be when I am stuck with vanilla Cinnamon or buggy Manjaro?  Any ideas on how to fix this?

**Comment by J-Putnam** [comment]
So, I removed my internet connection to the computer and started the install from scratch.  The install worked this time.  I don't know what is wrong, but something it was trying to download was messing with the install.

**Comment by dominichayesferen** [comment]
Can reproduce, working on fixing this.

**Comment by sultandilaram** [comment]
I am facing the same error and stuck using my pc with live boot.
Can you please tell me(us) when shall we receive the fixed build.

**Comment by dominichayesferen** [comment]
> I am facing the same error and stuck using my pc with live boot.
> Can you please tell me(us) when shall we receive the fixed build.

Reinstall without an internet connection.

**Comment by dominichayesferen** [comment]
An update to `oem-config-feren` has removed `networkcfg` from the post-installation process

Can someone reinstall Feren OS **with** an internet connection to see if it works fine now?

**Comment by dominichayesferen** [comment]
A successful post-install has been done with the new package, meaning the problem is fixed for ALL new installs.

**Comment by J-Putnam** [comment]
Thank you for the quick response.  This is why I recommend and will only install Feren OS on my daily installs.
