### ISSUE TITLE
Nemo cannot handle network locations

### ISSUE THREAD

**Issue by swoopa** [feren-OS/Bug-Reporting-Center#26]
Clicking on Network in the category/bookmark list in Nemo gives an error Could not display "network:///" Nemo cannot handle "network" locations.
![Nemo-Network-Error](https://user-images.githubusercontent.com/25865515/58834753-b1e7aa00-8686-11e9-80fa-272eaebcc57c.png)

**Comment by feren** [comment]
`sudo apt-get install gvfs-backends` should fix it.

More information: https://forums.linuxmint.com/viewtopic.php?t=173992

**Comment by swoopa** [comment]
sudo apt install gvfs-backends fixed the problem thanks Feren

**Comment by feren** [comment]
Alright. Re-opening it so that it can be closed properly once the latest Next ISO fixes this.

**Comment by feren** [comment]
Fixed in Feren OS Next Beta.
