### ISSUE TITLE
BR Portuguese language unable to write letters with accents ã,õ,ê,í etc

### ISSUE THREAD

**Issue by AndrewLaganaro** [feren-OS/Bug-Reporting-Center#269]
**Package Name or Section of Feren OS where this bug resides**
Installation process

**Describe the bug**
Brazilian Portuguese language unable to write letters with accents ã,õ,ê,í etc on keyboard testing right after installation
They come out bugged with the accent before the letter: ~a~o^e etc

**Steps to Reproduce**
Install the OS, go to keyboard testing. Select Brazilian Portuguese as language, try typing letter with accents: ã,õ,ê,í,á,à,ó,ò etc

**Screenshots**
on Vivaldi after installation;
![image](https://user-images.githubusercontent.com/45211616/150865896-dae7e878-024c-4a26-993f-eee766986649.png)

**Comment by AndrewLaganaro** [comment]
Weird. tried to change the layout back to english them back to portuguese and letters started to work as expected

**Comment by AndrewLaganaro** [comment]
apparently I choose the layout PT-BR with "no dead keys" and this is what caused the problem. When i switched back from english to portuguese again, it landed on "deafult" layout for PT-BR and things went back to normal :)

**Comment by dominichayesferen** [comment]
In that case, I'll mark it as User Error and close.
