### ISSUE TITLE
no key / manage update

### ISSUE THREAD

**Issue by mariancha** [feren-OS/Bug-Reporting-Center#270]
hi, this is a message when i try to update the system, thanks : NO_PUBKEY C8CAB6595FDFF622

![screenshot](https://user-images.githubusercontent.com/99098496/152658894-9036cee7-73aa-41be-9ff3-eb7090b73cad.png)

**Comment by dominichayesferen** [comment]
Go into Software Sources and try Resetting.

**Comment by mariancha** [comment]
thank you for your message, last week end, i have found on a website a
solution : in a terminal

sudo rm -r /var/lib/apt/lists
sudo mkdir -p /var/lib/apt/lists/partial
sudo apt-get update
