### ISSUE TITLE
update on 3/20/22 broke feren

### ISSUE THREAD

**Issue by BAB1222** [feren-OS/Bug-Reporting-Center#272]
I got a fairly comprehensive update yesterday. I went ahead and told it to install. One portion of it said there was an error and it couldn't install, but most of it already had. After that no system setting of any sort would work, including shutting down the computer. I had to use the button on the cpu. It would no longer start up. I would get a plain blue screen asking for my password, put in the password and the password request box would come right back. I had to use timeshift this morning to fix it. 
thanks,
Brad

**Comment by Onliner58** [comment]
Hallo,
dieses Update hatte mein FerenOS kaputt gemacht und ich muste neu Installieren.
Danach wieder diese große Anzahl von Updates und ein nicht funktionierendes Feren im Anschluss.
Ich warte erst mal ab und lege Feren OS auf Eis.

**Comment by kagirohi** [comment]
I had same errors.

**Comment by Onliner58** [comment]
Das Update funktionierte heute 23.03.22 .
Auf der Feren Hompage ist zu lesen, das man nach der Aktualisierung warten und das System nicht gleich neu starten soll.

**Comment by Onliner58** [comment]
Alles gut und alles OK .
Vielen Dank.

**Comment by kagirohi** [comment]
Really!?
I need little courage...
Thank you. Vielen Dank.

**Comment by Onliner58** [comment]
Hallo,
nur Mut es funktioniert wirklich.

**Comment by kagirohi** [comment]
I tried to update with courage,but having same errors.
I updated packages from Update Manager again and Keeped device on a few minute definitely before reboot device.
But, it shows some error messages. According to error messages, libmlt7-7 and lib++7 package has something wrong.
Finally,I get a login screen asking for my password after reboot, put in the password and the password request box would come right back.

I have never be able to login.

**Comment by kagirohi** [comment]
I suceed to login with graphical.

Below Process
1. Creating SystemBackup.(For example : with Timeshift) This process is needed to restore from failing update. Please restore system with it if next process doesn't work
2. Updating packages via Update Manager of ferenOS.
3. **Keeping device on a few minutes(I guess 4-5mins) before reboot device.You must NOT reboot or shutdown soon.This is also announced by the article of medium.com of ferenOS** (https://medium.com/feren-os/plasma-5-24-is-now-available-in-feren-os-b4c5026e8a40)
4. If you fail to login with graphical, transiting to tty1 with striking CTRL+ALT+F1
5. Login there using your lowercase no spaces username, followed by your regular password.
6. Running below commands
  `sudo apt update` 
  `sudo apt upgrade`
   6.1　If you receive a warning that you need to run "apt --fix-broken install" with  broken packages
   `sudo apt --fix-broken install`
   Reboot after finishing the command.
   repeat process 4,5,6 after reboot.

Do you suceed to update all packages safe?
Do you have any broken packages?
I managed to go well. But, everyone ,all enviroments don't always managed to go well.
Please note

**Comment by Onliner58** [comment]
Hallo,
ich hatte Feren neu Installiert im Anschluss kamen 256 Updates und es läuft alles ohne Probleme .

**Comment by dominichayesferen** [comment]
1. The CTRL+ALT+F2 way
If you strike CTRL+ALT+F2, log in with your lowercase no spaces username and your normal password, and then run `sudo apt update`, giving it your normal password on the `sudo password` prompt, and there are no connection errors, you can use this method.

To begin, simply run (type it in and then press ENTER) `sudo apt update` again, and then run `sudo apt-get dist-upgrade -y` and then allow some time for `feren-autopackagemgmt` to kick in in the background once that second command is complete to make the final adjustments automatically to fix the issue.

**Comment by dominichayesferen** [comment]
2. The Live Session way

This method is a little more complicated, and to be frank reinstalling would be easier to do than this, but, here goes:

1. Boot into your Feren OS USB or DVD, if you have one
2. Connect to the internet
3. Go into Files, and mount the drive that contains folders like `usr`, `tmp`, etc.
4. Right-click on an empty spot of the list of files and folders in that drive, and select "Open in Terminal"
5. Type the following into Konsole, and press ENTER: `for i in /dev /dev/pts /proc /sys; do sudo mount -B $i ".""$i"; done`
6. Type the following into Konsole, and press ENTER: `sudo chroot .`
7. Type the following into Konsole, and press ENTER, and wait for it to give you the input section again: `apt update`
8. Type the following into Konsole, and press ENTER, and wait for it to give you the input section again: `apt dist-upgrade -y`
9. Type the following into Konsole, and press ENTER, and wait for it to give you the input section again: `/usr/bin/feren-automatic-package-management`
10. Type the following into Konsole, and press ENTER: `exit`
11. Restart back into Feren OS, and it should now be fixed
