### ISSUE TITLE
Plasma crashes after update

### ISSUE THREAD

**Issue by FlightRisk1903** [feren-OS/Bug-Reporting-Center#273]
After the update on 3/20, I get a blank screen have login. I couldn't find any errors in Xorg log, of in my home folder. I tried loading known good, but it doesn't work either. I also tried using apt to update and upgrade, as well as dist-upgrade. I eventually had to install xubuntu desktop to get a desktop environment.  I can't figure out how to reinstall plasma or reset the environment.

**Comment by kagirohi** [comment]
I had same errors.
Did you take a backup of Timeshift(application) in advance of the update and have a installtion media of ferenOS?
these helped me.

**Comment by kagirohi** [comment]
I suceed to login with graphical.

Below Process

Creating SystemBackup.(For example : with Timeshift) This process is needed to restore from failing update. Please restore system with it if next process doesn't work
Updating packages via Update Manager of ferenOS.
Keeping device on a few minutes(I guess 4-5mins) before reboot device.You must NOT reboot or shutdown soon.This is also announced by the article of medium.com of ferenOS (https://medium.com/feren-os/plasma-5-24-is-now-available-in-feren-os-b4c5026e8a40)
If you fail to login with graphical, transiting to tty1 with striking CTRL+ALT+F1
Login there using your lowercase no spaces username, followed by your regular password.
Running below commands
sudo apt update
sudo apt upgrade
6.1　If you receive a warning that you need to run "apt --fix-broken install" with broken packages
sudo apt --fix-broken install
Reboot after finishing the command.
repeat process 4,5,6 after reboot.
Do you suceed to update all packages safe?
Do you have any broken packages?
I managed to go well. But, everyone ,all enviroments don't always managed to go well.
Please note

**Comment by dominichayesferen** [comment]
Refer to #272
