### ISSUE TITLE
Dock problem with KDE

### ISSUE THREAD

**Issue by Lucy1958** [feren-OS/Bug-Reporting-Center#277]
**Package Name or Section of Feren OS where this bug resides**
Unable to use EDIT MODE to configure placement of dock widgets

**Describe the bug**
Unable to use EDIT MODE to configure placement of dock widgets.  Widgets - in group - go to far right of monitor after placing virtual workspaces next to Applications Screen

**Steps to Reproduce**
1. Right click on Applications Screen
2. Select Edit Mode

**Expected behavior**
Want to place widgets in CENTER of screen not far right

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dominichayesferen** [comment]
Screenshots would be helpful. Press PrtScrn on your keyboard to take a screenshot.

**Comment by Lucy1958** [comment]
Hey Dominic.

Naturally I figured out the solution to my issue after I sent this troubleticket.  Resolved by getting into edit mode and moving widgets one at a time.

Thanks for responding so quickly.  Very impressive support!

John

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
