### ISSUE TITLE
linux liqourix

### ISSUE THREAD

**Issue by mabahut** [feren-OS/Bug-Reporting-Center#279]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (feren os ) ___

**Describe the bug**
everytime i update liqourix ,os doesn't load it goes straight to busy box 

**Steps to Reproduce**
don't know how to use busy box ..keyboard don't work when i try and type help
1. 

**Expected behavior**
doesn't load 

**Screenshots**

**Additional context**

**Comment by mabahut** [comment]
someone must have had this problem not asking for help but would like to know if there is a fix many thanks

**Comment by dominichayesferen** [comment]
Liqourix is by no means officially supported by Feren OS. Any issues it causes are likely on itself. For now, you can boot normal kernels via the 'Advanced Options' area in your boot options screen (if it doesn't appear automatically, it is accessible by pressing ESC once during the manufacturer logo on newer computers, or pressing ESC once the manufacturer logo disappears on older computers).

**Comment by mabahut** [comment]
ok thanks i didn't know this, thankyou for taking time replying ,now i am much wiser on the os than i was yesterday :D

**Comment by mabahut** [comment]
hello thanks for you reply
i just did  a sudo apt update && sudo apt upgrade in Terminal and its booted just fine didn't go to busy box

________________________________
