### ISSUE TITLE
I couldn't mount my SD card memory

### ISSUE THREAD

**Issue by alexefu73** [feren-OS/Bug-Reporting-Center#281]
Hello dears,

I had installed the system update yesterday, that contains updating Xorg server and Linux kernel.
And now I couldn't mount my SD card, and tried several ones, it's opened in other PC's but not on my laptop after last updating.

And when I typed the 'dmesg' on the terminal I got the following output for sd card errors:

[    0.148878] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xe0000000-0xefffffff] (base 0xe0000000)
[    0.148878] PCI: MMCONFIG at [mem 0xe0000000-0xefffffff] reserved in E820
[    1.734764] mmc0: new high speed SDHC card at address 0001
[    1.985599] sr 1:0:0:0: [sr0] scsi3-mmc drive: 24x/24x writer dvd-ram cd/rw xa/form2 cdda tray
[    2.026364] mmcblk0: mmc0:0001 SD 7.44 GiB 
[    2.344242] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.344249] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.346989] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.346995] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.349506] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.349510] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.352251] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.352255] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.354746] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.354749] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.357448] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.357452] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.359935] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.359938] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.359943] Dev mmcblk0: unable to read RDB block 0
[    2.362637] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.362640] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.365130] blk_update_request: I/O error, dev mmcblk0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.365133] Buffer I/O error on dev mmcblk0, logical block 0, async page read
[    2.367859] blk_update_request: I/O error, dev mmcblk0, sector 24 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    2.367862] Buffer I/O error on dev mmcblk0, logical block 3, async page read
[    2.373089]  mmcblk0: unable to read partition table
[   20.962376] blk_update_request: I/O error, dev mmcblk0, sector 15597440 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[   20.972233] blk_update_request: I/O error, dev mmcblk0, sector 15597440 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[   20.972248] Buffer I/O error on dev mmcblk0, logical block 1949680, async page read

**Comment by dominichayesferen** [comment]
Could you try booting an older kernel by chance to see if doing so temporarily fixes the issue?

To boot into an older kernel:
1. (if you don't see a selection screen before booting into Feren OS) Press ESC once shortly after the manufacturer logo appears on startup, and before the Feren OS loading screen appears
2. Select Advanced Options
3. Select the `Feren OS with Linux...` option below the top `(recovery mode)` option

**Comment by alexefu73** [comment]
> Could you try booting an older kernel by chance to see if doing so temporarily fixes the issue?
> 
> To boot into an older kernel:
> 
> 1. (if you don't see a selection screen before booting into Feren OS) Press ESC once shortly after the manufacturer logo appears on startup, and before the Feren OS loading screen appears
> 2. Select Advanced Options
> 3. Select the `Feren OS with Linux...` option below the top `(recovery mode)` option

Yes, I did.  I rebooted into Kernel 5.13 then Kernel 5.11, but the same thing happend.  It was works with Kernel 5.13 and 5.11 before updating the system.

**Comment by alexefu73** [comment]
> If you have a USB or DVD that was used to install Feren OS, try booting into it to see if your SD Cards work in that environment. If not, it might be a coincidental hardware issue.

Hi dears,
Sorry for lating, I was away from my laptop for several days.
I had booted into Feren OS 2021.10 DVD, and the sd card worked as a charm.  Then rebooted into my updated Feren OS again.  The same problem still existing.

**Comment by alexefu73** [comment]
> > If you have a USB or DVD that was used to install Feren OS, try booting into it to see if your SD Cards work in that environment. If not, it might be a coincidental hardware issue.
> 
> Hi dears, Sorry for lating, I was away from my laptop for several days. I had booted into Feren OS 2021.10 DVD, and the sd card worked as a charm. Then rebooted into my updated Feren OS again. The same problem still existing.

I'm sorry, it's now working, after booting another time in updated Feren OS, it's working, but don't know what happend after rebooting the second time.  And when I typed 'dmesg | grep -i mmc' I get the following output:
`[    0.148711] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xe0000000-0xefffffff] (base 0xe0000000)
[    0.148711] PCI: MMCONFIG at [mem 0xe0000000-0xefffffff] reserved in E820
[    1.752064] mmc0: new high speed SDHC card at address 0001
[    2.013479] sr 1:0:0:0: [sr0] scsi3-mmc drive: 24x/24x writer dvd-ram cd/rw xa/form2 cdda tray
[    2.052843] mmcblk0: mmc0:0001 SD 7.44 GiB 
[    2.076432]  mmcblk0: p1
[  119.704779] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[ 2108.763693] mmc0: card 0001 removed
[ 2116.265262] mmc0: new high speed SDHC card at address 0001
[ 2116.266046] mmcblk0: mmc0:0001 SD 7.44 GiB 
[ 2116.269361]  mmcblk0: p1
[ 2116.459884] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
`

**Comment by dominichayesferen** [comment]
Either you didn't unmount your SD Card via the in-OS way the last time you used it (or by shutting your OS down or restarting as intended), or your computer has potential hardware-level issues. Former is the more likely scenario.
