### ISSUE TITLE
[Applet is being phased out] Record Screencast not working

### ISSUE THREAD

**Issue by shajupa** [feren-OS/Bug-Reporting-Center#29]
Record Screencast does not work

When you record screencast a video should ideally be stored in the video folder but it doesn't

**Comment by shajupa** [comment]
Is there any one looking into it ?

**Comment by feren** [comment]
I will in the coming days

**Comment by feren** [comment]
Alright, nearly forgot about this bug report, but... to be honest I think it's just a missing package but for one it used to complain if there was a missing package if I recall correctly in the past for me (it doesn't now though) and for two I've been really meaning to phase that applet out of Feren OS Cinnamon...

For now, just remove the applet and use SimpleScreenRecorder, it's available in the Store and it's more feature-rich but simple.

**Comment by feren** [comment]
Ah, right, for now try installing these packages through the Store if you otherwise want to keep the applet working until it's removed (they can be installed via the Store's search functionality):

- ffmpeg
- xdotool
- x11-utils

**Comment by shajupa** [comment]
Thanks buddy for your support. Looking forward to a stable feren OS in the coming days

**Comment by feren** [comment]
This applet is no longer available in Feren OS by default, coming the Linux Mint 19.2 base update to the ISOs.
