### ISSUE TITLE
No microphone settings can be found, and it's disabled

### ISSUE THREAD

**Issue by achede22** [feren-OS/Bug-Reporting-Center#291]
**Package Name or Section of Feren OS where this bug resides**
FerenOS microphone settings

**Describe the bug**
The mic works in Windows 11 but not in FerenOS, it worked before but maybe I touched the keyboard shortcut to disable /ename the microphone and the bottom stopped working, so now I can't enable the microphone again from UI (KDE).

I tried microphone test online and only record system sounds,

**Steps to Reproduce**
1. Try to speak by the mic.

**Expected behavior**
My My should work as it does in the Windows 11 side installed on the same computer, no it's not a hardware issue.

**Screenshots**

**Additional context**
amixer sset Capture toggle -D pulse

Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 65536 [100%] [off]
  Front Right: Capture 65536 [100%] [off]
achede@lenovo-feren:~$ 

Linux lenovo-feren 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by achede22** [comment]
SOLVED!

I installed pavucontrol
`sudo apt install pavucontrol`

then I ran it
`pavucontrol`

At the right tab click "Configuration"

on the device **Family 17h (Models 10h-1fh) HD Audio Controller** Select
`Analog Stereo DUPLEX`

And the microphone was enabled again.

**Comment by dominichayesferen** [comment]
Just for future reference, you can also select that through the right-side button above volume sliders in the volume area.
