### ISSUE TITLE
wine  never finishes download

### ISSUE THREAD

**Issue by OSourceuser** [feren-OS/Bug-Reporting-Center#293]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**
i recently installed feren os, updates downloaded just fine, but wine  package [has]) been only half downloaded for a full day, i do not even know where to go in the os to delete and try again.

I am new to feren, just came over from window7.

any help stoping and starting the process again would be appreciated.

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot_20221120_083310](https://user-images.githubusercontent.com/23056078/202905237-1d4d12b8-6c41-463a-a4cf-23bc73896805.png)

**Comment by dominichayesferen** [comment]
Try running an EXE and installing Wine via the prompt that appears.

Otherwise, this is #223.
