### ISSUE TITLE
unable to transfer files to Feren os

### ISSUE THREAD

**Issue by OSourceuser** [feren-OS/Bug-Reporting-Center#294]
I just reinstalled feren os, despite the disk  showing that there are over 400 gb of space, new folders i create only have 1.2 gb of space!

please see screenshots, the drive has plenty of space, so why can i not transfer my files above 1.2 gb  in collective or single size?

Please advise.

Thanks

![Screenshot_20221126_084355](https://user-images.githubusercontent.com/23056078/204092251-1840a921-9105-4362-9629-d12608f7f42c.png)
![Screenshot_20221126_084411](https://user-images.githubusercontent.com/23056078/204092253-9c9a4ad8-cf54-4cc0-a0d7-1662d4c0d861.png)
![Screenshot_20221126_085029](https://user-images.githubusercontent.com/23056078/204092254-fb01b45e-06bc-4a06-9054-6a1c2bf92a7b.png)

**Comment by dominichayesferen** [comment]
You're comparing the free space or what is either a partition or an external/secondary hard drive to your main Feren OS partition (or 'home partition' if you set a home partition up).

I'd need to see how you laid out your drive when installing, via a screenshot of Disks, before I can really understand what's going on here besides what I just said.

**Comment by OSourceuser** [comment]
Hello

 

Thanks for the reply, I switched over the linux mint, it is all good!
 

Muhammad Bey

Web:Muhammadbey.com

Linkedin:https://www.linkedin.com/in/muhammdbey/

Whatsapp 215-868-9932

 
 

Sent: Sunday, November 27, 2022 at 4:16 PM
