### ISSUE TITLE
switch your base to arch linux IMMEDIATE

### ISSUE THREAD

**Issue by Ardaninho** [feren-OS/Bug-Reporting-Center#297]
Acquire an installation image
Visit the [Download](https://archlinux.org/download/) page and, depending on how you want to boot, acquire the ISO file or a netboot image, and the respective [GnuPG](https://wiki.archlinux.org/title/GnuPG) signature.

Verify signature
It is recommended to verify the image signature before use, especially when downloading from an HTTP mirror, where downloads are generally prone to be intercepted to [serve malicious images](https://www2.cs.arizona.edu/stork/packagemanagersecurity/attacks-on-package-managers.html).

On a system with [GnuPG](https://wiki.archlinux.org/title/GnuPG) installed, do this by downloading the ISO PGP signature ([under Checksums in the page Download](https://archlinux.org/download/#checksums)) to the ISO directory, and [verifying](https://wiki.archlinux.org/title/GnuPG#Verify_a_signature) it with:

$ gpg --keyserver-options auto-key-retrieve --verify archlinux-version-x86_64.iso.sig

Alternatively, from an existing Arch Linux installation run:

$ pacman-key -v archlinux-version-x86_64.iso.sig
Note:
The signature itself could be manipulated if it is downloaded from a mirror site, instead of from [archlinux.org](https://archlinux.org/download/) as above. In this case, ensure that the public key, which is used to decode the signature, is signed by another, trustworthy key. The gpg command will output the fingerprint of the public key.
Another method to verify the authenticity of the signature is to ensure that the public key's fingerprint is identical to the key fingerprint of the [Arch Linux developer](https://archlinux.org/people/developers/) who signed the ISO-file. See [Wikipedia:Public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) for more information on the public-key process to authenticate keys.
Prepare an installation medium
The installation image can be supplied to the target machine via a [USB flash drive](https://wiki.archlinux.org/title/USB_flash_installation_medium), an [optical disc](https://wiki.archlinux.org/title/Optical_disc_drive#Burning) or a network with [PXE](https://wiki.archlinux.org/title/PXE): follow the appropriate article to prepare yourself an installation medium from the chosen image.
Boot the live environment
Note: Arch Linux installation images do not support Secure Boot. You will need to [disable Secure Boot](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Disabling_Secure_Boot) to boot the installation medium. If desired, [Secure Boot](https://wiki.archlinux.org/title/Secure_Boot) can be set up after completing the installation.
Point the current boot device to the one which has the Arch Linux installation medium. Typically it is achieved by pressing a key during the [POST](https://en.wikipedia.org/wiki/Power-on_self_test) phase, as indicated on the splash screen. Refer to your motherboard's manual for details.
When the installation medium's boot loader menu appears, select Arch Linux install medium and press Enter to enter the installation environment.
Tip: The installation image uses [GRUB](https://wiki.archlinux.org/title/GRUB) for UEFI and [syslinux](https://wiki.archlinux.org/title/Syslinux) for BIOS booting. See [README.bootparams](https://gitlab.archlinux.org/mkinitcpio/mkinitcpio-archiso/blob/master/docs/README.bootparams) for a list of [boot parameters](https://wiki.archlinux.org/title/Kernel_parameters#Configuration).
You will be logged in on the first [virtual console](https://en.wikipedia.org/wiki/Virtual_console) as the root user, and presented with a [Zsh](https://wiki.archlinux.org/title/Zsh) shell prompt.
To switch to a different console—for example, to view this guide with [Lynx](https://lynx.invisible-island.net/lynx_help/Lynx_users_guide.html) alongside the installation—use the Alt+arrow [shortcut](https://wiki.archlinux.org/title/Keyboard_shortcuts). To [edit](https://wiki.archlinux.org/title/Textedit) configuration files, [mcedit(1)](https://man.archlinux.org/man/mcedit.1), [nano](https://wiki.archlinux.org/title/Nano#Usage) and [vim](https://wiki.archlinux.org/title/Vim#Usage) are available. See [pkglist.x86_64.txt](https://geo.mirror.pkgbuild.com/iso/latest/arch/pkglist.x86_64.txt) for a list of the packages included in the installation medium.

Set the console keyboard layout
The default [console keymap](https://wiki.archlinux.org/title/Console_keymap) is [US](https://en.wikipedia.org/wiki/File:KB_United_States-NoAltGr.svg). Available layouts can be listed with:

# ls /usr/share/kbd/keymaps/**/*.map.gz
To set the keyboard layout, pass a corresponding file name to [loadkeys(1)](https://man.archlinux.org/man/loadkeys.1), omitting path and file extension. For example, to set a [German](https://en.wikipedia.org/wiki/File:KB_Germany.svg) keyboard layout:

# loadkeys de-latin1
[Console fonts](https://wiki.archlinux.org/title/Console_fonts) are located in /usr/share/kbd/consolefonts/ and can likewise be set with [setfont(8)](https://man.archlinux.org/man/setfont.8).

Verify the boot mode
To verify the boot mode, list the [efivars](https://wiki.archlinux.org/title/Efivars) directory:

# ls /sys/firmware/efi/efivars
If the command shows the directory without error, then the system is booted in UEFI mode. If the directory does not exist, the system may be booted in [BIOS](https://en.wikipedia.org/wiki/BIOS) (or [CSM](https://en.wikipedia.org/wiki/Compatibility_Support_Module)) mode. If the system did not boot in the mode you desired, refer to your motherboard's manual
Connect to the internet
To set up a network connection in the live environment, go through the following steps:

Ensure your [network interface](https://wiki.archlinux.org/title/Network_interface) is listed and enabled, for example with [ip-link(8)](https://man.archlinux.org/man/ip-link.8):
# ip link
For wireless and WWAN, make sure the card is not blocked with [rfkill](https://wiki.archlinux.org/title/Rfkill).
Connect to the network:
Ethernet—plug in the cable.
Wi-Fi—authenticate to the wireless network using [iwctl](https://wiki.archlinux.org/title/Iwctl).
Mobile broadband modem—connect to the mobile network with the [mmcli](https://wiki.archlinux.org/title/Mmcli) utility.
Configure your network connection:
[DHCP](https://wiki.archlinux.org/title/DHCP): dynamic IP address and DNS server assignment (provided by [systemd-networkd](https://wiki.archlinux.org/title/Systemd-networkd) and [systemd-resolved](https://wiki.archlinux.org/title/Systemd-resolved)) should work out of the box for Ethernet, WLAN, and WWAN network interfaces.
Static IP address: follow [Network configuration#Static IP address](https://wiki.archlinux.org/title/Network_configuration#Static_IP_address).
The connection may be verified with [ping](https://wiki.archlinux.org/title/Ping):
# ping archlinux.org
Note:
If the disk does not show up, [make sure the disk controller is not in RAID mode](https://wiki.archlinux.org/title/Partitioning#Drives_are_not_visible_when_firmware_RAID_is_enabled).
If the disk from which you want to boot [already has an EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition#Check_for_an_existing_partition), do not create another one, but use the existing partition instead.
[Swap](https://wiki.archlinux.org/title/Swap) space can be set on a [swap file](https://wiki.archlinux.org/title/Swap_file) for file systems supporting it.
UEFI with GPT
/mnt/boot /dev/efi_system_partition EFI system partition At least 300MiB
[SWAP] /dev/swap_partition Linux swap More than 512 MiB
/mnt /dev/root_partition Linux x86-64 root (/) Remainder of the device
[Other mount points](https://wiki.archlinux.org/title/EFI_system_partition#Typical_mount_points), such as /mnt/efi, are possible, provided that the used boot loader is capable of loading the kernel and initramfs images from the root volume. See the warning in [Arch boot process#Boot loader](https://wiki.archlinux.org/title/Arch_boot_process#Boot_loader).
BIOS with MBR
[SWAP] /dev/swap_partition Linux swap More than 512 MiB
/mnt /dev/root_partition Linux Remainder of the device
See also [Partitioning#Example layouts](https://wiki.archlinux.org/title/Partitioning#Example_layouts).

Format the partitions
Once the partitions have been created, each newly created partition must be formatted with an appropriate [file system](https://wiki.archlinux.org/title/File_system). See [File systems#Create a file system](https://wiki.archlinux.org/title/File_systems#Create_a_file_system) for details.

For example, to create an Ext4 file system on /dev/root_partition, run:

# mkfs.ext4 /dev/root_partition
If you created a partition for [swap](https://wiki.archlinux.org/title/Swap), initialize it with [mkswap(8)](https://man.archlinux.org/man/mkswap.8):

# mkswap /dev/swap_partition
Note: For stacked block devices replace /dev/*_partition with the appropriate block device path.
If you created an EFI system partition, [format it](https://wiki.archlinux.org/title/EFI_system_partition#Format_the_partition) to FAT32 using [mkfs.fat(8)](https://man.archlinux.org/man/mkfs.fat.8).

Warning: Only format the EFI system partition if you created it during the partitioning step. If there already was an EFI system partition on disk beforehand, reformatting it can destroy the boot loaders of other installed operating systems.
# mkfs.fat -F 32 /dev/efi_system_partition
Mount the file systems
Mount the root volume to /mnt. For example, if the root volume is /dev/root_partition:

# mount /dev/root_partition /mnt
Create any remaining mount points (such as /mnt/efi) and mount their corresponding volumes.

Tip: Run mount(8) with the --mkdir option to create the specified mount point. Alternatively, create it using mkdir(1) beforehand.
For UEFI systems, mount the EFI system partition:

# mount --mkdir /dev/efi_system_partition /mnt/boot
If you created a swap volume, enable it with swapon(8):

# swapon /dev/swap_partition
genfstab(8) will later detect mounted file systems and swap space.
Installation
Select the mirrors
Packages to be installed must be downloaded from mirror servers, which are defined in /etc/pacman.d/mirrorlist. On the live system, after connecting to the internet, reflector updates the mirror list by choosing 20 most recently synchronized HTTPS mirrors and sorting them by download rate.

The higher a mirror is placed in the list, the more priority it is given when downloading a package. You may want to inspect the file to see if it is satisfactory. If it is not, edit the file accordingly, and move the geographically closest mirrors to the top of the list, although other criteria should be taken into account.

This file will later be copied to the new system by pacstrap, so it is worth getting right.

Install essential packages
Use the pacstrap(8) script to install the base package, Linux kernel and firmware for common hardware:

# pacstrap -K /mnt base linux linux-firmware
Tip:
You can substitute linux for a kernel package of your choice, or you could omit it entirely when installing in a container.
You could omit the installation of the firmware package when installing in a virtual machine or container.
The base package does not include all tools from the live installation, so installing other packages may be necessary for a fully functional base system. In particular, consider installing:

userspace utilities for the management of file systems that will be used on the system,
utilities for accessing RAID or LVM partitions,
specific firmware for other devices not included in linux-firmware (e.g. sof-firmware for sound cards),
software necessary for networking (e.g. a network manager or DHCP client),
a text editor,
packages for accessing documentation in man and info pages: man-db, man-pages and texinfo.
To install other packages or package groups, append the names to the pacstrap command above (space separated) or use pacman while chrooted into the new system. For comparison, packages available in the live system can be found in pkglist.x86_64.txt.
Configure the system
Fstab
Generate an [fstab](https://wiki.archlinux.org/title/Fstab) file (use -U or -L to define by [UUID](https://wiki.archlinux.org/title/UUID) or labels, respectively):

# genfstab -U /mnt >> /mnt/etc/fstab
Check the resulting /mnt/etc/fstab file, and [edit](https://wiki.archlinux.org/title/Textedit) it in case of errors.

Chroot
[Change root](https://wiki.archlinux.org/title/Change_root) into the new system:

# arch-chroot /mnt
Time zone
Set the [time zone](https://wiki.archlinux.org/title/Time_zone):

# ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
Run [hwclock(8)](https://man.archlinux.org/man/hwclock.8) to generate /etc/adjtime:

# hwclock --systohc
This command assumes the hardware clock is set to [UTC](https://en.wikipedia.org/wiki/UTC). See [System time#Time standard](https://wiki.archlinux.org/title/System_time#Time_standard) for details.

Localization
[Edit](https://wiki.archlinux.org/title/Textedit) /etc/locale.gen and uncomment en_US.UTF-8 UTF-8 and other needed [locales](https://wiki.archlinux.org/title/Locale). Generate the locales by running:

# locale-gen
[Create](https://wiki.archlinux.org/title/Create) the [locale.conf(5)](https://man.archlinux.org/man/locale.conf.5) file, and [set the LANG variable](https://wiki.archlinux.org/title/Locale#Setting_the_system_locale) accordingly:

/etc/locale.conf
LANG=en_US.UTF-8
If you [set the console keyboard layout](https://wiki.archlinux.org/title/Installation_guide#Set_the_console_keyboard_layout), make the changes persistent in [vconsole.conf(5)](https://man.archlinux.org/man/vconsole.conf.5):

/etc/vconsole.conf
KEYMAP=de-latin1
Network configuration
[Create](https://wiki.archlinux.org/title/Create) the [hostname](https://wiki.archlinux.org/title/Hostname) file:

/etc/hostname
myhostname
Complete the [network configuration](https://wiki.archlinux.org/title/Network_configuration) for the newly installed environment. That may include installing suitable [network management](https://wiki.archlinux.org/title/Network_management) software.

Initramfs
Creating a new initramfs is usually not required, because [mkinitcpio](https://wiki.archlinux.org/title/Mkinitcpio) was run on installation of the [kernel](https://wiki.archlinux.org/title/Kernel) package with pacstrap.

For [LVM](https://wiki.archlinux.org/title/Install_Arch_Linux_on_LVM#Adding_mkinitcpio_hooks), [system encryption](https://wiki.archlinux.org/title/Dm-crypt) or [RAID](https://wiki.archlinux.org/title/RAID#Configure_mkinitcpio), modify [mkinitcpio.conf(5)](https://man.archlinux.org/man/mkinitcpio.conf.5) and recreate the initramfs image:

# mkinitcpio -P
Root password
Set the root [password](https://wiki.archlinux.org/title/Password):

# passwd
Boot loader
Choose and install a Linux-capable [boot loader](https://wiki.archlinux.org/title/Boot_loader). If you have an Intel or AMD CPU, enable [microcode](https://wiki.archlinux.org/title/Microcode) updates in addition.
Reboot
Exit the chroot environment by typing exit or pressing Ctrl+d.

Optionally manually unmount all the partitions with umount -R /mnt: this allows noticing any "busy" partitions, and finding the cause with [fuser(1)](https://man.archlinux.org/man/fuser.1).

Finally, restart the machine by typing reboot: any partitions still mounted will be automatically unmounted by systemd. Remember to remove the installation medium and then login into the new system with the root account.
Post-installation
See [General recommendations](https://wiki.archlinux.org/title/General_recommendations) for system management directions and post-installation tutorials (like creating unprivileged user accounts, setting up a graphical user interface, sound or a touchpad).

For a list of applications that may be of interest, see [List of applications](https://wiki.archlinux.org/title/List_of_applications).

**Comment by itsthedot** [comment]
yes

**Comment by itsthedot** [comment]
this guy is commiting le dishery

**Comment by Ardaninho** [comment]
the kids r reviewing Feren OS
