### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by johnmils** [feren-OS/Bug-Reporting-Center#299]
GPU PROBLEMS... HOW TO INSTALL THE DRIVER. AND SOFTWARE OF AMD R5??

**Comment by dominichayesferen** [comment]
Driver Manager is where you install 3rd-party drivers.

**Comment by johnmils** [comment]
I've already done it. And it works. But not all of my games will play on
this OS. Thanks. I'm trying steam is holoiso now.

**Comment by johnmils** [comment]
Thanks.
