### ISSUE TITLE
Virtualbox not showing up after being installed

### ISSUE THREAD

**Issue by ashleenaidoo** [feren-OS/Bug-Reporting-Center#3]
I installed the latest version of the OS, but cannot seems to find it. So i uninstalled, and installed via terminal to the older version and now it is working. This is a bug or not supported by the OS

**Comment by feren** [comment]
Which version of VirtualBox is this, VirtualBox 5.0 (repositories version) or VirtualBox 6.0 (VirtualBox Repositories version)?

**Comment by ashleenaidoo** [comment]
Hi team, This is for version 5.2 of Virtualbox from the store. After you install this from the terminal everything then works. Happy to assist with more info in need

**Comment by feren** [comment]
I installed the 'VirtualBox' item from Store which has a description of 'Qt-based User Interface' and that one installed an application shortcut into the applications menu automatically. Marking as 'Not Reproducable'...

**Comment by ashleenaidoo** [comment]
Weird, noted and thank you
