### ISSUE TITLE
UEFI Installation does not work offline

### ISSUE THREAD

**Issue by feren** [feren-OS/Bug-Reporting-Center#31]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) calamares, feren-calamares-global-settings

**Describe the bug**
On the EFI-only stage of installation, due to the Installation Medium only Repository for Feren OS not working the installation immediately fails when there's no internet access due to not being able to retrieve the GRUB package(s).

**Steps to Reproduce**
1. Install Feren OS without internet access
2. Wait for it to fail

**Expected behavior**
Feren OS installing GRUB successfully

**Additional context**
This bug is caused by inaccessibility to the Installation Medium's Local Repository.

**Comment by Mark-Peppermint** [comment]
Feren, email me about this .. I think I know what the problem is.
(mark@peppermintos.com)

**Comment by feren** [comment]
Fixed in Feren OS Next Release Candidate 1.

**Comment by feren** [comment]
Since this is for Feren OS in general, however, now it's fixed in Feren OS Next it'll be pulled out of that milestone so that it can be focused on as a general bug as well.

**Comment by feren** [comment]
This has been fixed in Feren OS December 2019 Snapshot and Feren OS Classic 64-Bit December 2019 Snapshot. :crossed_fingers:
