### ISSUE TITLE
Firefox does not import Bookmarks from html or json properly.

### ISSUE THREAD

**Issue by peterneedshelp** [feren-OS/Bug-Reporting-Center#322]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___Firefox

**Describe the bug**
A clear and concise description of what the bug is.  I tried to import Bookmarks from another laptop, but it did not produce the bookmarks accurately either from html or json. Only some of the bookmarks were imported.

**Steps to Reproduce**
1. 

**Expected behavior**
A clear and concise description of what you expected to happen. Full and accurate transfer of Bookmarks.

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
Yeah that just screams Mozilla Firefox issue, and not a Feren OS issue - consider reporting it to https://bugzilla.org instead.
