### ISSUE TITLE
Thunderbird has problems importing Profile

### ISSUE THREAD

**Issue by peterneedshelp** [feren-OS/Bug-Reporting-Center#323]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___Thunderbird

**Describe the bug**
A clear and concise description of what the bug is. Thunderbird would not import a profile because it is larger than 2gb.

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
That's a Thunderbird design issue - report it to https://bugs.launchpad.net/ubuntu/+source/thunderbird/+filebug instead.
