### ISSUE TITLE
How to repair bad sectors

### ISSUE THREAD

**Issue by peterneedshelp** [feren-OS/Bug-Reporting-Center#324]
**Package Name or Section of Feren OS where this bug resides**  Before cloning, it's best to repair any bad sectors in the ssd. How do you do this in Feren Os ?
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
Use Disks or install and use KDE Partition Manager to check the partition.
