### ISSUE TITLE
Hard Drive Space Loss

### ISSUE THREAD

**Issue by peterneedshelp** [feren-OS/Bug-Reporting-Center#326]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___Feren OS 4.0.10
4.15.0-213-generic

**Describe the bug**
A clear and concise description of what the bug is.  The hard drive seems to be losing space quite fast. How do you stabilise hard drive space loss or regain it ?

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dominichayesferen** [comment]
Feren OS 4.0.10? Can I have a screenshot of System Information?
