### ISSUE TITLE
Settings applcation crash

### ISSUE THREAD

**Issue by Dave6871** [feren-OS/Bug-Reporting-Center#327]
When I go to settings and than to appearance than application style settings will crash and I have to restart it. I expected the application style to load it does not. It did at first on installation. I can perform the same as above and it will always crash settings. 

Attached is log
[system settings 20241003-220621.txt](https://github.com/user-attachments/files/17252477/system.settings.20241003-220621.txt)

**Comment by dominichayesferen** [comment]
Please uninstall `dde-qt5integration` as it is not compatible.

**Comment by Dave6871** [comment]
Thanks for the reply and solution
