### ISSUE TITLE
Flatpak pinned message

### ISSUE THREAD

**Issue by Dave6871** [feren-OS/Bug-Reporting-Center#329]
When I use the command flatpak update this message pops up. I tried to use the remove pin option but it still returns the message.  

![Flatpak message](https://github.com/user-attachments/assets/b995eedd-0a20-41f8-947b-dcb4bb5f5828)

Thanks
Dave

**Comment by dominichayesferen** [comment]
Try `flatpak remove org.freedesktop.Platform.Icontheme.Adwaita//1.0`.

**Comment by Dave6871** [comment]
Solved
