### ISSUE TITLE
Updates Not Working

### ISSUE THREAD

**Issue by zaivala** [feren-OS/Bug-Reporting-Center#38]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
Update center, or using Terminal sudo apt update
**Describe the bug**
Feren repositories not found, unable to complete update. I have a screenshot...

from Terminal, 
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://gitlab.com/feren-os/feren-repositories-neon/raw/master stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECB89CBB3F1D7688
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECB89CBB3F1D7688
W: Failed to fetch https://gitlab.com/feren-os/feren-repositories-neon/raw/master/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECB89CBB3F1D7688
W: Failed to fetch https://gitlab.com/feren-os/feren-repositories/raw/master/repositories/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECB89CBB3F1D7688
W: Some index files failed to download. They have been ignored, or old ones used instead.
**Steps to Reproduce**
1. Run Update Manager

1. Terminal sudo apt update

**Expected behavior**

I expected it to run through the repos and determine what software needs to be updated, and then update it.
**Screenshots**
![Screenshot from 2019-07-02 07-53-04](https://user-images.githubusercontent.com/28702896/60511561-43efcc00-9ca0-11e9-94c5-97df1ff633f5.png)

**Additional context**

**Comment by feren** [comment]
https://ferenos.weebly.com/troubleshooting/fix-no_pubkey-on-the-feren-os-repositories

**Comment by zaivala** [comment]
Thank you for this. I have a new problem, which is probably someone else's issue. I completed installation of OpenMandriva Lx 4 on another partition. I had an issue, and attempted to reboot to Feren so I could (a) fix this issue in Feren and (b) report the other issue on their Forum. I got the message that "this [distribution] is too old" and had to reboot to something else. OM4 now has control of my GRUB, so I'm not sure how I go about wresting control back. I am learning a lot LOL.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zaivala** [comment]
Let me update that message. It reads: "Version too old for 32-bit boot. Try [forgot the words here] for 16-bit".

Why on earth is Feren reporting a 32-bit boot, or why on earth is the OM 4 bootloader finding it in this state? I will mention that I can successfully boot to Bodhi 5 (based on Ubuntu 18.04) and Linux Mint 19.1 (upon which Feren OS is based) from this bootloader.

Moss, aka Zaivala, aka MossHippoLinux.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zaivala** [comment]
At this point, the only way I can think of to get my boot back is to reinstall Feren OS. I'm sure there are others, but that is the simplest and will only take a couple hours (to install all my software after install, set Grub Customizer, install printer, etc.).

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by feren** [comment]
@zaivala Try doing a boot-repair from the Feren OS Live USB/CD?

**Comment by zaivala** [comment]
Reinstalling will let me know whether you fix the bug or not. Apparently not. So now I will go do the fix.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zaivala** [comment]
During updates, I am getting a lot of statements saying warning this will be broken in the future if the developer doesn't fix it. I hope you're on top of that issue whatever it is.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by feren** [comment]
???

**Comment by zaivala** [comment]
I literally have no clue, it just came up with that message.

Also, as of this morning, the LinuMint and feren repositories are failing their check using Update Manager.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by feren** [comment]
https://ferenos.weebly.com/troubleshooting/fix-no_pubkey-on-the-feren-os-repositories
