### ISSUE TITLE
Installer not removing old partitions

### ISSUE THREAD

**Issue by redbubble481** [feren-OS/Bug-Reporting-Center#40]
Feren installer. Feren os july snapshot.

It said it is unable to change msdos partition table 

1. install different linux. eg manjaro, arch, etc
2. start installer
3. select erase disk
4. watch as error message pops up.  

I expect the installer to finish installing

Sorry no screenshots did not think of that at the time.

I have seen this bug before on other installs with calamares.

I was not able to delete the partitions with fdisk. Fdisk said the partitions were in use. I was using the Feren os live installer when i used fdisk. Used a different linux os to delete the partitions.

**Comment by feren** [comment]
I think that's the sfdisk issue that Calamares knows about over at https://github.com/calamares/calamares/issues/1170. Can you confirm so I can mark this bug report as 'Upstream'?

**Comment by redbubble481** [comment]
Okay. Fair enough.

**Comment by redbubble481** [comment]
This looks like the problem in #1170
