### ISSUE TITLE
Bluetooth and wifi drivers crash periodically

### ISSUE THREAD

**Issue by alan-hub** [feren-OS/Bug-Reporting-Center#43]
Feren OS requires rebooting about once a day due to losing wifi connectivity.  Disconnecting and reconnecting wifi does not solve the issue.  

Also, using bluetooth headphones while watching video causes wifi to fail predictably in less than ten minutes.

Note, I am also using a bluetooth mouse during the above scenarios.

My laptop is a Dell INSPIRON 15-3567

**Comment by alan-hub** [comment]
Note also, after returning from sleep, about half the time, Feren does not detect the bluetooth adapter.  Rebooting corrects the problem.

**Comment by feren** [comment]
@alan-hub By chance, if you were to try a Linux Mint Live USB/DVD for that amount of time, does a similar issue happen there?

**Comment by alan-hub** [comment]
I haven't tried the Mint iso.  But I did try both Ubuntu 18.04 and 19.04, and similar things happen there too.

**Comment by feren** [comment]
Then you might want to report it there too.
