### ISSUE TITLE
Problem with e-mail

### ISSUE THREAD

**Issue by Morn07** [feren-OS/Bug-Reporting-Center#45]
I am having problems sending and receiving email with Thunderbird and Evolution programs. After account setups, i open Thunderbird and this is what i get:

 X-ClientId: 7E16561DDBE44611A0F8A7330ED34E51
request-id 782bdbb9-a87b-4fdf-8b0c-2867f4c16a8e
X-Auth-Error System.ArgumentNullException
X-OWA-Version 15.20.2199.21
X-FEServer DM5PR2201CA0062
X-BEServer DM5PR2201MB1434
Date:26/08/2019 00:00:30

Thank you for your help,
John

**Comment by feren** [comment]
I tried it myself and couldn't get an issue similar to this. It could however just be that I was testing on an ISO build that hasn't been released yet to update the Mint base to 19.2, so I'll let you know here when that new ISO update is released.

**Comment by Morn07** [comment]
Hello,
Good evening,
So my Hotmail.com account seems to be working just fine now. But it's my Comcast.net that still isn't working. Something with the IMAP and SMTP settings not connecting. And that's in Geary, Evolution and Thunderbird.

Thanks for your help.
John Harley




On Wed, Aug 28, 2019 at 7:23 PM, The feren OS Dev <notifications@github.com> wrote:

I tried it myself and couldn't get an issue similar to this. It could however just be that I was testing on an ISO build that hasn't been released yet to update the Mint base to 19.2, so I'll let you know here when that new ISO update is released.

**Comment by feren** [comment]
The aforementioned ISO update just got released, BTW.

**Comment by feren** [comment]
Marking it as those as I can't test with a Comcast account for obvious reasons

**Comment by Morn07** [comment]
The new ISO update. Should I do a fresh install tonight?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by feren** [comment]
You can always check from the Live Session using Geary first.

**Comment by feren** [comment]
Any success?
