### ISSUE TITLE
Dual monitor bug, KDE

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#46]
There is dual monitor bug every time its left go on lockscreen for while being away when booting back in the other monitor does not work. I'm pretty sure this is long-lasting bug in KDE since version 5.0.6 came out. Here is video i found from AJ
https://www.youtube.com/watch?v=S25XTiG4oRc&t=315s

If go in to /.local/share/kscreen/ and delete those files and logout i will have daulscreen again. But Feren welcome screen comes up again and the display thing.

I will check to see if Kubuntu does this aswell.

Thanks Feren OS Next it's lightweight very fast here :)

**Comment by feren** [comment]
Feren OS hasn't got an obvious kscreen configuration in the /etc/skel folder, so help'll probably be needed trying to find the source files that configs for this are generated from.

**Comment by tjw0lf** [comment]
OK so this is fixed I figured out what the issue was. It was my part I do not know what I thought but This is almost a Windows 10 thing in KDE :) I thought options it was giving to mirror on everyone but idk so because I choose the red X and picked nothing. It will keep coming up until you choose an option. so here is the basic dialog box

<a href="https://imgur.com/zE8dQ9c"><img src="https://i.imgur.com/zE8dQ9c.png" title="source: imgur.com" /></a>

1 X window - will set one screen to your right - only one monitor will be active
2 x window - will set one screen to your left - only one monitor will be active
3 is both monitors mirrored - whatever you do on one same for the other
4 panel will be on your right - display on left will be empty nobody else can see
5 panel will be on your left - display on right will be empty nobody else can see
Bottom two is normally what one's people use for streaming and recording set which side you want the panel on. ones this is set it won't pop up again and you can change to whatever you like in -system settings - display monitor

Hopefully, this helps people with dual screens. If anybody need help let me know

**Comment by feren** [comment]
Alright, marking this issue as 'User Error' and closing it.

**Comment by Kei84** [comment]
During the use of the Live Session, it automatically picks up the dual screen with out a problem, after install it mimics the primary screen on the second monitor. i have to go to Display configuration and change the layout of the display and save it after each reboot. this is not a user error.

**Comment by feren** [comment]
You might want to make a new issue about that.
