### ISSUE TITLE
mint is reference in update manager

### ISSUE THREAD

**Issue by ravi005e** [feren-OS/Bug-Reporting-Center#47]
**Steps to Reproduce**
1. look at screenshot, mint is referenced

**Expected behavior**
mint shouldn't be there

**Screenshots**

**Additional context**
![Screenshot_20190914_215201](https://user-images.githubusercontent.com/29851236/64916895-5de86900-d73d-11e9-8e03-37df65687987.png)

**Comment by ravi005e** [comment]
see updated screenshot
![Screenshot_20190914_221941](https://user-images.githubusercontent.com/29851236/64916918-0b5b7c80-d73e-11e9-88e3-bc3431a33c69.png)

**Comment by feren** [comment]
Removed the 'Feren OS Next' label as it affects standard Feren OS

**Comment by feren** [comment]
While this bug is confirmed, the reference to it in Software Sources is intentional.

**Comment by feren** [comment]
Alright, fixed the unintentional one (the Update Manager reference) just now, so I guess I'll mark this one as a Fixed and a Not A Bug issue.

**Comment by feren** [comment]
Anyway, I guess since both things in this issue were sorted out this issue is due for closure now.
