### ISSUE TITLE
Plasma Lock Screen doesn't accept no password for Live Session User sometimes

### ISSUE THREAD

**Issue by deafgeek** [feren-OS/Bug-Reporting-Center#48]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-plasma) ___
Start FerenOS Next Beta 2 in live session, then allow screen to time out and auto lock, then wake up computer then presented with login screen for live session, live and blank and mint and Live and password and Password does not work and pressing enter without entering anything in password box does not work, had to power off computer and restart then disable screen lock and restart install process

**Describe the bug**

**Steps to Reproduce**
1. burn FerenOS beta 2 to dvd or USB or download to iso and install to virtualPC
2. boot using the FerenOS beta 2, go into Try without installing
3. allow everything to load, then leave computer or virtual PC go idle then screen time out
4. wake up screen, see a dialog box for Live Session and password

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by feren** [comment]
That's a known issue that's very likely upstream. A workaround for this is to turn off Screen Locking in System Settings > Screen Locking so it doesn't lock on inactivity.

I'm planning on disabling auto-screen-locking by default on the Live Session at some point.

**Comment by feren** [comment]
Sorta fixed it by disabling the lock screen by default on the Live Session via a new package - `feren-plasma-live-adjustments` - so this issue should be resolved in Beta 3, hopefully.

**Comment by feren** [comment]
'Fixed' in Feren OS Next Beta 3. (Auto Screen Locking was turned off in the Live Session Feren OS Next)
