### ISSUE TITLE
Stable Feren install then multiple failures in software components after updates only recommendation reinstall.

### ISSUE THREAD

**Issue by MPN-stack** [feren-OS/Bug-Reporting-Center#49]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
After installing the latest update there was some problems with it not installing as chrome was open. After closing this and allowing latest update the Google Chrome window opens and closes without error
**Describe the bug**
Google Chrome will no longer open after update. It does not open to Workspace 1 to Workspace 4

**Steps to Reproduce**
1. Install latest Feren update 
2. Use the latest Google Chrome browser /home/martin/Downloads/google-chrome-beta_current_x86_64.deb

**Expected behavior**
Clicking the desktop icon Google Chrome should open up with a browser window instead it looked like it opens a white full screen which then disappears but does not open to any of the desktops.

**Screenshots**
Unfortunately the window opens and closes to quickly to photograph. But provide an image of updates:
![Screenshot from 2019-09-20 12-06-21](https://user-images.githubusercontent.com/54211372/65341870-627aaa80-db9f-11e9-9457-7d93a30b1fa7.png)

**Additional context**
Possibly this either needs an update to Feren window manager or an update to Google Chrome ? . It is odd that the update refused to execute with Google Chrome open suggesting a dependency issue

**Comment by feren** [comment]
Go into Terminal and run 'google-chrome-(your release channel here)' for some hopefully useful output. That might come in handy for me if you could do that.

**Comment by feren** [comment]
Also how come did you opt for the Google Chrome Beta Channel?

Pro Tip: Web Browser Manager

**Comment by feren** [comment]
Double also, is the use of an rpm file intentional or a typing error? Feren OS takes .deb files as packages, not .rpm files.

**Comment by MPN-stack** [comment]
Thank you for your messages I have tried the deb file to install this too. It is the first option I tried when it failed. Originally I  installed the one in the store  which is beta . When this last update installed Chrome was running and it gave an error stating it could not install update I quite Feren completely to get  it to install with no programs running. chrome wont run Additionally I am noting the Software update puts a dialog box up in regard to the repository which is too large for the screen and you can only leave by pressing exit. This happens when it cant locate the repository

**Comment by MPN-stack** [comment]
in terminal as directed to run google-chrome
pc:~$ google-chrome
[22802:22802:0921/053641.597208:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
[22802:22802:0921/053642.067650:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
Segmentation fault (core dumped)

**Comment by feren** [comment]
The repository issue can be fixed by removing the Google Chrome Unstable Repository in Software Sources.

Then you can install 'Google Chrome' from Store instead of google-chrome-beta or google-chrome-unstable...
Otherwise not sure, and also can't reproduce the Google Chrome issue.

As for Windows booting: Try rEFInd potentially if you can figure out how to get it running?

**Comment by MPN-stack** [comment]
I spoke to Google and sadly they had no-one who could help with Feren

**Comment by MPN-stack** [comment]
That is ridiculous Feren I might have to reset laptop and dump Feren then as its not working and support is hopeless. I had hoped this was better than Microsoft but it appears not at the moment!

**Comment by MPN-stack** [comment]
rEFInd not found on Feren

**Comment by MPN-stack** [comment]
Well I installed rEFind from store made no difference 

Cant find google uninstall in software repository. Infact its not very user friendly states it cant find the repository most of the time . There seems no options on it to remove software only upgrade. Currently as I type its sitting with a red X in the shield opening is just as pointless:

![Screenshot from 2019-09-22 14-24-30](https://user-images.githubusercontent.com/54211372/65392631-cf7b7500-dd44-11e9-8b04-93566854ee9e.png)

**Comment by feren** [comment]
Well to be fair you did install a repository when you installed Chrome Beta that wasn't installed by default. It's removable in "Additional Repositories" in Software Sources (remove all the Google ones but the 'stable' one).

**Comment by feren** [comment]
Also while you're at it you might as well remove all the Chrome's from your install followed by installing 'Google Chrome' from the Store or Web Browser Manager.

**Comment by MPN-stack** [comment]
Feren , To be fair I informed you that all of these problems started with your update at the source which caused Feren to not operate properly . I explained to you that this was noticeable as the update would not install when chrome was open stating the install would be aborted. 

It could be you do not have the Google Music App added to chrome that leads you not to replicate this .  I have no chromes at all currently

![Screenshot from 2019-09-23 04-05-09](https://user-images.githubusercontent.com/54211372/65410253-ddb6a900-ddb7-11e9-9f6a-0f62be6ba11c.png)

![Screenshot from 2019-09-23 04-08-01](https://user-images.githubusercontent.com/54211372/65410277-eb6c2e80-ddb7-11e9-9b5d-4fdad7d6c709.png)
![Screenshot from 2019-09-23 04-08-26](https://user-images.githubusercontent.com/54211372/65410285-f0c97900-ddb7-11e9-82fc-cb9448c34faf.png)

**Comment by MPN-stack** [comment]
Its seems now Feren has removed all wireless networking from this Operating System . I plugged in a wired connection yesterday and immediately lost the meter for WIFI connections on the lower bar which usually connects and was working in the past.  There doesn't seem to be a way of making it re appear here removal of the wired connection does not seem to reinstate it and leaves the laptop without internet wifi

**Comment by MPN-stack** [comment]
Despite removing chrome and repositories it is still on machine do you have a complete procedure for uninstalling chrome that works please as its not been removed?

**Comment by feren** [comment]
Given how many oddities are occuring, would it just be worth it to just reinstall Feren OS and then try installing Google Chrome via Web Browser Manager on the fresh install? Apologies.

**Comment by MPN-stack** [comment]
Dear Feren

I am not sure why I should have to re install Feren! This sounds like a support Microsoft useless helpline coment? 

This problem seems to be caused by your useless updates as it was working after install and failed during your updates  which have ruined this previously working system! 

I note in Feren it does not even have root access default which is ridiculous as its the same only password given at install. There seems no tool to change this login privilege under user account

I have installed WifiRadar in attempt to bypass Feren's not workable patched Wifi code  . I provide the terminal log :

About to execute /usr/sbin/wifi-radar.
This command needs root privileges to be executed.
Using sudo...
Enter MPN_Stack password at prompt.
[sudo] password for MPN_Stack:       
2019-09-26 06:50:14,725: get_network_device: No WiFi device found, please set this in the preferences.
2019-09-26 06:50:14,727: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:15,791: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:16,815: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:17,848: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:18,879: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:19,914: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:20,942: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:21,969: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:22,998: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:24,026: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:25,057: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:26,088: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:27,122: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:28,147: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:29,175: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:30,207: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:31,237: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:32,263: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:33,295: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:34,319: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

2019-09-26 06:50:35,346: get_network_device: No WiFi device found, please set this in the preferences.
up: error fetching interface information: Device not found
          Interface doesn't support scanning.

This was installed from the Store . on to this computer Acer Aspire E15 . When you go to Preferences the pull down menu to select your network  WIFI driver is unpopulated and default ticked. I note the network  tool still shows my WIFI network login information for WIFI but there seems to be no Feren WIFI Driver loaded on the system which was removed by just inserting a network cable!

**Comment by MPN-stack** [comment]
Can you please provide a Software dependency list for WIFI access on Feren. Can you please provide a process/ procedure  to gain root access to clean up this mess your updates have provided?

**Comment by feren** [comment]
I'm suggesting to reinstall for the following reasons:
1. You're looking at Chromium in the Store, not Chrome Beta, not Chrome Stable, etc. I don't think you understand that I'm meaning Chrome not Chromium. You installed an unstable version of Chrome, not Chromium and not Chrome Stable (also known as just 'Google Chrome' in the Store) which added a repository that isn't included by default in Feren OS.
2. This hasn't ever been something that has been known to have happened in here, and definitely not something I've intentionally done.
3. It should revert every single mistake that occured on your installation including WiFi being lost so you can get to updating it immediately to see if the problem occurs again.
4. None of the packages I've updated myself should affect internet connectivity, etc.
5. You can install Chrome properly (via Web Browser Manager or via the one called 'Google Chrome' in the Store) on attempt 2 rather than installing an unstable version of Chrome and then being left to wonder why it isn't working.

**Comment by feren** [comment]
As for rEFInd: Alright, I should've mentioned that that needs an external PPA to be added, apologies for failing to mention that. Chances are I might stick it in the 'software' repository sometime, though...

**Comment by MPN-stack** [comment]
Personally I am not getting much help . The original install of Feren to be honest is very good. 
However it seems on my device installing components from your store principally Google Chrome and then applying updates causes multiple problems to occur including Google Chrome browser to open a white window and halt run . **If you plug in a network cable this seems to remove all traces of your WIFI networking which cannot be repaired save the only advice given to reinstall .** I would imagine this is not to good news for everyone looking for a stable operating system.  This test was on a fairly new  Aspire E 15 laptop computer. Google Chrome was then tried to update from another repository which has not improved the problems on my device with Google Chrome on Feren OS.

**Comment by feren** [comment]
You installed Google Chrome **Beta** though, not Google Chrome from the Store.

**Comment by feren** [comment]
As for that other issue, it seems to be an upstream issue so unfortunately it doesn't seem like I can do much about it - the best that can be done for now is to report it upstream to Ubuntu if you also notice similar issues with Ubuntu 18.04 LTS.

As for the "Non-producable" part: That was for the initial issue - Google Chrome Beta not working.

**Comment by feren** [comment]
The correct Google Chrome to install from the Store identifies itself as "Google Chrome", not "Google-chrome-beta" or anything like that. Google Chrome Beta is an **unstable** product and is therefore bound to have issues with things.

**Comment by MPN-stack** [comment]
Yes Feren , If its a beta the why are you placing it in your store inferring its authorised and tried and tested? 
I told you (four days ago) which version I had installed that was working upuntil it was updated by your software update:
![Screenshot from 2019-09-26 07-10-50](https://user-images.githubusercontent.com/54211372/65684111-d4824200-e02c-11e9-99df-6f11ed0b5a24.png)

**Comment by feren** [comment]
Alternatively, there's a shortcut right to installing Chrome right in Web Browser Manager.

**Comment by feren** [comment]
AFAIK Google Chrome Beta only appears in the Store if you search for it. Package search, due to the MintInstall code, isn't something you can blacklist entries from appearing in.

However, the correct Google Chrome will frequently appear on the front page of the Store.

**Comment by feren** [comment]
Chromium =/= Google Chrome Stable
Google Chrome Beta =/= Google Chrome Stable

**Comment by MPN-stack** [comment]
Are you intentionally not reading any of my comments? And providing a support related suitable answer. Your only sensible answer to date is to reinstall with windows 10 !

**Comment by feren** [comment]
I am reading your comments, and I'm answering them honestly. You don't have to use Windows 10 to reinstall - as long as you still have your USB you can reboot into it again.

**Comment by MPN-stack** [comment]
There is plenty of information of what we installed and in what order onto the first stable install. Once your Update system started updating it has seemed to ruined this install creating these problems which you seem to not able to address or resolve. This matter of networking failures is addressed on your reporting centre on another thread and likewise ignored and has a closed thread. This devices  Feren install is on two desperate partitions there was a healthy windows 10 install on other that since installing Feren on new partition windows 10  is not accessible and has appears corrupted by the failure of the updates to your boot manager up  the Feren boot manager.

**Comment by feren** [comment]
As for rEFInd when you've got a working OS, do this:
```
sudo apt-add-repository ppa:rodsmith/refind
sudo apt-get update
sudo apt-get install refind
```

**Comment by feren** [comment]
@MPN-stack Before you go:
- Go back into the Live Session and don't forget to run Boot Repair after removing Feren OS if you remove it.

**Comment by MPN-stack** [comment]
**Stable Feren install then multiple failures in software components after updates only recommendation reinstall.**

There is plenty of information of what we installed and in what order onto the first stable install. Once your Update system started updating it has seemed to ruined this install creating these problems which you seem to not able to address or resolve. This matter of networking failures is addressed on your reporting centre on another thread and likewise ignored and has a closed thread. This devices  Feren install is on two desperate partitions there was a healthy windows 10 install on other that since installing Feren on new partition windows 10  is not accessible and has appears corrupted by the failure of the updates to your boot manager up  the Feren boot manager.

I am going to reinstall Windows 10 as clearly you are not providing any support for Feren in this matter to resolve the faults.

**Comment by feren** [comment]
As for rEFInd when you've got a working OS, do this:
```
sudo apt-add-repository ppa:rodsmith/refind
sudo apt-get update
sudo apt-get install refind
```

**Comment by feren** [comment]
@MPN-stack Before you go:
Go back into the Live Session and don't forget to run Boot Repair after removing Feren OS if you remove it, so you needn't worry about GRUB getting in the way.

**Comment by feren** [comment]
After all, Windows 10 might still be working fine if you reinstall its bootloader.

**Comment by feren** [comment]
As for "lack of support"... Hmm yeah seems legit. I wonder what other people'll think if they look in the comment history... Well at least I tried.
