### ISSUE TITLE
update manager, software sources  

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#51]
I reinstalled Feren OS Next. And the update manager is not launching in panel and software sources not launching when I click on it in the KDE menu at all.  How do i fix this? 

it came up when I Live stream it with you last month.

**Comment by feren** [comment]
Could you go in a Terminal and see what 'mintupdate' does output-wise?

**Comment by tjw0lf** [comment]
OK, thanks. well synaptic package manager isn't installing things as well it just hangs i don't remember it doing it before. I'm going to try and redo the USB stick first may be bad write

**Comment by feren** [comment]
That's very weird output for 'mintupdate' to do, telling you in Terminal:
```
OK, thanks. well synaptic package manager isn't installing things as well it just hangs i don't remember it doing it before. I'm going to try and redo the USB stick first may be bad write
```

Jokery aside, wanna check what the output is in Terminal?

**Comment by tjw0lf** [comment]
Why did the chickens cross the road?  'chickens didn't like FerenOS' LOL

I was just saying that happened as well. I did say i was going to try redo the USB stick.

**Comment by tjw0lf** [comment]
I rewrite the ISO to USB and it works now. it was bad write i guess. updates work software sources work.

**Comment by tjw0lf** [comment]
even my USB stick doesn't like you FerenOS 

Just joking :) :+1:

**Comment by feren** [comment]
Closing since you said it got 'fixed'. Also marking as 'User Error' since bad writes falls under that.
