### ISSUE TITLE
unable to get Virtualbox working

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#52]
I tried VirtualBox 6.0 and when I try to open it it just imminently crashes.

then I tried Virtualbox 5.23 and it won't loud modprobe vboxdrv to the kernel for some reason. I updated the kernel to the newest one kernel 5.2.3. I'm running. 

Not sure how to get it to work?

**Comment by feren** [comment]
Does VirtualBox provide any output if run via Terminal that'd be helpful to me? Just asking as VBox has always worked for me on 6 so I can't reproduce the issue myself.

**Comment by tjw0lf** [comment]
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (5.3.4-050304-generic) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /sbin/vboxconfig

         You will not be able to start VMs until this problem is fixed.
Qt WARNING: Icon theme "gnome" not found.
Qt WARNING: Icon theme "gnome" not found.
Illegal instruction (core dumped)

This is what I get when I do virtualbox in terminal. not sure why it won't load with this kernel.

i upgraded kernel again to see if it would work and same results.
[vbox-setup.log](https://github.com/feren-OS/Bug-Reporting-Center/files/3693715/vbox-setup.log)

here is the vbox log

**Comment by feren** [comment]
Ah, right, you can fix it by typing this in Terminal:
`sudo /sbin/vboxconfig`

**Comment by feren** [comment]
Gonna mark it as 'Upstream' as I'm quite sure at this point this might be more of an upstream issue with the official VirtualBox 6 Repo's VirtualBox 6.

**Comment by tjw0lf** [comment]
> Ah, right, you can fix it by typing this in Terminal:
> `sudo /sbin/vboxconfig`

I have done this multiple times. and it won't load into the kernel I'm using. It just gives ERROR. I'm not sure how to fix it with kernel 5.3.4

**Comment by feren** [comment]
...Kernel 5.3.X isn't an officially supported Feren OS Kernel version. Feren OS Next runs on Linux 5.0.X where VirtualBox seems to work fine after running `/sbin/vboxconfig`. Try downgrading your kernel to one officially supported.

**Comment by feren** [comment]
VirtualBox has to first update it to make it support the new kernels as they come, as far as I know, meaning updates have to be tested and then released by VirtualBox... I'll check if VirtualBox has an update since its last repository sync after I've finished with a KDE neon Repo Sync.

**Comment by feren** [comment]
If there has been an update in Update Manager for VirtualBox 6, you can try that new version, otherwise I don't know as it's therefore on the latest VirtualBox provided directly by a package from VirtualBox's own repositories.

**Comment by tjw0lf** [comment]
Ok Thanks feren. I get it now it's on VirtualBox Oracle side then. I just did a quick search on google and they haven't officially released for kernel 5.3 yet. That kinda sucks I think Virtualbox should be releasing for newer kernels daily.
