### ISSUE TITLE
Allow users to select language and keyboard layout while booting to the Live Session from EFI

### ISSUE THREAD

**Issue by jallain9** [feren-OS/Bug-Reporting-Center#55]
Keyboard layout prior to install is set to English (UK)

My wifi pasword contains the "@" sign. I could not sign on to my laptop's wifi so that I could proceed with the installation. I discovered that the keyboard layout was set for English (UK). The shift-2 key would issue the (") double quotes preventing me from logging on to my wifi.

Once I added the English (US) layout to the keyboard my keyboard then functioned normally for the US.

**Comment by feren** [comment]
Was this an EFI Boot or a Legacy Boot?

**Comment by feren** [comment]
Also SHIFT+' on the UK Keyboard Layout = @, FYI.

**Comment by feren** [comment]
Ah, right, that's a known thing, then. Limitations with a basic GRUB environment, unfortunately... for now anyway.

If you do a Legacy Boot and press ENTER on the first logo you'll get the option to set the language, keyboard layout, etc before you boot up.
I might look into Manjaro's GRUB configuration sometime into the future after Feren OS Next is released, though, for making the experience better for EFI.

**Comment by feren** [comment]
WIP
![image](https://user-images.githubusercontent.com/11057934/71643829-56ca7400-2cb6-11ea-9784-ee574e936b79.png)

**Comment by feren** [comment]
Fixed in January 2020 Snapshot ISOs.
