### ISSUE TITLE
Flatpak Blender

### ISSUE THREAD

**Issue by swoopa** [feren-OS/Bug-Reporting-Center#56]
**Blender Flatpak (Store)**
In Software Store, installing Blender Flatpak

**Error While trying to install Blender Flatpak**
The error states, While trying to apply extra data:runtime/org.freedesktop.Platform/x86_64/19.08 not installed
**Steps to Reproduce**
1. Install Blender flatpak
![Screenshot_20191025_195904](https://user-images.githubusercontent.com/25865515/67569632-f53fd380-f761-11e9-87ea-185ef0a93a21.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by feren** [comment]
I swear Mint fixed this upstream by making it ignore those errors... sigh... TBF Store was pending a base update sometime... I'll do it after preparing #11

**Comment by feren** [comment]
This was fixed in Feren Store 2019.11.0.0.0
