### ISSUE TITLE
Double Title Bar Vivaldi

### ISSUE THREAD

**Issue by swoopa** [feren-OS/Bug-Reporting-Center#57]
**Vivaldi**
On the title bar of Vivaldi
**Describe the bug**
There seems to be a doubled up title bar, especially the Close, Minimize and maximize buttons when using the Qogir Dark GTK3 Window decoration

**Steps to Reproduce**
1. Set the Qogir Dark GTK3 as the window decoration

**Expected behavior**
It doubles up the title bar on the Vivaldi Web Browser
![Qogir-Dark-Double-title-Bar-Vivaldi](https://user-images.githubusercontent.com/25865515/67570476-13a6ce80-f764-11e9-99c2-dceee536f520.png)

**Screenshots**

**Additional context**

**Comment by feren** [comment]
Go into System Settings > Other > Window Rules > Shadow Fix > Edit > Appearance (or Fixes, I forget which tab since I'm not at my computer right now) > Hide Window Decorations > Force -> Do Not Affect > Save

**Comment by feren** [comment]
Once I've put Plasma 5.17 in Feren OS, I'll make a patch for Window Decorations to make this process happen automatically like it does in Look & Feel.

Also you'll need to reload Vivaldi once you've made the changes.

**Comment by feren** [comment]
This was fixed in a Window Decorations patch package release.
