### ISSUE TITLE
Text is too dark to read on graphical login screen

### ISSUE THREAD

**Issue by ferenbreath** [feren-OS/Bug-Reporting-Center#58]
When you click the button to change the desktop environment on the login screen, the options are difficult to read as they display as black text with a dark highlight. (Think the text is white on Linux Mint). Also the back arrow button is not properly visible as it is shown as just a white box.

**Comment by feren** [comment]
That's a Feren OS GTK Issue. I'll fix it during the Feren OS GTK Theme Redo after I'm done with Feren OS Next as it isn't an issue wanting immediate action. For now you can work around it by installing the Linux Mint Theme and then changing the GTK Theme to a Mint-Y variant in Login Window.

**Comment by feren** [comment]
Fixed it in the new WIP Feren OS GTK Theme, pending release in the future.

**Comment by feren** [comment]
Fixed.
