### ISSUE TITLE
SDDM? Theme

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#60]
I figured it out. I wanted the SDDM theme I had before when I did my live stream. You took it out for lightdm WHY? SDDM is awesome in KDE. I uninstalled lightdm and installed sddm and your config but when log out its all white. I figured it out it was missing login pic from feren-os folder so I copied it from images back to feren-os folder in /usr/share/feren-os and sddm theme working for me now

**Comment by feren** [comment]
This change was made in Beta 4. The reasons for the change are listed on https://medium.com/feren-os/feren-os-next-final-beta-has-just-landed-e3b12acfa19c.

Quote:
> There are multiple reasons for this change, including:
> - LightDM starts logging into users, and takes you to the powering off screen when powering off from a logged in session, faster than SDDM
> - LightDM can directly unlock Plasma sessions just by logging into currently logged into users from the login screen, while SDDM can’t unlock the Plasma session directly and has a short wait as Plasma realises a session is already running as a user and switches the user, most of the time, to that running session
> - As slightly hinted to above, SDDM has weird behaviour where it starts a new session when logging into an already logged in user. LightDM always switches the user to their running session in this case, however, meaning there is less confusion.
> - In SDDM, if you are to switch user, log into another user, switch back to the first user and log the first user out you won’t be returned to either the login screen or the remaining user, but instead be put on the empty text-based shell that that session was running in.

SDDM may return in the future as the default Display Manager if they manage to sort out these issues with SDDM upstream. For now, however, Feren OS has reverted to using LightDM Slick Greeter and may fork Ubuntu Kylin Greeter in the future to provide an official Feren OS LightDM Greeter.

**Comment by feren** [comment]
Now that that's explained, I'll get to the part where I say this issue isn't a bug report so it'll be closed and marked as Invalid.

**Comment by feren** [comment]
Although, if you make a new issue about the currently unused SDDM theme having the wrong background URL, I'll keep that issue open for sure until I fix that.

**Comment by tjw0lf** [comment]
SDDM is fine for me feren? Where did you put that? on your site i didn't see it!.  Either one works for me I'm glad you keept them both in the repo for users who do like SDDM.

You should make fancy greeter for lightdm like the SDDM was.

Also you forgot to put lightdm-gtk-greeter-settings IN... 

WOW BETA4 WOW How long was i away NICE JOB FEREN
