### ISSUE TITLE
Update failed for Kernel? Broken packages 

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#61]
Feren stop braking stuff! LOL J/K

There where updates that came through and failed with kernel. How do i fix

It keeps telling me to fix broken packages but it always errors

**Comment by tjw0lf** [comment]
You have mixed kernels Feren WHY? Coming down its not playing nice. there's an hwe kernel in the updates? i think you grabbed the wrong one. wont install with generic others.

**Comment by feren** [comment]
There's a new RC that just released. Try that.

**Comment by tjw0lf** [comment]
There was still hwe kernel coming through that shouldn't have. Not sure why. 

Also i see you removed the blur effect. How do i get it back in. That wasn't really necessary was it? ALL you have to do is turn the blur strength down. Problem fixed. You had it up way to high Feren LOL what you trying to do. I don't think i can see you with that up so high :+1:

**Comment by feren** [comment]
Ubuntu.
