### ISSUE TITLE
No system Sounds in VM

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#62]
There are no system sounds at all Log in shutdown in virtualbox with Feren OS Next. I'm not sure how to fix it if you know how to fix it Feren. Thanks you

**Comment by feren** [comment]
A new RC has been released. Try it out and see if your issues still persist. https://medium.com/feren-os/feren-os-next-release-candidate-2-has-arrived-cb50429414ad

**Comment by tjw0lf** [comment]
Sound Works now.
