### ISSUE TITLE
building deepin-music 18.04 Feren OS Next

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#63]
I'm trying to build deepin-music player in your KDE Next? I have done it with xubuntu 19.04 and Kubuntu 19.10. and it works fine

every time i try and compile deepin-music with the required packeges. Feren-KDE-Next crashes the whole KDE and i have to do a whole reinstall. I'm doing this in virtualbox this is very odd and weird to me as it shouldn't be crashing anything? I'm going to try it on Kubuntu 18.04 i will know for sure

**Comment by feren** [comment]
First of all, why would you want to build it when you can get it from Welcome Screen > Install Software > Snap Apps?

Secondly, you've tried building it thus far on newer package bases... Ubuntu 18.04's package base might be a part of a problem during this.

**Comment by tjw0lf** [comment]
Your first answer feren. Snap is very old for Deepin Music And is outdated. Looks ugly 

I tried building it on Kubuntu 18.04. And it doesn't build as well. But I'm able to login on Kubuntu afterwards without the whole plasma crashed black screen on Feren OS Next when i try build it using the requested Depends after reboot the whole plasma crashes which shouldn't be happening just by building package? That's why i really do not like 18.04. Hopefully Mint will go to 19.04 at least won't have to wait long. I just think 19.04 is better more stable. The only downside is the android stuff you have installed my not work anymore. 

anyway you can count this as, Ubuntu issue

**Comment by feren** [comment]
What were the build dependencies?

**Comment by tjw0lf** [comment]
`Build-Depends: debhelper,  python, pkg-config, qttools5-dev-tools,
 libqt5svg5-dev, qtmultimedia5-dev,
 libtag1-dev, libicu-dev, libcue-dev,
 libavutil-dev, libavformat-dev, libavcodec-dev,
 libdtkwidget-dev`

`Depends: ${shlibs:Depends}, ${misc:Depends},
 gstreamer1.0-libav, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good,
 gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-pulseaudio,
 libqt5sql5-sqlite, libqt5multimedia5-plugins, gstreamer1.0-fluendo-mp3,
 gvfs-bin`

Also here is the bug i was referring to with the snap.
https://github.com/linuxdeepin/deepin-music/issues/53

They also used older version of the release. I tried to build 5.0.1 release as snap but it failed on 18.04 and 19.04. I'm not sure if i did it right building snap i don't know what i'm doing with snaps.

**Comment by feren** [comment]
I'll hold this issue for now until I've released Feren OS Next. Once that's done, I'll come back to this issue in due time.

**Comment by feren** [comment]
Is this issue still happening?

**Comment by tjw0lf** [comment]
YES. this will always be an issue on 18.04 releases of LTS. due to older package management. Once 20.04 LTS comes out it should compile.

**Comment by dominichayesferen** [comment]
Does this issue still occur in Feren OS November 2020 Snapshot?

**Comment by tjw0lf** [comment]
I'm attempting to check this once i get Feren OS 20.04 installed. I will let you know thanks for your hard work.

**Comment by tjw0lf** [comment]
well the deepin music will not build for me now at all in Feren OS. But it doesn't break anything after restart like it did before in KDE on 18.04 so thats good thing. i don't know what i'm missing to build this? Feren OS Dev maybe you can try? I tried different versions not sure!!!.

**Comment by tjw0lf** [comment]
There new deepin player from deepin 20 is OK but the lyrics part don't work why have lyrics button if your not going to make it work @Deepin Devs. I kinda switched music players i found cool one it looks almost like itunes
