### ISSUE TITLE
Packages needs fixing Feren?

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#64]
The following packagers have been kept back
feren-meta-os-plasma-system

wont upgrade, This is big problem dude What are you doing you sure like to just throw packages in whatever feren LOL

**Comment by feren** [comment]
What happens if you try to 'sudo apt install feren-meta-os-plasma-system'?

**Comment by feren** [comment]
Because if it complains about kde-config-tablet, I'm pretty sure if you manually install 'kde-config-tablet' it'll suddenly be fine for some reason.

**Comment by tjw0lf** [comment]
yep that's what i did all good now

**Comment by tjw0lf** [comment]
hey Feren how did you get the software sources to open up with mintupdate? I got it installed on Xubuntu 18.04 and says somthing about LSB wrong codename how do i get it to launch what i'm i'm missing if you can help. Thanks Awesome Feren Dev

**Comment by feren** [comment]
1. Feren OS mods mintupdate to adjust a few things towards the Feren OS Repository Structure
2. ferensources-ubuntu is a modded mintsources. To add LSB codenames to the list of supported codenames copy any folder named after a Linux Mint codename that matches with your Ubuntu base version to a new folder in there named after your Ubuntu base version's codename. (e.g.: tina -> bionic)

**Comment by tjw0lf** [comment]
I know you made plenty of mods :+1: 

What do you mean copy any folder to new folder. Where and where at in. I tried to look at yours i didn't see anything else? I have everything installed.

**Comment by feren** [comment]
e.g.: Copy /usr/share/mintsources/tina -> /usr/share/mintsources/bionic

**Comment by tjw0lf** [comment]
I did that i got a traceback error from  mintSources.py and something else. Oh well. i will just wait till there on 20.04

**Comment by feren** [comment]
The latest mintSources needs mintcommon, IIRC.

**Comment by tjw0lf** [comment]
IIRC?

**Comment by feren** [comment]
If I recall correctly.

**Comment by tjw0lf** [comment]
What do you mean Feren by IIRC?

**Comment by feren** [comment]
https://github.com/feren-OS/Bug-Reporting-Center/issues/64#issuecomment-561129751

**Comment by tjw0lf** [comment]
What do you mean Feren by IIRC? Your not making any sense DUDE

**Comment by feren** [comment]
https://github.com/feren-OS/Bug-Reporting-Center/issues/64#issuecomment-561129751

**Comment by tjw0lf** [comment]
Feren can you help me pull the lightdm greeter from deepin 20. How would i do that if you can help

**Comment by feren** [comment]
IDK currently
