### ISSUE TITLE
Simple Menu should have tooltips on the power buttons

### ISSUE THREAD

**Issue by dominichayesferen** [feren-OS/Bug-Reporting-Center#65]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-plasma) plasma-applet-simplemenu

**Describe the bug**
When hovering over the power buttons in Simple Menu, there's no useful tooltip to state what the button does.

**Steps to Reproduce**
1. Hover over a power button in Simple Menu

**Expected behavior**
A locale-translated tooltip will appear stating what the power button does

**Additional context**
Reported on behalf of Raman Sarda

**Comment by feren** [comment]
Yeah not really sure about this one either.

**Comment by dominichayesferen** [comment]
This won't be fixed as Feren OS is planned to get a new default menu in the Plasma 5.21 update. Once that menu arrives, this issue will be closed.

**Comment by dominichayesferen** [comment]
Simple Menu is no longer present after the KDE Plasma 5.21 update, so this issue will now be closed.

Subsequently, this was addressed in its replacement menu.
