### ISSUE TITLE
Editing an application doesn't automatically hide Simple Menu

### ISSUE THREAD

**Issue by dominichayesferen** [feren-OS/Bug-Reporting-Center#66]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-plasma) plasma-applet-simplemenu

**Describe the bug**
When you hit 'Edit Application' after right-clicking on an application in Simple Menu, the menu doesn't automatically close to get out of your way.

**Steps to Reproduce**
1. Open Simple Menu
2. Right-click any application
3. Hit 'Edit Application'

**Expected behavior**
Simple Menu will hide itself while you edit that application

**Screenshots**
![image](https://user-images.githubusercontent.com/11057934/69495187-10fedc80-0ebc-11ea-8120-2fbb27cd5842.png)

**Additional context**
Reported on behalf of Raman Sarda

**Comment by feren** [comment]
Alright, I tried looking for a fix for it, and... I'm stumped. It seems that in the code the 'Edit Application...' context menu trigger code is the same piece of code as everything else on the context menu, which means that it's either have every single menu option make the menu close or leave it as-is. I guess I'll just leave it to the Plasma developers to sort out if no one else tries it before those people.

**Comment by dominichayesferen** [comment]
Same as #65.

**Comment by dominichayesferen** [comment]
Simple Menu is no longer present after the KDE Plasma 5.21 update, so this issue will therefore be closed.

Subsequently, this bug doesn't occur on the replacement menu.
