### ISSUE TITLE
'Mint' needs to be removed.

### ISSUE THREAD

**Issue by twodogsdave** [feren-OS/Bug-Reporting-Center#67]
I'm trying "Feren OS' for the first time.  I like it and I have found some issues.

Open a terminal.  Title bar says 'mint@mint.'  Should be 'feren@feren.'
Issue command `uname -a` and it says 'Linux Mint.'

Open Nemo file manager.  Says 'Mint' on the first 'breadcrumb.'  Should say 'Feren.'

Missing volume icon on Cinnamon panel.  It's there, you just can't see it.

That's it for now.

**Comment by feren** [comment]
Because of the fact that Feren OS Classic will not be available in Ubuntu 20.04-based Feren OS and later, and the fact that this is not an issue in Feren OS (only is an issue in Feren OS Classic), I unfortunately won't be fixing this issue.
