### ISSUE TITLE
grub-install fails because modinfo.sh is missing for 64-Bit EFI

### ISSUE THREAD

**Issue by Anonymo** [feren-OS/Bug-Reporting-Center#68]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-plasma) feren-calamares-global-settings
Calamares installer when trying to install grub

**Describe the bug**
Halts the installation from Livcd

**Steps to Reproduce**
1. Try to install FerenOS Next from Release Candidate 2
2. Mine is a UEFI installation, I ran all the options, changing to English US, Erase the whole disk and begin install.
3.  It stops at trying to install grub.

**Expected behavior**

Expect it to install the OS

**Screenshots**
![Screenshot_20191206_104202](https://user-images.githubusercontent.com/967787/70340002-8ac88b80-1815-11ea-946f-eaf79eda9c2b.png)

https://imgur.com/a/cn6A5ro

**Additional context**

**Comment by feren** [comment]
How did you install Feren OS Next? With or without an internet connection?

**Comment by feren** [comment]
I've found out why this is probably happening and I'll release an update to feren-calamares-global-settings to make sure the missing packages are installed automatically followed by an ISO update for Next RC2 to include these fixes.

**Comment by feren** [comment]
Alright, the ISO and the package were both updated so this issue should be fixed in the newest iteration of the Next RC2 ISO. Marking this as 'Fixed'...

**Comment by feren** [comment]
False alarm, I'll

**Comment by feren** [comment]
Alright THIS TIME it's definitely fixed in the latest Next RC2 ISO update that was released a few minutes ago.
