### ISSUE TITLE
Installation Error: apt-cdrom unable to stat mount point /media/cdrom/

### ISSUE THREAD

**Issue by ApertureDevelopment** [feren-OS/Bug-Reporting-Center#69]
**Package Name or Section of Feren OS where this bug resides**
During the installation process of the 2019 July Snapshot

**Describe the bug**
I am trying since 2 hours to install FerenOS on my PC and in a VM but both fail with the error message `apt-cdrom unable to stat mount point /media/cdrom/` I am trying to install feren OS in a MBR enviroment, but I dont think that is the issue.

**Steps to Reproduce**
1. Insert the 2019 July Snapshot
2. Start the installation process in a MBR enviroment
3. At about >50% the error message appears

**Expected behavior**
A installation process without interupptions.

**Screenshots**

![image](https://user-images.githubusercontent.com/16450982/70755445-21c3a500-1d3a-11ea-9c9b-d3a194ad768f.png)

**Comment by Scott-A-T** [comment]
I've been getting a similar issue when trying to install it on bare metal.

![Screenshot_20191210_195203](https://user-images.githubusercontent.com/58492880/70756456-d2f61b00-1cf9-11ea-87f0-2a1eb982dd79.jpeg)

**Comment by feren** [comment]
What did you use to write your USB/DVD?

**Comment by feren** [comment]
Furthermore, what VM software was used for the VM and what version was it? (e.g.: VirtualBox 6.0)

**Comment by feren** [comment]
Thirdly, can you access /cdrom in the Live Session?

**Comment by feren** [comment]
Ah, I think I've figured out why this happens. I'm going to release an update to feren-calamares-global-settings now to include a potential fix to this. Thanks for reporting this issue.

**Comment by feren** [comment]
...and pushed. @ApertureDevelopment @Scott-A-T can you do the following in the Live Session, please?

1. Open a Terminal
2. Run `sudo apt update`
3. Run `sudo apt install -y feren-calamares-global-settings`
4. Run Calamares again (if it's running close it and open it again)
5. Install Feren OS as usual

If it installs correctly now, please let me know.

**Comment by Scott-A-T** [comment]
It worked; it now installed fine! Great job!

Scott

**Comment by Anonymo** [comment]
After using above steps to upgrade feren-calamares-global-settings, I'm getting this:

![image](https://user-images.githubusercontent.com/967787/70846654-40509b80-1e21-11ea-93de-74afad4b360e.png)

I let the disk manager setup the disk for me.

**Comment by ApertureDevelopment** [comment]
Works for me too, now just to find out what to do with grub

**Comment by feren** [comment]
Just updated it again, try the steps again @Anonymo

**Comment by Anonymo** [comment]
Got the same error, not sure if I'm supposed to disable secure boot.

**Comment by feren** [comment]
@Anonymo Did you `sudo apt update` and `sudo apt install -y feren-calamares-global-settings` again?

**Comment by Anonymo** [comment]
> @Anonymo Did you `sudo apt update` and `sudo apt install -y feren-calamares-global-settings` again and then relaunched Calamares?

yes I did.

**Comment by feren** [comment]
Was the error any different to last time?

**Comment by Anonymo** [comment]
looked the same to me

**Comment by feren** [comment]
When you 'install' feren-calamares-global-settings does it say it's at 2019.12.0.0.3?

**Comment by Anonymo** [comment]
I'll check in a bit.

**Comment by Anonymo** [comment]
![image](https://user-images.githubusercontent.com/967787/70851989-c2f94b00-1e61-11ea-9ef5-bbfadb13724a.png)
Looks like it is updating it to the latest.

**Comment by feren** [comment]
Now try relaunching Calamares and try installing again.

**Comment by Anonymo** [comment]
Tried again, no luck.

**Comment by Anonymo** [comment]
![IMG_20191214_131723](https://user-images.githubusercontent.com/967787/70853630-2a20fa80-1e76-11ea-9272-e7b36af30c90.jpg)
![IMG_20191214_131730](https://user-images.githubusercontent.com/967787/70853640-386f1680-1e76-11ea-8192-ef3c221d8ebd.jpg)

**Comment by feren** [comment]
Did you relaunch Calamares right after updating that without rebooting?

**Comment by feren** [comment]
Oh, nevermind, I just realised why it will still error out: It needs an ISO update. :man_facepalming: 

I'll rebuild the ISOs and update 'em in a bit.

**Comment by feren** [comment]
Feren OS Next has had an ISO Update just released, with a 64-Bit Feren OS ISO Update uploading right now. Therefore, this issue can now be closed.

**Comment by ApertureDevelopment** [comment]
The next error that happens on a Lenovo 2 11 with uefi

**Comment by feren** [comment]
*sigh* I'll do another ISO update... I REALLY need to put refreshing the CDROM package lists in the Make ISO script...

**Comment by feren** [comment]
In case this next ISO upload (currently building) doesn't fix the issue, it'd be best to open an issue for this other bug as this chat is not related to the original issue at this point.

**Comment by feren** [comment]
The ISO was updated again.

**Comment by feren** [comment]
The ISO was updated again.

**Comment by feren** [comment]
@ApertureDevelopment Does the new ISO work for you?

**Comment by Anonymo** [comment]
Latest ISO worked for me.  Thanks
