### ISSUE TITLE
UI Redesign - Theme

### ISSUE THREAD

**Issue by feren** [feren-OS/Bug-Reporting-Center#70]
**Describe the bug**
Feren OS's theme is alright enough, however it depends on the survival of Arc to be maintainable, and I feel that with the move to Plasma recently Feren OS should have a new pair of clothes some point in the future to mark this milestone and to improve maintainability.

As such, the following must be considered:
- Upstream basage - better to base on the original upstream theme that the most commonly used application toolkit is built with than to base on forks of that theme. That way we can reduce application issues and how much we depend on the maintenance of the base code to keep the Feren OS theme maintained.
- Contrast - the default themeing of Feren OS should have sharp contrast to allow users to easily read what's on their screens. The user is free to mess this contrast up themselves after the fact if they so desire with colour scheme editing, however the initial product should be designed with contrast in mind.
- Design - the design should remain faithful to Feren OS's current identity, overall, while still being a little different and slightly more modern if required. Adwaita's newest design seems like a perfect design fit for Feren OS to base off of.

As such, the following has been considered for a new Feren OS theme redesign:
- GTK Theme: Fork a version of Adwaita from after they introduce the newest Adwaita design and work from that code to make a Feren OS theme using the foundations of the Adwaita theme
- Qt Application Style: Fork Adwaita-Qt, make it support KDE colour schemes, tweak it to match with the Feren OS Adwaita-based GTK theme and ultimately ditch Kvantum for the default Application Style to provide native colour scheme support on the default style
- Plasma Theme: Make minimal edits to the theme to improve consistency on the controls that are common between Plasma Desktop Workspace and applications

Extra objectives:
- Make the GTK theme support Plasma colour schemes just like Breeze does

**Comment by Elbullazul** [comment]
have you decided which approach you're going to take yet?

**Comment by feren** [comment]
I think I'm going to take the approach that was initially considered above. I've tested modifying the Adwaita SCSS to success.

**Comment by feren** [comment]
The Theme Redesign project has officially come to a finish. Feren OS's new theme is now available as an update over the older one.
