### ISSUE TITLE
Opera browser could not be installed from Web Browser Manager on Virtual Box machine

### ISSUE THREAD

**Issue by saidbakr** [feren-OS/Bug-Reporting-Center#75]
I have tried to install Opera from Web Browser Manager and after updating packages shortly after start downloading I got a box with error message: `An error occured` without any further details.

Since, Opera website is blocked in my country, I tried to use a VPN and I repeated the try, but also the same error message is revealed.

 Feren OS 2019.12
VirtualBox 6.0 Machine hosted on Kubuntu 18.04.
![Screenshot_20191226_164100](https://user-images.githubusercontent.com/467554/71479788-a9abb380-27fe-11ea-92e0-5367acaf5e05.png)

**Comment by feren** [comment]
Web Browser Manager installs the Opera browser as Superuser/Root. Make sure your VPN has changed the network Root uses to be connected through the VPN as well. I won't be able to help you on doing that, unfortunately, as I don't know how, though.

Alternatively go into Welcome Screen -> Install Software -> Snap Apps, open Snap Store and install Opera as a Snap.

**Comment by saidbakr** [comment]
> Web Browser Manager installs the Opera browser as Superuser/Root. Make sure your VPN has changed the network Root uses to be connected through the VPN as well. I won't be able to help you on doing that, unfortunately, as I don't know how, though.
> 
> Alternatively go into Welcome Screen -> Install Software -> Snap Apps, install and open Snap Store and install Opera as a Snap.

Indeed, I don't know how to make network Root connected through VPN. However, I use Proton VPN through its python script installed on the system by the command `sudo protonvpn c` and using `sudo` makes me think that it may using the Root you mean.

However, your suggestion about using snap is great. Also, I, already, have downloaded the Opera deb package from their website, of course it was accessed using the VPN, and I will try to install it using that deb package.

**Comment by feren** [comment]
Gonna reopen this to remind myself to add browser installation logging to Web Browser Manager.

**Comment by saidbakr** [comment]
I will not install Opera using deb package due to this installation announcement:
![Screenshot_20191226_181825](https://user-images.githubusercontent.com/467554/71482646-6d7f4f80-280c-11ea-9329-984926accc7f.png)

In othere words, it may remove the Feren desktop as well!

**Comment by feren** [comment]
Working on a huge Web Browser Manager update to allow for log writing for each browser installation.

**Comment by feren** [comment]
Try not to install that DEB, I'll link to the correct DEB in a bit.

**Comment by feren** [comment]
https://deb.opera.com/opera-stable/pool/non-free/o/opera-stable/opera-stable_65.0.3467.69_amd64.deb

**Comment by feren** [comment]
@saidbakr An update to Web Browser Manager was released which adds logging to the mix. If you have any further issues, please provide the log in /tmp/opera-install-log.

**Comment by saidbakr** [comment]
After the last update, the contents of the regarded log file has nothing about Opera or its installtion, a copy of its contents is bellow:
```
Hit:1 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:3 http://repo.vivaldi.com/stable/deb stable InRelease
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease
Ign:6 http://packages.linuxmint.com tina InRelease
Hit:7 http://repo.vivaldi.com/stable/deb stable Release
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:9 http://dl.google.com/linux/chrome/deb stable Release
Hit:10 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease
Hit:11 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease
Get:12 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:13 http://packages.linuxmint.com tina Release
Hit:14 http://ppa.launchpad.net/noobslab/apps/ubuntu bionic InRelease
Get:15 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:16 https://gitlab.com/feren-os/feren-repositories-neon/raw/master stable InRelease [1,702 B]
Get:17 https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable InRelease [10.0 kB]
Fetched 264 kB in 4s (72.9 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
```

**Comment by feren** [comment]
Does /etc/apt/sources.list.d/opera-stable.list exist? If so try deleting that file via Files -> Open as Root and then try the Install button again. Opera appears absent from your APT package list refresh sources according to what is in the log.

**Comment by saidbakr** [comment]
> Does /etc/apt/sources.list.d/opera-stable.list exist? If so try deleting that file via Files -> Open as Root and then try the Install button again. Opera appears absent from your APT package list refresh sources according to what is in the log.

Well, after deleting the specified file, this is the output of `/tmp/opera-install-log`:

```
Ign:1 https://deb.opera.com/opera-stable stable InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.canonical.com/ubuntu bionic InRelease
Hit:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Err:5 https://deb.opera.com/opera-stable stable Release
  Could not handshake: Error in the pull function. [IP: 151.101.194.202 443]
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:8 http://packages.linuxmint.com tina InRelease
Hit:9 http://dl.google.com/linux/chrome/deb stable Release
Hit:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:11 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:12 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease
Ign:13 http://repo.vivaldi.com/stable/deb stable InRelease
Hit:14 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease
Hit:15 http://packages.linuxmint.com tina Release
Hit:16 http://repo.vivaldi.com/stable/deb stable Release
Hit:17 http://ppa.launchpad.net/noobslab/apps/ubuntu bionic InRelease
Get:18 https://gitlab.com/feren-os/feren-repositories-neon/raw/master stable InRelease [1,702 B]
Get:19 https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable InRelease [10.0 kB]
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
```
It seems that the IP of opera is blocked.
