### ISSUE TITLE
Chrome autofill message text in feros dark theme unreadable

### ISSUE THREAD

**Issue by draeder** [feren-OS/Bug-Reporting-Center#76]
Chrome autofill message text in dark theme unreadable

**Comment by feren** [comment]
Can you provide a screenshot of this, please, as long as there's no personally identifiable information in it? (you can delay screenshots in Spectacle to grab a screenshot of a popup that otherwise won't appear in time for a screenshot)

**Comment by draeder** [comment]
Here you go... Thanks for the tip on using Spectacle!

![image](https://user-images.githubusercontent.com/15527661/71547922-17292280-296c-11ea-8e84-abd557f25ccb.png)

**Comment by feren** [comment]
I'm not sure if that's potentially a Google Chrome issue or not. Try going into System Settings -> Theme -> GNOME / GTK Application Style and then changing the theme over to Breeze, followed by applying a dark colour scheme in System Settings -> Theme -> Colours and then restarting Google Chrome so it has the new colour scheme in it.

**Comment by draeder** [comment]
Thanks that is making a difference, but it's not perfect. If the menu is dark the text should always be light. I'm now using the Breeze Dark Colors, but see this: 

![image](https://user-images.githubusercontent.com/15527661/71551012-5f633780-29a2-11ea-947a-661d36ec935a.png)

**Comment by draeder** [comment]
I don't know what things are written in, but I once posed a question for javascript about a similar challenge: https://stackoverflow.com/questions/12043187/how-to-check-if-hex-color-is-too-black

**Comment by feren** [comment]
Alright, the last theme to check with is Adwaita Dark but with a light colour scheme in Colors just in case. If it happens on Adwaita Dark, it's very likely an upstream issue with Google Chrome itself.

**Comment by feren** [comment]
To get Adwaita Dark apply 'Default' for the GTK3 theme and tick "Prefer Dark Theme" to the right of that and apply. Then close Chrome entirely and launch it up again.

**Comment by feren** [comment]
Since I've just confirmed it happens on the built-in GTK theme, this must be an upstream bug.

**Comment by feren** [comment]
Reported Upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1039123&can=2

**Comment by feren** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=914974
