### ISSUE TITLE
Barrier no longer resides in task tray

### ISSUE THREAD

**Issue by draeder** [feren-OS/Bug-Reporting-Center#79]
The Barrier application for mouse / keyboard sharing used to show in the task tray in Feren OS Classic, but is no longer doing that. 

Because of this, when trying to launch Barrier (from the start menu) it runs a new instance instead of loading the already running instance. So it is no longer configurable.

**Comment by feren** [comment]
What version of Barrier are you using, the one from Store (Flatpak)?

**Comment by feren** [comment]
I can confirm this on the Flatpak version.

**Comment by draeder** [comment]
Thanks - I can work around this by disabling "Minimize to System tray" under Barrier > Change Settings.

**Comment by feren** [comment]
You might want to get in touch with the maker of this Flatpak about the lack of a system tray icon in Plasma.

**Comment by feren** [comment]
^
