### ISSUE TITLE
Microsoft Teams Preview shows wrong icon on task bar but right icon on task tray in Feren OS Plasma

### ISSUE THREAD

**Issue by draeder** [feren-OS/Bug-Reporting-Center#80]
Microsoft Teams Preview shows wrong icon on task bar but right icon on task tray in Feren OS Plasma

It shows an Xwindows icon instead.

Never had this issue in classic.

**Comment by feren** [comment]
Are you using the official DEB packaged Microsoft Teams Preview application?

**Comment by draeder** [comment]
@feren Yes - Sorry, I forgot to mention where I got it from. There's an unofficial version of Teams in the store, but I felt more comfortable with the official version direct from Microsoft.

**Comment by feren** [comment]
Alright, so we're both using the same version. Weird, it shows the correct icon in both places for me (the 'Preview' icon in the taskbar and the system tray icon in the task tray) on my main machine.

**Comment by feren** [comment]
I'll check a fresh Feren OS installation though just to be sure.

**Comment by draeder** [comment]
I had Teams installed first on Feren OS Classic then updated to Feren OS Plasma if that helps. Notably, now the issue isn't occurring at the moment. Seems it might be related to switching desktop themes, and then issue is resolved after rebooting? I'm not 100% sure

**Comment by feren** [comment]
Yeah no I can't reproduce it here.
![image](https://user-images.githubusercontent.com/11057934/71550137-4027d280-29c1-11ea-9f8a-b8cd732adf00.png)
