### ISSUE TITLE
Feren OS. updated by itself?

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Bug-Reporting-Center#83]
My Feren OS updated by it self. I didn't hit anything when i rebooted new welcome screen came up. Everything was updated. Is this correct if anyone is on older Feren OS it will auto update it self. It is werid i didn't touch anything which is what i would expect from Windows 10 HAHAHA.

**Comment by feren** [comment]
This is normal behaviour. If you want it gone, consult https://feren-os-user-guide.readthedocs.io/en/latest/updatemanager.html#disabling-automatic-updates .

**Comment by tjw0lf** [comment]
The last part was Joke Feren :) Have Happy Holidays Thank you for your hard Work. do you have Donate button yet 

That's nice feature. For people that don't update. Updated is good for secure
