### ISSUE TITLE
GRUB loader no longer present at boot

### ISSUE THREAD

**Issue by draeder** [feren-OS/Bug-Reporting-Center#84]
I initially installed Feren OS Classic as a dual boot option alongside Windows 10. I then used the transfer tool to get Plasma when it was available.  Since then, I am no longer being presented with the GRUB bootloader upon boot and now I can't get back into Windows. 

Do I really want to get back into Windows? No, not really... So far Feren OS is doing absolutely everything I need.... But I need the fallback since I use this computer for work. If something doesn't go right I need to quickly get back into Windows.

**Comment by feren** [comment]
Go into a Feren OS Live Session and run Boot Repair.

**Comment by draeder** [comment]
Cool thank you. I'll give that a try. If it's just a timer issue, I can figure it out from there.
