### ISSUE TITLE
Resize Screen resolution using Virtual Box 

### ISSUE THREAD

**Issue by Bernd1EH** [feren-OS/Bug-Reporting-Center#85]
Hello,
I just instlled feren-OS using Virtual Box "Version 6.1.0 r135406 (Qt5.12.4)". Trying to resize the screen resolution from the initial value of 800x600 to anything else does not work. It just jumps back to 800x600. Any idea?

**Comment by feren** [comment]
This is two things:
1. An upstream issue with KDE Plasma that is known to them, if I recall correctly. I can't find the bug report though but I swear I've seen it reported on their bug tracker.
2. Workaroundable. See, the display driver affects whether or not VirtualBox allows automatic guest screen resolution resizing.

In VM Settings -> Display there is an option called 'Graphics Controller'. One or more of these options supports Guest Screen Auto-resizing that isn't the one that is currently selected. Once you've got the correct one, logging in will give you an automatically resized guest screen.
Also BTW don't choose "None" for obvious reasons.

**Comment by Bernd1EH** [comment]
Hello,
I tried to find the setting and I believe it is "File - Settings - Display - Maximum Guest Screen Size" which I can set to automatic, none or hint. I tried automatic and hint, but in my screen always goes back to 800x600. I tried Ubuntu, which works. Tomorrow I might try Mint too.

**Comment by feren** [comment]
![Peek 2019-12-30 17-46](https://user-images.githubusercontent.com/11057934/71593507-500ff580-2b2c-11ea-931d-35ee4eabc7bb.gif)

**Comment by Bernd1EH** [comment]
Hi, 
I did reinstall using VBoxSVGA. With that I can resize the screen. Thanks a lot, Bernd.
