### ISSUE TITLE
feren OS plasma grub shows minimal menu/using boot/efi(active) boots direct to fern login window

### ISSUE THREAD

**Issue by lestoilnr** [feren-OS/Bug-Reporting-Center#86]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

**Describe the bug**

**Steps to Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by feren** [comment]
I'm going to need more information than that, otherwise to me it sounds like an intentional feature.
