### ISSUE TITLE
Dual Monitor Bug

### ISSUE THREAD

**Issue by Kei84** [feren-OS/Bug-Reporting-Center#88]
During the use of the Live Session, it automatically picks up the dual screen with out a problem, after install it mimics the primary screen on the second monitor. i have to go to Display configuration and change the layout of the display and save it after each reboot. this is not a user error.

**Comment by feren** [comment]
So is the screen layout on the first login different to how it is on the live session?

**Comment by Kei84** [comment]
When using live session. It reads the dual monitor with both screens side by side. After install it reads the primary screen overlapping the secondary screen, causing the second screen to mimic the first screen.

**Comment by feren** [comment]
So, Screen Duplicating by default on the fresh install?

**Comment by Kei84** [comment]
Yes.

**Comment by feren** [comment]
Are you doing a fresh install or importing a /home directory from another install?

**Comment by Kei84** [comment]
Fresh installs

**Comment by feren** [comment]
Is this your first OS using Plasma or have you tried other OSs using Plasma in recent past? (if you're new to Linux, just say yes)

**Comment by Kei84** [comment]
First time using it,but I fail to see how that is relevant to the issue at hand since it works in a live session but not after it being installed. New to Linux no, I've used Linux before, it is not my daily desktop as I use Ubuntu server for my home server.

**Comment by feren** [comment]
I was just thinking that if you had prior experience with Plasma elsewhere it'd make it easier to know if this is maybe just an upstream issue with the service 'kscreen'.

**Comment by feren** [comment]
Also by "screen overlapping the second screen", does that mean the second monitor shows the first screen along with the first monitor showing the first screen or that the two screens are literally overlapping each other on one monitor?

**Comment by feren** [comment]
_Going to bed for now, see you here in a few hours if the issue still persists._
