### ISSUE TITLE
Unlock screen from sleep fail

### ISSUE THREAD

**Issue by tripleripple** [feren-OS/Bug-Reporting-Center#92]
Twice now the unlock process when the laptop (Lenovo T510) is sleeping has failed.  The characters are typed in and then when I hit enter it is as though the enter key is not recognized.  Deleting the characters, re-entering them and then hitting the forward arrow button results an the error message of unlock fail.  The only recovery solution is to power down and to restart the computer.  This does not happen every time but only on these two occasions.

**Comment by feren** [comment]
Workaround: Switch User > Start New Session > Log In via the Login Screen again

**Comment by feren** [comment]
I would be able to reproduce this except I don't get the unlock fail issue following that.

**Comment by tripleripple** [comment]
I will try the workaround the next time it happens.  Thus far no issues on awaking from sleep mode.

**Comment by feren** [comment]
Any occurrences of this since?

**Comment by flyingthings93** [comment]
I've experienced this same thing, several times.  It's a pain because my laptop has a broken power switch, so it's really hard to power it down and back on.  I'm looking forward to trying the work-around described above the next time.  
Maybe not coincidentally, mine is a Lenovo also, Z580.
Otherwise, I'm loving Feron and am thinking that it will become my OS on this device for a good while.

**Comment by tripleripple** [comment]
Another incident last night.  The last two times I left the machine running to download a large ISO file.  The screen turns off after a while and the system is left powered on.  In the morning the unlocking routine failed to conclude successfully resulting in another cold boot.  Hope this helps.

The workaround did not restore the session.  Starting a new session left a black screen and the mouse curser that followed my finger on the trackpad.  The feren logo with the spinning circle never displayed.  The only recourse was a reboot of the system.

**Comment by feren** [comment]
Are you on SDDM or on the default Feren OS Display Manager (LightDM)?

LightDM has the Feren OS logo on the bottom-left corner.

**Comment by tripleripple** [comment]
Not sure which display manager it is specifically but the Feren logo is on the bottom left corner and the pop up launcher uses cascading pop up menus.

**Comment by feren** [comment]
LightDM, then. Alright.

**Comment by flyingthings93** [comment]
I had another incident, also, and had the same outcome as tripleripple above when I tried the workaround. 
Interestingly, I may have actually fat-fingered my first attempt at logging in, which may be an important clue.  Could it be that if one does not get their password right on the first try, subsequent tries will also fail?  Though, it seems like if that were the case, we'd be hearing about this from a lot more people!
If I have some time to kill at some point, I may try entering my password incorrectly on purpose and report back.

**Comment by flyingthings93** [comment]
I had another incident, also, and the same outcome to the workaround as described by tripleripple above.
Interestingly, I may have actually fat-fingered my first attempt at logging in from the wake-up screen, which could be a clue.  If I have some time to kill at some point, I may try entering an incorrect password on purpose and report back.

**Comment by flyingthings93** [comment]
I haven't gotten around to testing my theory, yet, but I had another incident again just now and the workaround worked this time, my theory is already brought into question.

**Comment by feren** [comment]
There is an upstream bug with the code the Feren OS Lock Screen theme is based on where pressing ENTER after the first failed unlock attempt yields no unlock triggering, however that's surely unrelated.

**Comment by flyingthings93** [comment]
Yes, I've observed that phenomenon multiple times along the way and I agree, it seems a different problem.  Sometimes, the ENTER key doesn't work on first attempts either, but I haven't been able to discern any pattern to it -- Seems pretty random.  
I just had a chance to test a couple of times of putting the machine into standby, waking it up, and trying to log in with purposefully wrong passwords on the first attempt.  Both times, I was able to enter the correct password for a second attempt and get in with no problem.  So, my theory is blown.  Just for the sake of thoroughness, though, one of the times I used the ENTER key on the first attempt and clicked on the screen button the other time.

**Comment by flyingthings93** [comment]
The workaround just worked again.

**Comment by tripleripple** [comment]
Sadly the workaround failed for me again.  Started a new session and the login screen appeared on the left side of the screen.  Entered the password, hit enter and then the empty (no characters present) login screen reappeared in the middle of the screen rapidly followed by the black screen with the mouse cursor  able to move around with my finger movement.  Finally had to reboot as nothing changed for the longest time.

**Comment by feren** [comment]
Something tells me at this rate that it's an upstream Plasma issue... guess I'll go bug report hunting.

**Comment by feren** [comment]
Actually, could someone try reporting it to bugs.kde.org by chance? Might get some more exposure over there so that it can get resolved sooner.

By the way, if someone does report it over there, be sure to give everyone else here a link to the bug report on KDE's own Bugtracker.

**Comment by flyingthings93** [comment]
I've read through a number of bug reports at KDE Bugtracking System using the search terms, "plasma unlock screen", and have not found a reported bug that seems like ours in enough ways to give me any clues.  So, I'm  preparing to report our bug as new, but the first screen I encounter when doing so says that I "must pick a product on which to enter a bug" and provides a very long list from which to choose.  What do you suggest I pick?

**Comment by feren** [comment]
kscreenlocker is the lock screen, so if there's a kscreenlocker option go for kscreenlocker.

**Comment by tripleripple** [comment]
Had four more incidents and then surprisingly another similar one using Libreoffice writer.  My trackpad suddenly became unresponsive during a composition (the only time this has happened BTW).  I could use the arrow keys but not the trackpad.  Since we both are using Lenovo's maybe it has something to do with the trackpad driver?

**Comment by flyingthings93** [comment]
OK.  Product, kscreensaver.  
Next, it asks for what component and a version number.  The component, I'm guessing is kcheckpass.  Versions they offer to select from are, 5.8.7, 5.10.2, or 5.10.3.  There is also an "unspecified" option for the version number.

**Comment by feren** [comment]
I'd recommend saying 'unspecified' if 'kcheckpass' is the only option. They can specify it later if needs be. KScreenLocker is 5.17.5 in Feren OS currently, however it'll be upgraded to the latest version once #122 is completed.

Also I have a Lenovo hybrid laptop myself, so I'm not sure if it's Lenovo-related as I don't have any trackpad issues.

**Comment by feren** [comment]
Feren OS now has Plasma 5.18 in the repositories. Update everything so you're on Plasma 5.18 and try again to see if the issue still persists.

**Comment by tripleripple** [comment]
That was a major update!  I left the machine running overnight to finish and came back to the following message:

The screen locker is broken and unlocking is not possible anymore.  In order to unlock switch to a virtual terminal ( e.g. Ctrl+Alt+F2), log in and execute the command:  loginctl unlock-session C2
Afterwards switch back to the running session (Ctrl+Alt+F7).  

During the terminal session a second message advised me to to run a Canonical Livepatch (https://ubuntu.com/livepatch) so that I would have less reboots and greater kernel security.

Pretty serious patch process.

**Comment by feren** [comment]
Yeah, that's a downside that I need to figure out to updating Plasma: The lock screen breaks. It does that upstream anyway too.

If that happens, just do as it tells you to do on that screen to manually unlock your session.

**Comment by tripleripple** [comment]
That did not take long :-(  Another unlock failure today.  The virtual terminal route brought back the session but with a black screen sadly.  Had the cursor and lots of hard drive access and the pop up sounds but no display.  The only recourse was yet another reboot.

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
