### ISSUE TITLE
USB DAC lacking support

### ISSUE THREAD

**Issue by Jakihro** [feren-OS/Bug-Reporting-Center#93]
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

-Audio panel device selection

**Describe the bug**

-External USB DAC unit is not recognized by Feren-OS as a usable sound output. 
The unit in question is a Massdrop Grace SDAC, running an AKM AK4452 DAC chip and an XMOS XU208-128-TQ64 USB interface.

Replugging the unit reveals it as a selectable sound output temporarily, but upon initialising audio from any source, device disconnects and sound output reverts back to on-board audio.
The unit disappears from the USB Devices list also when this occurs. I can't find it in the IO-Ports menu regardless of whether it's recognized by the system or not.

**Steps to Reproduce**

-Plug in unit in question, play audio.

**Expected behavior**

-Expected unit to be recognized as a selectable audio output by default, without issues. This is the behavior I've experienced in most other distros I've used (Linux Mint Cinnamon, Solus OS, Manjaro, among others). I'm concerned as to whether similar issues may occur with other similar USB devices.

**Screenshots**

The unit in question, as displayed in various lists 
![screenshot](https://user-images.githubusercontent.com/17137804/71864546-5a1f8e80-3100-11ea-97c6-64ffe49c9ba9.png)

![screenshot_1](https://user-images.githubusercontent.com/17137804/71864556-60156f80-3100-11ea-8438-2e8a2aa575dc.png)

![screenshot_2](https://user-images.githubusercontent.com/17137804/71864597-7d4a3e00-3100-11ea-8bc1-127a2f0c1ac1.png)

The volume settings upon running "Speaker Placement and Testing", resulting in the unit disconnecting
![screenshot_3](https://user-images.githubusercontent.com/17137804/71864599-80452e80-3100-11ea-927e-6877bd9a2822.png)

![screenshot_4](https://user-images.githubusercontent.com/17137804/71864603-83401f00-3100-11ea-81b0-e01b7ab18ac6.png)

**Additional context**
Add any other context about the problem

**Comment by feren** [comment]
I'm not sure on what this issue is without being able to reproduce it here currently. I'll mark it for now under these...

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
