### ISSUE TITLE
Printer options not saving in Settings

### ISSUE THREAD

**Issue by DarrenDoesDnD** [feren-OS/Bug-Reporting-Center#94]
I was trying to change the default printer settings to Toner Save Mode = On and Darkness = Light through Plasma Settings, but the changes refused to save. 
I also couldn't get CUPS web admin to authenticate me, even though I am a member of lpadmin and I tried changing the cupsd.conf to not require authentication.
I ended up having to open systemsettings5 from a command prompt as root to get it to save.

**Comment by feren** [comment]
Does this still happen?
