### ISSUE TITLE
settings..screen unlock, black thumbs

### ISSUE THREAD

**Issue by jaspi72** [feren-OS/Bug-Reporting-Center#95]
**FerenOS Next
**Settings..screen lock..theme

Dont know when this start but noticed it couple days ago.
It was working when installed FerenOS

**Comment by jaspi72** [comment]
![no thumbs](https://user-images.githubusercontent.com/34282195/72058115-3e6ee080-32d8-11ea-8bf0-acf4a7dac97d.png)

**Comment by feren** [comment]
It probably just needs time to generate the previews. Try checking if the ones on the top of the list aren't black.

**Comment by jaspi72** [comment]
Waiting not work. same problem on desktop background thumbs, whats wrong?
![kuva](https://user-images.githubusercontent.com/34282195/72172156-27fe7d00-33dd-11ea-8994-626cb764e300.png)

**Comment by feren** [comment]
I honestly have no idea, then. Just remember that when it does work it can take a long while for the thumbnails to all generate. If you installed with a /home partition that was taken from another OS installation left intact, make sure you have complete read/write access and ownership of HOME/.cache and everything inside of there.

**Comment by jaspi72** [comment]
Hmm, i installed this FerenOS next with beta2.iso or what is was, dont remember anymore but 09.2019 anyway. Is it possible updates has done something nice and now is how it is :).
Damn do i need to make new clean install..

**Comment by dominichayesferen** [comment]
Does this still occur in Feren OS November 2020 Snapshot?
