### ISSUE TITLE
Nemo File Manager: (Global) Menu/Preferences/Behavior:Single click to open items 

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#97]
**Package Name or Section of Feren OS where this bug resides**
Nemo File Manager

**Describe the bug**
1. Menu item "Edit > Preferences" doesn't open sometimes from the "Global Menu".
2. Menu item "Edit > Preferences > Behavior > Single click to open items" doesn't remain effective (unlike other preferences) after logging out.
3. Desktop items (e.g. URL Link "Send Feedback or Report an Issue" doesn't open on single click at all.

**Comment by feren** [comment]
This is controlled by System Settings -> Workspace Behaviour instead.

**Comment by feren** [comment]
Other than that, the Global Menu issue should be in another issue.
