### ISSUE TITLE
Grub menu specifies Feren OS as Ubuntu

### ISSUE THREAD

**Issue by Sadi58** [feren-OS/Bug-Reporting-Center#99]
**Package Name or Section of Feren OS where this bug resides**
grub2?

**Describe the bug**
When grub menu is updated after a kernel upgrade or via terminal command "sudo update-grub" Feren OS is named as Ubuntu although another distro such as Linux Mint names it correctly as Feren OS if it's allowed to take over the grub installation instead.

**Comment by Sadi58** [comment]
PS: **Timeshift** snapshots are also named **Ubuntu**.

**Comment by feren** [comment]
This has been fixed by package `grub-modifications-feren`.
